### ISSUE TITLE
[Feature Request] Allow auth endpoint to serve sign_in pages as well

### ISSUE THREAD

**Issue by linuxgemini** [oauth2-proxy/oauth2-proxy#1015]
Mentioned at https://github.com/oauth2-proxy/oauth2-proxy/pull/762#issuecomment-768360213 by @pcneo83

> Is there any chance on reconsidering the missing functionality that hasn't been captured in #957 please? While `X-Forwarded-*` headers are now supported to make the redirects capture the path correctly, this does not work on the initial unauthenticated requests with Traefik. The dependency on `errors` middleware to capture 401 status and then initiate `/oauth2/sign_in` breaks the signin redirect in the browser (when --skip-provider-button is true).
> 
> The `--auth-endpoint-sign-in` option suggested in [#762 (comment)](https://github.com/oauth2-proxy/oauth2-proxy/pull/762#issuecomment-688440183) and implemented in this PR is the only missing functionality and would greatly help in using Traefik FowardAuth using a single endpoint `oauth2/auth` and will also fix
> 
> * --skip-provider-button redirect failure in the browser
> * missing unauthenticated request URI path in the redirect

This should be implemented, as it is noted that when `--skip-provider-button` is set, the redirect doesn't work.

**Comment by pcneo83** [comment]
@linuxgemini thank you very much for creating this feature request from my comment left on the old PR.

To provide some context on how we intend to use, we have a Kubernetes cluster using Traefik ingress with multiple services exposed through a single ALB on their own endpoints. The idea is to provide an `Auth as a service` solution using an on/off flag that each service could set during deployment. The platform and deployment automation takes care of correct configuration of the ingress routes, along with `/oauth2` path forwarding to `oauth2-proxy` service.

We are initially looking to cater for two types of services:
- A service that wants all paths protected (takes care of OAuth login) with an automatic signin redirect
- A service that wants more control over which paths to protect with an automatic signin redirect
- A service that wants to explicitly initiate the login call with more involvement in control and error handling from their frontend code

What we were missing to cater for the above is an option to redirect to sign page by `oauth2-proxy` without breaking when `skip-provider-button` is set to `true`. Based on the #762, what I would like to propose is to:
- overload the `/oauth2/auth` request using a boolean query string flag like `redirect_signin` that will either redirect automatically or return a `401` depending upon the flag being set to `true`

The advantage of QS flag above instead of an `oauth2-proxy` config parameter is that
- Only one oauth-proxy service can be run per provider
- Multiple Traefik ForwardAuth middlewares can be configured, one with `/oauth2/auth?redirect_sign=true` and another with `/oauth2/auth?redirect_sign=false`

Depending upon the choice of individual services, the relevant ForwardAuth middleware configuration can be applied on the service ingress configuration.

I'm happy to submit a PR for this as we are currently using a patched version (which includes the above) on our platform.

**Comment by linuxgemini** [comment]
Possible Traefik bug, tracking at https://github.com/traefik/traefik/issues/7872
