### ISSUE TITLE
Question: Call auth server /userinfo endpoint and forward content to resource servers

### ISSUE THREAD

**Issue by fabian-ifflaender-triveme** [oauth2-proxy/oauth2-proxy#1037]
I would like oauth2-proxy to get the userinfo from authorization server after getting the access_token. I tried to figure out whether oauth2-proxy is able to do that. But I could not get an answer from your documentation.

## Expected Behavior

I would like to have something like that:

- The user is redirected to the authorization server to login.
- The user is redirected back to oauth2-proxy.
- oauth2-proxy uses the token endpoint to get an access token
- HOWTO: oauth2-proxy uses the userinfo endpoint to get further user information
- HOWTO: oauth2-proxy caches the userinfo for every access_token (as long as valid)
- oauth2-proxy returns a session cookie
- HOWTO: oauth2-proxy provides access_token AND the userinfo to resource server

The HOWTOs are what I am not sure about.

## Current Behavior

That's the question. I saw that there is an option --profile-url that may point to a userinfo endpoint. But I am not sure what it does? Is it only for getting the E-mail address?

The concrete questions are:
- How does oauth2-proxy use the userinfo endpoint of authorization server?
- Is it possible to forward the userinfo results to the resource server with every request?

**Comment by JoelSpeed** [comment]
How OAuth2 Proxy uses the userinfo depends on which provider you are using. Some use it to get information such as user name, email and group information if they aren't provided in an ID Token as part of the authentication flow.

What kind of information are you looking to retrieve from the authorization server to provide to your application?

For now, as a workaround, you could pass the access token to the upstream server to access the userinfo directly, but in the long term we do want to make it customisable so that we will try to cache any user info that the admin wishes to be cached. We don't have an ETA for implementing that just yet though.

**Comment by fabian-ifflaender-triveme** [comment]
> For now, as a workaround, you could pass the access token to the upstream server to access the userinfo directly, but in the long term we do want to make it customisable so that we will try to cache any user info that the admin wishes to be cached. We don't have an ETA for implementing that just yet though.

I wanted to avoid the userinfo usage in every resource server. At the moment we solved that by adding the needed user attributes to the access_token. So now we do not need the userinfo endpoint at all. 

As an alternative solution caching the userinfo (let's say per instance of access_token) would be perfect within oauth2-proxy. That means we would not have to call userinfo endpoint that often or we would not have to coordinate the caches on the level of resource servers. From an architectural point of view I think caching the userinfo data in oauth2-proxy would be good. 

Thanks for your insights!
