### ISSUE TITLE
whitelist_domain in cfg file not working

### ISSUE THREAD

**Issue by betullapina** [oauth2-proxy/oauth2-proxy#1050]
Hi, sorry to bother, but I stumbled on a strange bug(?). _[I think is a bug]_

I've found a workaround for my case, but I thought to report here.

If I try to configure whitelist_domain in a cfg file i get an "invalid key error".

## Expected Behavior

permit use of whitelist_domain via cfg file

## Current Behavior

if I set in a cfg file the attribute: whitelist_domain=".mydomain.com:*"
I get this error:
```
ERROR: failed to load config: error unmarshalling config: 1 error(s) decoding:
* '' has invalid keys: whitelist_domain

I also tried whitelist_domain=".mydomain.com", with the same result

```
## Possible Solution
For now my solution is to set an env variable:  OAUTH2_PROXY_WHITELIST_DOMAIN=.mydomain.com:*

## Steps to Reproduce (for bugs)

map a volume:
-v '/mnt/user/appdata/oauth2-proxy/':'/etc/oauth2/':'rw' 

configure the cfg file to use:
--config=/etc/oauth2/oauth2_proxy.cfg

add the attribute:
whitelist_domain=".mydomain.com:*"

restart the docker 

## Context

I've configured a OIDC provider with keycloak as IdP and I was trying to logout the user in keycloak if the /sign_out endpoint was invoked.

I was getting the error of not permitted redirection.

I solved it using the env variable OAUTH2_PROXY_WHITELIST_DOMAIN so for me is not a blocking error. 

## Your Environment

docker in a Unraid Server (6.9)

- Version used: 7.0.1

**Comment by JoelSpeed** [comment]
Since the `--whitelist-domain` flag can be set multiple times, it becomes `whitelist_domains` and `OAUTH2_PROXY_WHITELIST_DOMAINS` in the config and env respectively. This is noted in the first sentence of the config file section of the docs https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#config-file

This is not a bug, however, if you managed to get it to work with `OAUTH2_PROXY_WHITELIST_DOMAIN` (without the S), then that is a bug

**Comment by betullapina** [comment]
You were right in the env I used the "s".... sorry for the trouble.
