### ISSUE TITLE
[Question] Can I deactivate Endpoints like robots.txt?

### ISSUE THREAD

**Issue by DaBonse** [oauth2-proxy/oauth2-proxy#1068]
robots.txt endpoint is statically served by OAuth2 Proxy. But I need a different content of robots.txt.

I found no configuration option to override this endpoint.

Is there an option to deactivate this endpoint or override robots.txt in another way?

## Your Environment

Docker image: quay.io/oauth2-proxy/oauth2-proxy:v7.0.1

**Comment by JoelSpeed** [comment]
This isn't possible right now, but I don't see why we couldn't make it possible as part of the templates work we did recently.

We moved all of the static page content into the `pkg/app/pagewriter` directory, this is used at the moment for rendering the error and sign in pages, but could (perhaps even should) be used to render the robots page as well. This would allow users to override it by putting a file onto their system and pointing the template directory to it. Currently this is implemented so that if one template is missing, it falls back to the default template, so we could make this a backwards compatible change as well.

**Comment by DaBonse** [comment]
Thank you very much JoelSpeed. 
This solution would help me, and you answered also my next (unasked) questions about customizing login page.

Do you know when the new template solution will be stable released?

**Comment by JoelSpeed** [comment]
We are looking to release 7.1.0 by the end of march which will include these changes, however, I want to be clear, we haven't implemented this change for the robots page yet, so this may or may not be in that release depending on whether we find time to do this and/or some community member comes up with a PR.

**Comment by DaBonse** [comment]
Thank you very much, I understand.
