### ISSUE TITLE
session cookie for bearer authentication

### ISSUE THREAD

**Issue by sribee** [oauth2-proxy/oauth2-proxy#1069]
Support session cookie creation for bearer token(jwt) authentication
## Expected Behavior

In the normal SSO flow, session cookie is created upon successful authentication flow with identity provider and client uses it in subsequent requests. In the case of bearer token based pass thru, every call needs to carry the bearer token. It will be useful specify bearer token once and get session cookie in response, and use the cookie for subsequent calls.

## Current Behavior

Each call needs to carry the bearer token.

## Possible Solution

Create a session cookie on first call with bearer token and return with the response.

## Context

This will be useful in having secure machine to machine communication by avoiding the bearer token in all the subsequent calls.

- Version used:
7.0.1

**Comment by NickMeves** [comment]
Out of curiosity so I understand the use case:

For machine to machine communications, why do you prefer have a session cookie instead of just using your machine ID Token in every request?

I only see complexities and downsides:
- Your HTTP client code now needs to be stateful and maintain the session cookie
-  The session is less performant than the direct bearer token (It is compressed, encoded & encrypted). Raw ID Token just does a signature verification then extracts the claims.

**Comment by sribee** [comment]
thanks @NickMeves - our http client is already stateful and uses the session coolkie when invoked from a browser. 
We are now trying to embed it in an iframe of another client which already has a id_token that is valid. (both clients use same Identity Provider). So if a session cookie can be created on first call with id_token, then the client can maintain that session without the id_token to be present in all subsequent interactions.

**Comment by NickMeves** [comment]
This feels weird to me to support both for convention & security reasons:

(1) Convention: Bearer Token APIs are designed to get that header (`Authorization: Bearer TOKEN`) in every request. CLI to API or Machine to Machine. It's a pretty common design and they don't expect to get a session cookie back bloating up the response size.

(2) Security: If this returns a session, our `SessionState` in cookies/stores that are traditionally returned after interactive login flows have timing details that are decoupled from underlying tokens we get back from IdPs (set based on your own session duration options). What happens if we get an IDToken with 1 second left on its lifespan? Now the Session that gets created from it potentially has a lifespan much longer than that ID Token should've been allowed to grant access for.

**Comment by sribee** [comment]
> This feels weird to me to support both for convention & security reasons:
> 
> (1) Convention: Bearer Token APIs are designed to get that header (`Authorization: Bearer TOKEN`) in every request. CLI to API or Machine to Machine. It's a pretty common design and they don't expect to get a session cookie back bloating up the response size.

Yes, agree in the machine to machine case. But in our case, we are invoking the another app, which is already integrated with oauth2-proxy, so can make use of session cookie.

> 
> (2) Security: If this returns a session, our `SessionState` in cookies/stores that are traditionally returned after interactive login flows have timing details that are decoupled from underlying tokens we get back from IdPs (set based on your own session duration options). What happens if we get an IDToken with 1 second left on its lifespan? Now the Session that gets created from it potentially has a lifespan much longer than that ID Token should've been allowed to grant access for.

Can't the session cookie lifespan match the bearer token presented?

**Comment by NickMeves** [comment]
> Can't the session cookie lifespan match the bearer token presented?

Current functionality creates a session that lasts the configured length setup in the OAuth2 Proxy options, it doesn't look at the `exp` claims in a potential Access or ID Token (since all the providers are different and some might not have a claim structure in an Access Token).
