### ISSUE TITLE
Cookie replay issue when used for multiple domains

### ISSUE THREAD

**Issue by sepich** [oauth2-proxy/oauth2-proxy#1072]
## Current Behavior

We have multi-tenant environment where single oauth2-proxy is used for multiple customer managed domains like this:

domain1.com/ -> service1
domain1.com/oauth2/ -> oauth2-proxy

domain2.com/ -> service2
domain2.com/oauth2/ -> oauth2-proxy

And oauth2-proxy has only `--email-domain` configured (with google auth). This works fine as oauth2-proxy reads domain from `Host` header and cookie is set to domain automatically. 
But this leads to cookie replay security issue:  if domain1.com cookie is leaked somehow - it could be used to login to domain2.com. This is because redis key (or value) is not per-host but per-cookiename:
https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/session_storage#redis-storage

## Possible Solution

Could you please add option to also validate cookie data against domain?
For example to add `Host` to encrypted cookie content. For redis - use something like `{Host}-{ticketID}.{secret}` as a key.
The option could be mutually exclusive with `--cookie-domain`.

## Context

This is multitenant k8s env, where customers could host their services and expose them as Ingress.
Some sites could be marked as "private", which automatically adds `/oauth2 -> oauth2-proxy` to customers Ingress (and corresponding `nginx.ingress.kubernetes.io/auth-url` annotations).
Currently that means that same cookie could be used to gain access to all the sites in such scheme.
It is fine when you valid user to login to domain1.com, that means you are valid for domain2.com too.
But this is not fine, when you compromised domain1.com - means you compromised all of them.

## Your Environment

- Version used:
v7.0.1
```
      - args:
        - --provider=google
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --email-domain=company.com
        # --cookie-domain is not set
```

**Comment by NickMeves** [comment]
I think I am in a similar boat as you design wise but slightly different (distinct central auth domain from nginx ingress auth annotations, share's a top level `.example.com` corporate domain with all the consuming apps, so a central cookie set to `.example.com` can be used across all of them).

Both are scenarios are weak to this shared session storage when using a persistent store.

The challenge is, we can't tie it to a Host easily for installations the use the leading wildcard functionality of `--cookie-domain` and `--whitelist-domain`. E.g. I have hosts `a.example.com`, `b.example.com` & `c.example.com` all coming in riding the same `.example.com` cookie by setting `--cookie-domain .example.com`

Something that has been asked for a few times that might be an alternative solution: allowing stripping the OAuth2 Proxy session cookie (pure encrypted cookie or redis ticket) from the request before the upstream. Cause for the most part, that is worthless to the upstream (it's either encrypted or just a random nonce for a Redis ticket).

Would that work for securing your setup? (You were worried about a compromised backend server leaking cookies right? not a compromised client?)

Downside to that route -- some users take the session cookie at the backend and use it to call the `userinfo` endpoint to get the user session details instead of using the `X-Forwarded-*` auth headers.

**Comment by JoelSpeed** [comment]
Does having secure cookies not prevent this from happening?

If you're able to, you could set a list of cookie domains that are allowed and the cookie will be created for the best that matches, this may also help a little bit

**Comment by NickMeves** [comment]
> Does having secure cookies not prevent this from happening?
> 
> If you're able to, you could set a list of cookie domains that are allowed and the cookie will be created for the best that matches, this may also help a little bit

I think the concern in this shared tenancy architecture is the level of trust in all applications that share these session cookies.

If on the backend side, `AppA` is compromised with server-side code that can steal session cookies, now shared tenancy `AppB` & `AppC` are compromised. So everything is as weak as the weakest shared app.

**Comment by sepich** [comment]
> allowing stripping the OAuth2 Proxy session cookie from the request before the upstream.

We are already doing this, but that would not help if "notebook is stolen and cookie taken from browser" for example.

> you could set a list of cookie domains 

We do not use `--cookie-domain`, so cookie set for **domain1.com** is not sent to **domain2.com** and even to **sub.domain1.com** by browser.

> I think the concern in this shared tenancy architecture is the level of trust in all applications that share these session cookies.

Correct, we trust oauth2-proxy more that our customer's apps ;) So, in case cooke for domain1.com would be leaked, we want to reduce blast radius to domain1.com only. Because now the same cookie could be replayed to get access to domain2.com too (no matter if you using redis or encrypted-cookie scheme).
