### ISSUE TITLE
documentation/help regarding working with protected/password protected pages 

### ISSUE THREAD

**Issue by thapabishwa** [oauth2-proxy/oauth2-proxy#1123]
Currently I have setup oauth2-proxy with internal tools and I have to enter the password(for the page separately) after login with google. Can you point me to any documentation regarding how I could automate the password entering step.

**Comment by JoelSpeed** [comment]
Does your upstream service support basic auth? Or could it observe some sort of header that would allow it to trust the identity passed to it by OAuth2 Proxy. The answer to your question very much depends on how the authentication works for these internal tools

**Comment by thapabishwa** [comment]
Hi @JoelSpeed , in my case I have to send a payload to a specific api endpoint.

**Comment by JoelSpeed** [comment]
We don't have any way to send a request to a backend like this. If your application also supports some sort of authentication headers, we can help you set those up, but otherwise this isn't something we support and in this particular case, I'd lean towards we probably don't want to support it either. Trusting headers from a previous authentication system is pretty standard in my experience at least
