### ISSUE TITLE
Validating bearer JWTs fails non-deterministically

### ISSUE THREAD

**Issue by uipo78** [oauth2-proxy/oauth2-proxy#1151]
Validating bearer JWTs fails non-deterministically.

## Expected Behavior

If I send a request with the exact same, valid JWT in the Authorization header, I should expect the proxy to consistently accept the token as valid. It does not. 

## Current Behavior

The proxy fails to validate a fixed, valid JWT consistently, throwing this error in its logs when it fails:
```
[2021/04/08 15:08:45] [jwt_session.go:51] Error retrieving session from token in Authorization header: [unable to verify bearer token, not implemented, failed to verify signature: fetching keys oidc: get keys failed: 404 Not Found {"error":"HTTP 404 Not Found"}]
```

## Steps to Reproduce (for bugs)

The unfortunate part of reproducing this bug is that it is non-deterministic. That said, here's how I configured the proxy:
```
provider = "keycloak"
client_id = "[redacted]"
login_url = "[redacted keycloak URL]/auth/realms/[redacted Keycloak realm]/protocol/openid-connect/auth"
redeem_url = "[redacted keycloak URL]/auth/realms/[redacted Keycloak realm]/protocol/openid-connect/token"
profile_url = "[redacted keycloak URL]/auth/realms/[redacted Keycloak realm]/protocol/openid-connect/userinfo"
validate_url = "[redacted keycloak URL]/auth/realms/[redacted Keycloak realm]/protocol/openid-connect/userinfo"
extra_jwt_issuers = [
  "[redacted keycloak URL]/auth/realms/[redacted Keycloak realm]=[redacted client ID]"
]
cookie_secret = "[redacted]"
http_address = "0.0.0.0:4180"
upstreams = [
  "http://127.0.0.1:8080"
]
email_domains = "*"
ping_path = "/health"
scope = "email"
skip_provider_button = "true"
skip_jwt_bearer_tokens = "true"
pass_access_token = "true"
```

And if you want to see the random failures happen:
1. Get a JWT from Keycloak
2. Make a request to the web service whose authentication is being proxied by this project. Include that JWT as a bearer token in your request.
3.  Make the same request as above (with the same token) multiple times over and observe how some of the requests pass and others fail. 

## Context

This proxy sits as a sidecar on our services in production. What we're trying to accomplish is consistent authentication for our apps without requiring such logic being built into the web service itself.

## Your Environment

k8s version (AKS): 1.18.14

- Version used: 7.0.1

**Comment by uipo78** [comment]
Part of me suspected network failures to be the root cause of this problem, given this bug's random behavior, but I wouldn't've expected seeing a 404 if that were the case.

**Comment by NickMeves** [comment]
This looks like an issue with your Keycloak OIDC issuer here:

```
extra_jwt_issuers = [
  "[redacted keycloak URL]/auth/realms/[redacted Keycloak realm]=[redacted client ID]"
]
```

Under the hood, this uses `go-oidc` as the OIDC token verifier.  It will make a request to the OIDC discovery document (at `/.well-known/openidc-configuration`.  Then it will look up the `jwks_uri` field in that JSON and request the JWKS public keys to validate the token.

I'm guessing there's something not stable at the `jwks_uri` hosting if you are getting 404s fetching keys.

`go-oidc` will also cache JWKS responses based on the HTTP cache-control headers too (if you want more stability once the 404 issue is fixed).  It actually uses the cached public keys after the TTL until an invalid token comes in that triggers a fresh lookup of JWKS for a potential update (since they are intended to be dynamic) if I recall from their implementation.

**Comment by NickMeves** [comment]
FYI The existing Keycloak provider is dated and has a lot of issues. I recommend you use the OIDC provider until this PR is ready: https://github.com/oauth2-proxy/oauth2-proxy/pull/1107

**Comment by uipo78** [comment]
Sounds good
