### ISSUE TITLE
--insecure-oidc-allow-unverified-email does not apply to JWT Bearer token auth

### ISSUE THREAD

**Issue by maxbischoff** [oauth2-proxy/oauth2-proxy#1152]
When configuring JWT bearer token authentication with the `--skip-jwt-bearer-tokens` and turning off email-Validation with `--insecure-oidc-allow-unverified-email`, tokens with unverified emails cause an `email in id_token <email> isn't verified` error.

## Expected Behavior

The documentation text for `--insecure-oidc-allow-unverified-email` causes me to expect the unverified email to be ignored for any type of authentication:

> don't fail if an email address in an id_token is not verified

## Current Behavior

Authentication always fails for JWT Bearer Tokens with unverified email addresses.

## Possible Solution

If the behaviour is intended, the documentation should be updated to be more clear about which authentication options it does apply to.

Otherwise, the setting would probably have to be checked in https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/apis/middleware/session.go#L42

## Context

I am trying to accomplish M2M authentication using an OAuth2.0 Client Credentials flow, but cannot get tokens with verified emails.

## Your Environment

- Version used: 7.1.2

**Comment by NickMeves** [comment]
Our documentation admittedly needs some love 😅 

You are correct, any provider based settings only apply to the main provider.

Any extra OIDC bearer verifiers added with `extra-jwt-issuers` don't use those and use a generic implementation. Long term, when we roll out structured configs, we want to make the bearer verifier list a list of full providers that can take in full options.

Which provider are you using as the main provider? OIDC does respect the email verified in bearer mode: https://github.com/oauth2-proxy/oauth2-proxy/blob/42475c28f7f235c08777a24027fe8ec170763482/providers/provider_data.go#L142

We are working on refactoring other providers to be based on OIDC as a baseline for functionality -- otherwise they fall behind and they don't get any new features we add to OIDC first usually.

**Comment by maxbischoff** [comment]
We are currently using the keycloak provider. I can try to exchange it for the OIDC Provider and see if that fixes the issue.

**Comment by NickMeves** [comment]
We are looking to deprecate the Keycloak provider in favor of this in the future: https://github.com/oauth2-proxy/oauth2-proxy/pull/1107

In the meantime, since Keycloak is fully OIDC compliant -- the OIDC provider has much more features than the barebones Keycloak OAuth provider.
