### ISSUE TITLE
Typo in cli argument: "--exclude-logging-path" vs "exclude_logging_paths"

### ISSUE THREAD

**Issue by lathspell** [oauth2-proxy/oauth2-proxy#1159]
According to https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview the setting is called "exclude_logging_paths" (plural) but the CLI only accepts "--exclude-logging-path" (singular). The former seems right as more than one path can be specified.

Tested with Docker Image v7.1.2.

**Comment by JoelSpeed** [comment]
There is a note at the top of our docs that explains the precedence here: 
> Every command line argument can be specified in a config file by replacing hyphens (-) with underscores (_). **If the argument can be specified multiple times, the config option should be plural (trailing s).**

When arguments can be specified multiple times, the command line is deliberately singular as per convention in this project.

**Comment by lathspell** [comment]
That would make sense if I had to specifiy "--exclude-logging-path=/foo --exlclude-logging-path=/bar" on the CLI but it currently accepts multiple paths on one cli argument so shouldn't it be named with plural-s?
Anyway, just wanted to point out that it's irritating. Close if you want.

**Comment by JoelSpeed** [comment]
> on the CLI but it currently accepts multiple paths on one cli argument

That's an artifact of a change to the flag parsing library. Originally you had to specify individual values multiple times, now you can do either comma separated or multiple times. We chose not to make the breaking change to all the flag names as we are trying to move away from flag based config and move instead towards structured configuration files.

We aren't going to make any changes to these flags any time soon I would expect, especially since this would be a breaking change for no real gain (yes I appreciate there is confusion around the singular vs plural arguments, but we are hoping this won't be long lasting)
