### ISSUE TITLE
Second, third, etc. query parameters are dropped

### ISSUE THREAD

**Issue by janosi** [oauth2-proxy/oauth2-proxy#1169]
## Expected Behavior

If a client sends the original request as `/path?key=value&key2=value2`the same request should arrive to the backend service.

## Current Behavior

If the client sends the original request as `/path?key=value&key2=value2`only the first `key=value` query parameter arrives to the backend service after the authentication.

The problem is, that OAuth2-Proxy constructs the `state` as `nonce:/path?key=value&key2=value2` (in percentage encoded form, actually). When the OIDC provider makes the client call the /callback endpoint of OAuth2-Proxy the `state` value comes back as `nonce:/path?key=value&key2=value2` (unescaped). The go http.ParseForm() is called on this request, and that considers `key2=value2` as a separate query parameter, which is not part of the `state` parameter, so `key2` becomes a standalone map entry in the request.Form. Because of the `&`. On the other hand, OAuth2-Proxy assumes, that the whole original request URI is in the `state` parameter. So it uses what it finds there, and it redirects the client to that request URI. Which does not contain any but the first query parameter.

## Possible Solution

Alternatives considered:

1. OAuth2-Proxy replaces all the `&` in the query string with e.g. `+` (or anything that is compatible with the charset of `state`) before it puts that into the `state` parameter. 
2. OAuth2-Proxy looks for other query parameters than `code` and `state` at /callback, and adds those to the redirect URI which is obtained from `state`. However, in this case the order of the query parameters can change

## Steps to Reproduce (for bugs)

1.  send a request from the client with a request URI that contains query parameters separated with `&`

## Your Environment

- Version used: v6.1.1

**Comment by NickMeves** [comment]
What Provider + IdP are you using? We've had this bug reported once before and it ended up being an issue with the IdP.

If I recall, the state/nonce formatting our codebase is the same format Google/Okta etc have in their sample OAuth2 implementation code guides.

**Comment by qkflies** [comment]
I've noticed a similar issue, too, using the OIDC provider and Keycloak.

Some request URLs contain a hash (e.g. `/#here`), and they get stripped only when going through the authentication flow. This occurred with v6.1.1, and also the latest v7.1.2, if I recall correctly.

**Comment by JoelSpeed** [comment]
If a request contains a hash, then anything following it is referred to as the "fragment". As part of the HTTP spec, fragments are not sent as part of the request. Therefore, anything after the hash is never sent to OAuth2 Proxy.

Given it does not know what's in the hash, it can't restore it after the redirection flow.

With that said, I'm not sure that this issue is being broken by it being a fragment 🤔

**Comment by janosi** [comment]
@NickMeves I use IBM Cloud App ID as OIDC provider, and the Kubernetes Ingress controller that uses the OAuth2-Proxy via nginx sub-requests.

The request that comes has literally the query `?key=value&key2=value2` I tested it with that query in the URI. There is no hash in the URI.

The reason is really here https://github.com/oauth2-proxy/oauth2-proxy/blob/7eeaea0b3f563c7e14f213e47dfda82b40f3fca1/oauthproxy.go#L1183

At this point "key2=value2" is not part of `req.Form.Get("state")` anymore, because ParseForm() moved that part of "state" an an own entry in the map. Due to the `&` separator.

**Comment by NickMeves** [comment]
That code snippet is new in master, it isn't in v6.1.1.

But your IdP is supposed to be encoding embedded `?`, `&` if they are a value field in a querystring parameter. If I recall, IdPs that don't do that correctly on sending back the `state` parameter per the OAuth2 spec have this bug.

Other OIDC/OAuth providers don't have this bug. I just tested myself with OneLogin OIDC and it encodes the URL in the `state` param and my querystring parameters are preserved on the redirect.

**Comment by NickMeves** [comment]
If you are in the slack, this question came up with ADFS, it has the same implementation bug: https://gophers.slack.com/archives/CM2RSS25N/p1613672290052200

Which I think for ADFS, that contributor is forcing this in their PR to account for that implementation bug by ADFS for OIDC: https://github.com/oauth2-proxy/oauth2-proxy/pull/1021/files#diff-a803b5cc86a6da0f825513c80b501431ae2d42b5bbb06775a1b76dff6a8173d8R57

**Comment by NickMeves** [comment]
@JoelSpeed If this implementation bug on IdP side is a non-trivial amount:

Should we encode the redirect URL portion of the `state` (currently `nonce:url`) to better account for IdPs that suck and don't properly encoded querystring value contents?

**Comment by NickMeves** [comment]
More accurately... should we double encoded, because we are already encoding these values appropriately when we send the original `state` querystring parameter on the original authorization endpoint request that kicks off the OAuth2 flow by nature of using `params.Encode()` in our `makeLoginURL` implementation.

Per spec, we are supposed to get EXACTLY that back from the IdPs (which would avoid this bug) -- but it seems these IdPs are decoding -- then sending that back in the generated redirect to the token endpoint with the `state` without re-encoding.

**Comment by NickMeves** [comment]
Using `base64` in our `encodeState` and `decodeState` is the best guaranteed reversible encoding I can think of without having to deal with whether the underlying IdP supports url-encoding properly or not (and it will have no collisions with risky &? characters).

Downside is using that will expand the size by 33%. That would create problems for URL paths that are already close to the maximum length -- if they were the first request that redirected to SSO, the base64 encoded URL would be too large.

**Comment by janosi** [comment]
> That code snippet is new in master, it isn't in v6.1.1.

Indeed, my fault. This is how it looks like in v6.1.1
https://github.com/oauth2-proxy/oauth2-proxy/blob/e4e5580852dcc8a45cc5c552243416f7a6ae0368/oauthproxy.go#L781

**Comment by janosi** [comment]
> If you are in the slack, this question came up with ADFS, it has the same implementation bug

I am in slack, but unfortunately I am not a member of that workspace.

**Comment by NickMeves** [comment]
@janosi You should also report this bug to IBM Cloud since this is a bug on their end I think. (They aren't URL encoding the `state` parameter when they reflect it back after they URL decode it).

Not sure what good avenues we have to fix this without causing bugs for other use cases. I prefer to leave the identity provider that isn't following the spec correctly broken rather than fixing it here & potentially breaking other valid IdPs.

**Comment by janosi** [comment]
@NickMeves Yep, I see your point.
