### ISSUE TITLE
Wrong logic for setting secure cookies

### ISSUE THREAD

**Issue by rassie** [oauth2-proxy/oauth2-proxy#1190]
The option `--cookie-secure` breaks redirect URLs for HTTP sites with a HTTPS IDP. The problem is in https://github.com/oauth2-proxy/oauth2-proxy/blob/06808704a3762de73bed1cc92b077420eb93d735/oauthproxy.go#L932-L936

`--cookie-secure` is the default setting and it is used verbatim in the cookie creating routine. This will fail on HTTP sites and will also produce wrong redirection URL. 

## Expected Behavior

1. Open an `oauth2-proxy`-protected HTTP site, which uses a HTTPS IDP (e.g. local development with remote IDP).
2. Observe `http://` in the `redirect_url` query parameter
3. Login at the IDP
4. Get redirected to your HTTP site.

## Current Behavior

1. Open an `oauth2-proxy`-protected HTTP site, which uses a HTTPS IDP (e.g. local development with remote IDP).
2. Observe `https://` in the `redirect_url` query parameter
3. Login at the IDP
4. Get redirected to your HTTP site with HTTPS protocol, resulting in SSL protocol errors.

## Possible Solution
While it is possible to set or unset `--cookie-secure`, it probably shouldn't exist at all -- whether a cookie needs to be secure depends completely on the scheme of the protected URL. Whether or not `oauth2-proxy` should be deployed on HTTPS should be user's decision (in case of development machines there is not even a choice).

**Comment by NickMeves** [comment]
If you are hosting via HTTP, you should have `cookie-secure` set to false.  Otherwise, the session cookie will have the `secure` flag and browsers won't send that cookie to HTTP sites.

The history behind using the `CookieSecure` flag as a last fallback detection for redirect URL schemes is here: https://github.com/oauth2-proxy/oauth2-proxy/pull/1045

There's a thorough discussion of the security implications of this design and whether users should explicitly use the `--redirect-uri` option. FYI, that is our recommendation for security purposes.

I had actually removed it -- but I didn't realize for HTTP sites go libraries were making the scheme `//` instead of `http://`, so that PR reverted the functionality back.

**Comment by NickMeves** [comment]
Just to confirm because the term is overloaded:

Are you having issues on the OAuth redirect to the callback URL (which it calls `redirect_uri` in its querystring, usually to `oauth2/callback`)? This logic is in `getOAuthRedirectURI`

Or having issues on the final app redirect after the full SSO flow is done? This logic is in `getAppRedirect`.

**Comment by rassie** [comment]
I was having problems with the `redirect_uri`, which is probably fixed by #1045, sorry, my fault for not checking the newest version (which I haven't done since the alpha config now expects to contain providers' info, while I'm only using header injection).

However, I would still argue that secure cookies should be dynamic depending on the site: if I use a relative `--redirect-url`, I would expect the setup to work not depending on whether I'm calling `https://app.my.loadbalancer.com` or `http://app01.internal.network:8080` (e.g. for testing and isolating problems). I'm off reading #1045 for now, maybe there is a counter-argument there for me :)

**Comment by NickMeves** [comment]
> I was having problems with the `redirect_uri`, which is probably fixed by #1045, sorry, my fault for not checking the newest version (which I haven't done since the alpha config now expects to contain providers' info, while I'm only using header injection).
> 
> However, I would still argue that secure cookies should be dynamic depending on the site: if I use a relative `--redirect-url`, I would expect the setup to work not depending on whether I'm calling `https://app.my.loadbalancer.com` or `http://app01.internal.network:8080` (e.g. for testing and isolating problems). I'm off reading #1045 for now, maybe there is a counter-argument there for me :)

Proxies throw a big wrench into things. We can't 100% know whether they are in the chain or not, terminating TLS or not. Then we can't know whether to trust X-Forwared-For, X-Forwarded-Host, X-Forwarded-Proto or not or default to Golang http request details (which will be wrong if fronted by a proxy).

And then trying to be smart and auto-detect any of this puts the system at a huge risk for malicious actors spoofing headers.

Hence we lean toward explicit settings of security related toggles.
