### ISSUE TITLE
TLS support for Redis 

### ISSUE THREAD

**Issue by parth30** [oauth2-proxy/oauth2-proxy#1221]
We are trying to connect to redis with TLS with oauth2-proxy 7.1.3 and it does not seem to work.

## Expected Behavior

proxy should be able to communicate to Redis with TLS without the proxy validating the server certs . 

## Current Behavior

If we use the flag --redis-insecure-skip-tls-verify  then there is a error thrown -- getting panic: runtime error: invalid memory address or nil pointer dereference from go . 

## Steps to Reproduce (for bugs)

1.  Spin up a pod with with oauth2proxy 7.1.3 by passing a option --redis-insecure-skip-tls-verify =true , you will see an error on startup . 

Any other step/suggestion to connect to TLS enabled redis is also great !

- Version used: 7.1.3

**Comment by NickMeves** [comment]
Did this work in previous versions?

Redis TLS is traditionally an addon via a TLS proxy right? Not native in Redis (I might be misremembering, been a while since I've used Redis heavily).

If I recall, the Redis session store implementation just wrapped around the underlying `go-redis` client support for TLS, I don't think we bolted too much onto it.

So hopefully if something is broken with `panic`, it's a quick fix 🤞
