### ISSUE TITLE
Github unauthorized when the user is clearly authorized

### ISSUE THREAD

**Issue by chaodaiG** [oauth2-proxy/oauth2-proxy#1252]
## Expected Behavior

Authorized user in configured github org and group can be authorized by oauth2-proxy

## Current Behavior

A few users get unauthorized error

## Steps to Reproduce (for bugs)

Oauth2-proxy is deployed in a kubernetes cluster, the configuration is https://github.com/GoogleCloudPlatform/oss-test-infra/blob/8dc1700495f08720c67f2fb243b34667af923dec/prow/oss/cluster/deck_private_deployment.yaml#L98.

Most of the users are successfully authorized, but a few users with the same github org and group memberships get unauthorized error.

The errors from the container:

```
<hidden-ip-address> - a0d2883e-47bf-4241-8f24-ea50cac4c6b4 - - [2021/06/23 20:26:33] [AuthFailure] Invalid authentication via OAuth2: unauthorized
```

```
<hidden-ip-address> - a0d2883e-47bf-4241-8f24-ea50cac4c6b4 - - [2021/06/23 20:26:32] <hidden-host-address> GET - "/oauth2/callback?code=<hidden-code>%3A%2F" HTTP/1.1 <browser-related-info>
```

We have tried clearing caches, revoke github oauth2 authorization to the github app, none of them worked. The logs above don't seem to provide much useful info either. Is there anything else we can do to debug this?

**Comment by chaodaiG** [comment]
Found this out by ourselves. For anyone who ran into this again, the root cause was that the user didn't have email verified on github. Just hope that the log can be more descriptive than this

**Comment by cjwagner** [comment]
The root cause of this appears to have been that the user did not have a verified primary email registered with their GitHub account.
This causes the email to be empty:
https://github.com/oauth2-proxy/oauth2-proxy/blob/ac188b129fcb6a0c9df6adbb88b7a90660e68423/providers/github.go#L436-L443
Which later causes validation to fail even if all domains are allowed via `--email-domain=*`:
https://github.com/oauth2-proxy/oauth2-proxy/blob/42475c28f7f235c08777a24027fe8ec170763482/validator.go#L80-L96

**Comment by cpflaume** [comment]
Just ran into the same issue, thanks for the hint @chaodaiG
