### ISSUE TITLE
Integration with Firebase

### ISSUE THREAD

**Issue by tlawrie** [oauth2-proxy/oauth2-proxy#1316]
Has anyone integrated Auth Proxy with Firebase, similar to what happens with Keycloak / Dex? 

## Expected Behavior

The auth proxy would go to Firebase to validate the user object. I am not even sure if this is possible, but wanted to see if it had previously been looked at or investigated?

**Comment by tlawrie** [comment]
Hey @JoelSpeed do you know if this is something that has ever been looked at or how hard it would be?

**Comment by JoelSpeed** [comment]
I don't think anyone has looked at this before no. Is Firebase just another provider in this situation or is it more of an Authz style plugin?

**Comment by tlawrie** [comment]
The reason i likened it to Dex was that Firebase handles going out to all the different providers

![image](https://user-images.githubusercontent.com/16438811/132271136-57aa3a3d-befe-4ed2-82b4-a57e8cc8c8b4.png)

So somehow I am thinking you would have Auth Proxy integrated in front of microservices with NGINX the same way it can be now, and it goes out to Firebase.

However I have no idea about the technical details of how that could be achieved.

**Comment by JoelSpeed** [comment]
As far as I'm aware, firebase doesn't have the ability to itself be an identity provider, so in this case, it wouldn't work with OAuth2 Proxy no. The reason Dex does work is because it is designed itself to be an identity provider, proxying information from the upstream identity providers.

If there's a way to use firebase as an OIDC provider (a quick google didn't reveal anything), then it might work, but I suspect not

**Comment by tlawrie** [comment]
Thanks Joel, I agree with your summation. This can be closed now.
