### ISSUE TITLE
oauth2-proxy drops the HTTP method and gets 405 http error

### ISSUE THREAD

**Issue by einavdaniel** [oauth2-proxy/oauth2-proxy#1349]
## General description
oauth2-proxy with keycloak as a provider drops the HTTP method and changes it to GET after redirect, resulting in a "HTTP error 405 method is not allowed"

## Expected Behavior
Callback should preserved as the original HTTP method

## Current Behavior
When invoking http request after session is idle for a while it returns redirect with GET method instead of the original POST/PUT/DELETE

## Steps to Reproduce (for bugs)
Using the following configuration, after an idle time of about 5 minutes, the next POST call is executed as a GET request:
[oauth2-proxy-config.txt](https://github.com/oauth2-proxy/oauth2-proxy/files/7093968/oauth2-proxy-config.txt)

## Context
Getting this 405 error will force the user to refresh the page/relog since he wont receive data from the server

## Environment
Kuberntes setup with Nginx-ingress controller, oauth2-proxy, keycloak as OIDC provider
- Version used:
keycloak - v14.0.0
oauth2-proxy - v7.1.3
kubernetes - v1.20.0 (K3S and GKE)

## Example
Initiated POST request to http://my-server/api/v1/setup/test_connection after session cookie expired:

1: redirected 302
Request URL: http://my-server/api/v1/setup/test_connection
Location: http://my-server/oauth2/start?rd=/api/v1/setup/test_connection

2: redirected 302
Request URL: http://my-server/oauth2/start?rd=/api/v1/setup/test_connection
Location: http://my-server/auth/realms/my-realm/protocol/openid-connect/auth?approval_prompt=force&client_id=nginx&redirect_uri=http://my-server/oauth2/callback&response_type=code&scope=openid+profile+email&state=-CShX4nyqJeRD7_2wfBH-nsCk5Q-FHwikQkjW7m-Qa8%3A/api/v1/setup/test_connection

3: redirected 302
Request URL: http://my-server/auth/realms/my-realm/protocol/openid-connect/auth?approval_prompt=force&client_id=nginx&redirect_uri=http://my-server/oauth2/callback&response_type=code&scope=openid+profile+email&state=-CShX4nyqJeRD7_2wfBH-nsCk5Q-FHwikQkjW7m-Qa8%3A/api/v1/setup/test_connection
Location: http://my-server/oauth2/callback?state=-CShX4nyqJeRD7_2wfBH-nsCk5Q-FHwikQkjW7m-Qa8%3A/api/v1/setup/test_connection&session_state=cc82b0ad-bbe1-4b32-83ba-74499708b826&code=fb0cc4c9-e21b-437f-badb-d2314d0dd24a.cc82b0ad-bbe1-4b32-83ba-74499708b826.b5c51dae-526f-48c3-adfb-eb50705b94ed

4: redirected 302
Request URL: http://my-server/oauth2/callback?state=-CShX4nyqJeRD7_2wfBH-nsCk5Q-FHwikQkjW7m-Qa8%3A/api/v1/setup/test_connection&session_state=cc82b0ad-bbe1-4b32-83ba-74499708b826&code=fb0cc4c9-e21b-437f-badb-d2314d0dd24a.cc82b0ad-bbe1-4b32-83ba-74499708b826.b5c51dae-526f-48c3-adfb-eb50705b94ed
Location: /api/v1/setup/test_connection

5: error 405 method is not allowed
Request URL: http://my-server/api/v1/setup/test_connection
GET instead of POST

**Comment by JoelSpeed** [comment]
IIRC if we were to change from a 302 to a 308(?) we could preserve the request method, but, since we don't control the redirects being sent by the IDP, I think their 302s would then drop the request method.

I don't know if there's a way we can send the request method back as part of the final redirect after the `/callback`, might be something to look into 🤔

**Comment by jacobsin** [comment]
> IIRC if we were to change from a 302 to a 308(?) we could preserve the request method, but, since we don't control the redirects being sent by the IDP, I think their 302s would then drop the request method.
> 
> I don't know if there's a way we can send the request method back as part of the final redirect after the `/callback`, might be something to look into 🤔

Think it's 307

**Comment by jacobsin** [comment]
Related to #1289?

**Comment by redboxstudio** [comment]
and so I moved on, replacing 302 with 307 to fix 405 for non-get requests, I ran into error 400 for post requests keycloak returns me the error "not present or present multiple times in the HTTP request parameters"
its here 
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/003665e3-d321-4c58-80e0-53b329df0091)
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/ed284b36-7d9a-4080-a705-2ea9da9a1693)
I tried to modify the sending of the request for the post type, but so far it is to no avail, in the logs I do not see the body with the parameters that I am creating
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/34ecd2c6-9634-4005-9be2-68285098af9c)
Maybe someone understands more about golang and can suggest how to correctly implement this scheme so that you can work with both post and get requests?
