### ISSUE TITLE
What is the purpose of setting the X-Scheme header?

### ISSUE THREAD

**Issue by andrewdbate** [oauth2-proxy/oauth2-proxy#1362]
The example Nginx configuration in the docs [here](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#configuring-for-use-with-the-nginx-auth_request-directive) sets the `X-Scheme` header.

`X-Scheme` is also used in the Nginx config snippet given on docs page [here](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/tls).

`X-Scheme` is not mentioned anywhere else in the 7.1.x docs.

It seems that this header is not used anywhere in the source code (grepping for `X-Scheme` or similar returns nothing). Searching through all issues (open and closed) for `X-Scheme` shows that lots of people have it set in their Nginx config, but no one has previously asked why it is set.

I found another Nginx configuration [here](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/contrib/local-environment/nginx.conf) but that does not set `X-Scheme`.

I also searched through the commit history in case `X-Scheme` had been used in an old version of OAuth2 Proxy, but couldn't find anything.

So what is `X-Scheme` used for? Can we just get rid of it from the example Nginx configs in the docs?

**Comment by JoelSpeed** [comment]
I don't recall anywhere that uses it explicitly, the only thing I can think of where it might be used is in the HTTPS redirection. I think have something there that looks for a forwarded scheme header to determine what the upstream request scheme was.

It could be that it's just good practice to recommend setting the scheme so that downstream servers can make decisions based on the header
