### ISSUE TITLE
Feature Request - Provide scratch based image

### ISSUE THREAD

**Issue by mattharrigan** [oauth2-proxy/oauth2-proxy#1372]
Please provide a scratch based image. I believe that is often considered a security best practice as it dramatically reduces the surface area for attacks and vulnerabilities. Also, v7.1.2-amd64 currently has CVE-2021-36159. Fixing that specific issue is also appreciated, but truly solving it by offering a scratch image would be much preferred.

To be more specific, changing https://github.com/oauth2-proxy/oauth2-proxy/blob/master/Dockerfile#L24 to `FROM scratch` would just about do it.

Thank you

**Comment by JoelSpeed** [comment]
IIRC we looked into this before and there was one slight issue with it, being that because the proxy makes HTTPS calls, it needs to have the system root certificates in the container. When you have a scratch container, we don't have any, so any HTTPS call the proxy makes would end up failing as an untrusted certificate.

There are a couple of options for how to get around this:
* Try to include a set of root certificates - but then is it really a scratch container? And where would we copy them from? Not from the build system I'd hope
* Don't provide any root certificates - we would have to document that users need to inject these themselves, probably not ideal and will definitely lead to people opening issues asking why the root cetificates are broken, increasing our support burden
* Something else I haven't thought of this morning?

Do you have any thoughts about how best we might resolve this particular issue?

**Comment by mattharrigan** [comment]
I recommend providing a scratch based image in addition to the one you already provide. The docs for the scratch image should say that the user needs to inject their own ca cert. The existing image is not affected. I think that mostly avoids people opening issues for root certificates being broken. Quite a few apps provide multiple different images for different specific use cases. For my use case, I need to provide a custom ca cert from my company regardless, and will probably just mount it to one of the golang default locations using k8s configmaps.

**Comment by JoelSpeed** [comment]
> I recommend providing a scratch based image in addition to the one you already provide.

Yep, totally agree with this.

> The docs for the scratch image should say that the user needs to inject their own ca cert. 

My suspicion is that people won't read the docs, I don't think we have docs right now for our existing images, so where could we put these to make it obvious?

**Comment by omBratteng** [comment]
Alternatively [`distroless`](https://github.com/GoogleContainerTools/distroless) images
> "Distroless" images contain only your application and its runtime dependencies. They do not contain package managers, shells or any other programs you would expect to find in a standard Linux distribution.

**Comment by JoelSpeed** [comment]
Would a distroless image have the same issue of not having root certificates? I think what we do today is copy them from the builder image, I could see us leaning towards using that as an approach, I don't mind setting up new builds for a scratch or distroless image.

Which of the two is preferred, what are the pros/cons of distroless vs scratch?

**Comment by omBratteng** [comment]
iirc the distroless does have certificates installed. I can do a PoC tomorrow and see if distroless works

**Comment by omBratteng** [comment]
I have done a PoC here https://github.com/oauth2-proxy/oauth2-proxy/pull/1478
Using distroless static-debian11 with non-root user.
It does not have a shell, if you want a shell, you can use the `debug-nonroot` tag to get a busybox shell

Only tested with OIDC against Azure AD

**Comment by omBratteng** [comment]
If you use the `debug-nonroot`, you can verify that there is root certificates installed.
