### ISSUE TITLE
Use Redis lock when refreshing session

### ISSUE THREAD

**Issue by Bibob7** [oauth2-proxy/oauth2-proxy#1384]
## Description
Based on redis lock feature from #1063, I wanted to integrate the locking of sessions when refreshing them.

## Motivation and Context
If parallel requests hitting the oauth2-proxy with an expired session, oauth2-proxy will perform multiple requests to the token endpoint to refresh it.
Because of refresh token rotation, a refresh token can only be used once, so that the second request to the token endpoint will fail.
In this case, it is possible to repeat the retrieval of the session from the persistent storage, as the successful request must have already updated the session in the persistent storage.

**Comment by JoelSpeed** [comment]
Hey @Bibob7 I was under the impression that your previous work had resolved the issues here. As I understood it, when trying to refresh, first we would acquire the lock, do the refresh, save the session. When a second refresh got blocked, it would re-retrieve the session before then checking whether it actually needed to refresh. Is that not happening currently? Can you explain the current behaviour and why this needs looking at again?

**Comment by Bibob7** [comment]
With my last work I just added the redos lock implementation on the Session state, but it was not yet used, because it was necessary to refactor the refresh implementation before. This was done here: https://github.com/oauth2-proxy/oauth2-proxy/pull/1086

**Comment by lollo25** [comment]
@JoelSpeed do we have of the release of this feature? In my experience this would be super useful to allow security without comprimise the user experience.

**Comment by piyushk** [comment]
I believe we're getting impacted by this issue as well -- we have parallel backgroundrequests hitting 2 oauth2-proxy replicas with a redis store.

What would be oauth2-proxy's current behavior be if 1 our of 2 parallel requests fail since only a single request can refresh the token (refresh tokens are revoked after first use)? Would the failed request would be redirected to the provider? What happens to the current session/cookies? We're trying to see if this issue might explain some other hard-to-replicate user behavior, such as CSRF token mismatch issues (https://github.com/oauth2-proxy/oauth2-proxy/issues/817). Thanks!

**Comment by piyushk** [comment]
After looking at the logs I think we were able to establish that this issue was indeed leading to hard-to-replicate user experience behavior when the application uses background/polling requests and refresh token revocation is enabled in the provider. 

Here's our best estimate of what's happening in case someone finds it useful:

1. 2 parallel background/polling requests hit oauth2-proxy right after the cookie refresh interval.
2. oauth2-proxy hits the provider with 2 requests to refresh the token
3. The provider (Keycloak in our case) refreshes the token for the first request, but issues a 400 for the second one.
    1.  Keycloak also removes the client from the keycloak session for incorrect usage. There might be a way to disable this feature in keycloak, but it doesn't seem like a half bad thing to keep in.
4. Oauth2-proxy logs the error for the failed request, but the session was correctly refreshed so future requests work as expected since the session is valid.
5. After the next cookie refresh interval, oauth2-proxy again tries to exchange the refresh token from keycloak (parallel requests don't matter here). It received a 400. This time oauth2-proxy marks it session as expired and removed it. I believe the cookie is unset.
6. Since multiple background requests are still ongoing, each request gets a 302 redirect to the provider
    1. Parallel requests start overriding the `csrf` cookie repeatedly. A user generally has multiple tabs open.
    2. Nit: It doesn't matter much for these background requests, but they fail because they fail the CORS handshake with the provider.
7. The user notices that parts of the application aren't opening and refreshes the current tab. The user gets logged into keycloak automatically, a new keycloak session is established, and the user gets redirected back to oauth2-proxy. Because background requests in a second tab have obliterated the `csrf` cookie, the user experiences a 403 as described in https://github.com/oauth2-proxy/oauth2-proxy/issues/817.

We'll try and mitigate this issue by disabling refresh token revocation in keycloak for the time being.

### Potential update to the proposal 

I think to prevent 3i, oauth2-proxy must send only 1 refresh request to the provider, even in the case of parallel requests. I think this is a minor difference from @Bibob7's original proposal - requests should re-check the session again after acquiring the lock and before refreshing it.
1. Determine if session needs to be refreshed. This will prevent unnecessarily locking the session.
2. If yes, then acquire redis lock.
    1. Determine again if session needs to be refreshed. Some other parallel request may have updated the session already.
    2. If yes, then refresh the session
3. Release the redis lock

@Bibob7 @JoelSpeed Would the above work?

**Comment by JoelSpeed** [comment]
@piyushk Have you seen my PR #1468, I believe I'm on the same page as you here and have included that already within the implementation, any feedback on that PR would be appreciated

**Comment by piyushk** [comment]
@JoelSpeed Thanks for the pointer. I saw #1385, but missed the continuation in #1468. From my reading of the code, it covers the case above. There's a little bit of work we need to do to allow different keycloak settings in QA vs production. We might not be able to test it pre-merge, but I'll follow up there once we confirm that it resolves the issue. Thanks a lot for your work!
