### ISSUE TITLE
Recommendations for running oauth2-proxy with session-storage-type=redis

### ISSUE THREAD

**Issue by joliebig** [oauth2-proxy/oauth2-proxy#1417]
## Expected Behavior

I'm running oauth2-proxy (V7.1.3) together with redis (6-alpine) in a Kubernetes environment. My setup involves:
1. oauth2-proxy runs in a pod with redis as sidecar and is used for centralized authentification and central group-based authorization.
2. redis is configured with resource limits (cpu: 100m and memory 200Mi).
3. We are using a company based Cloud-IDP with 30min access-token validatity and 12h refresh-token validity.
4. Due to the size of the Cookie-based storage (around 4KB) we switched to redis' session storage.
5. We are expecting up to 2000 Users.

## Current Behavior

The setup works, but I'm wondering if someone could share experiences/recommendations. Specifically, redis is not configured with persistence, so on pod restarts there are authentication errors. _oauth2_proxy_csrf token appears additionally in my browser. A page reload fixes that, but leads to application-specific problems. I'm aware that a specific setup is out of scope with respect to the documentation (see https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/session_storage). However, since session-storage-type=redis seems to be the favourable storage backend, some additional information on redis configuration may be helpful.

## Your Environment

- Version used: V7.1.3

**Comment by NickMeves** [comment]
You definitely need your session datastore to be persistent -- otherwise I recommend switching back to cookies, and if they are large, using session-cookie-minimal (do we still have that? Or did I remove it after I implemented session lz4 compression 😅 )

As for Redis, I recommend a StatefulSet instead of a Deployment so it can persist and running it in AOF persistence mode (or AOF + RDB): https://redis.io/topics/persistence

**Comment by joliebig** [comment]
@NickMeves: Thanks for the input. I'll look into that.
