### ISSUE TITLE
Support * for the arg --whitelist-domain to allow any domain, any ip and any port.

### ISSUE THREAD

**Issue by SpecialYang** [oauth2-proxy/oauth2-proxy#1460]
Currently, the arg `--whitelist-domain` only support domain and domain with any port. 
However, in our case, we have lots of domains can be redirected by oauth2 proxy and these domains may changes frequently. In addition, in the test case, we hope to redirect ip to test directly. 
So, should we support  * for the arg `--whitelist-domain` to allow any domain, any ip and any port?

**Comment by SpecialYang** [comment]
@JoelSpeed  Sorry for ping. How do you think this enhancement?

**Comment by JoelSpeed** [comment]
I don't think we should do this. This would open it up so that anyone could login and then redirect to any endpoint. This would expose your users to phishing attacks very easily, all an attacked has to do is send them a crafted URL, they open it, login and they could end up on a site that looks like yours, but isn't and then enter sensitive information. 

Disabling certain protections within the OAuth2 spec is not advised and allowing that within our product might open up our users to insecure situations, so I'd rather we didn't on this one.
