### ISSUE TITLE
Why is id_token used instead of access token for upstream calls?

### ISSUE THREAD

**Issue by braunsonm** [oauth2-proxy/oauth2-proxy#1548]
Just a question, I noticed in the oidc provider that the ID token is passed instead of the access token to upstream calls after being authenticated: https://github.com/oauth2-proxy/oauth2-proxy/blob/master/providers/oidc.go#L225

`Authorization: Bearer <ID Token>`
(Notice how ID token is set for ID token and access token in the session, the access token is just dropped)

It was my understanding in the spec that access token should be used as the "Bearer" token. This actually is better in my experience on Azure because they sometimes return Opaque tokens and our apps would like to get some user information from the claims.
But I was wondering if any of the maintainers could answer why this is, or what the motivation was? Perhaps I am misunderstanding the specs intent and the usual advice I see.

Happy to take this discussion offline if necessary but figured it would be good to get a response for the community and others that see this.

**Comment by JoelSpeed** [comment]
The code you've linked to is for the case when a user sends an ID Token within the header as a request (this is common in OIDC compliant applications). When a session is created, we actually do store the Access Token and ID Tokens, and, if you use `--pass-access-token` and `set-xauthrequest` you can get the Access Token in a header as well.

The `Authorization: Bearer ...` addition was probably a mistake, the long term intention is to allow users to build their own headers, but that will come with structured configuration

**Comment by braunsonm** [comment]
Thank you @JoelSpeed 

I'm specifically referencing articles such as: https://auth0.com/blog/id-token-access-token-what-is-the-difference/

> What Is an ID Token NOT Suitable For?
One of the most common mistakes developers make with an ID token is using it to call an API.

It seems articles tend to talk about how this is insecure. So I'm curious why the ID Token is passed in the `Authorization` header. Or if there's something I'm missing in regards to the spec. I haven't found anything that says this should be used as the Authorization header.

**Comment by JoelSpeed** [comment]
This article talks about a lot of different scenarios, and they are right, there are possibilities to compromise your security if an ID token is leaked. However it does also mention that in some first-part scenarios ID Tokens are valid for calling APIs.

The ID Token can be thought of as a passport right? It proves who you are, it's up to the application that accepts the token (or the border control in my analogy) to check the person has the right to use the application, eg by having separate RBAC (or a visa for the analogy purposes).

The feature was originally implemented because a lot of Kubernetes and cloud native applications use ID Tokens to identify users, and then delegate authorization to some other service

**Comment by PSanetra** [comment]
@JoelSpeed I agree with the original assumption of @braunsonm that the `Authorization` header should actually contain the access token, not the ID token, but for my use case the `x-auth-request-access-token` works as well :+1: 

I think the ID token contains usually only informational content about a user and should not be used for authorization purposed.
