### ISSUE TITLE
Question about redirect-url param

### ISSUE THREAD

**Issue by SpecialYang** [oauth2-proxy/oauth2-proxy#1622]
There is a param called redirect-url can be use to define the third-party authority server callback. If I set this param as test.com/abc, the oauth proxy still use `/oauth2/callback` in exchanging token phase. I am confused about the function of this  redirect-url param. If i set this param, why oauth proxy doesn't use this path to handle callback?

The relevant code is following.
Set custom callback.
```
callbackRedirect := p.getOAuthRedirectURI(req)
	loginURL := p.provider.GetLoginURL(
		callbackRedirect,
		encodeState(csrf.HashOAuthState(), appRedirect),
		csrf.HashOIDCNonce(),
		extraParams,
	)
```

Handle callback.
```
s.Path(oauthCallbackPath).HandlerFunc(p.OAuthCallback)
```

**Comment by JoelSpeed** [comment]
How are you setting the redirect URL? Is it via a command line flag? 

Looking at the code it should be using whatever you specify unless there's a bug somewhere.

That said, why are you setting the redirect URL to a different server? OAuth2 proxy needs to handle the callback so that it can set the session up and perform the token exchange.
The only reason you need to set redirect URL typically is if there is some rewrite logic in front of OAuth2 Proxy

**Comment by SpecialYang** [comment]
If we explicitly set redirect-url and don't have rewrite logic in front of OAuth2 Proxy, the path of redirect-url must be `/oauth2/callback`. I think we should highlight this note in the document.
