### ISSUE TITLE
Documentation Flaw - Configuration via Environment Variables

### ISSUE THREAD

**Issue by newcron** [oauth2-proxy/oauth2-proxy#1631]
First of all: thanks for oauth2_proxy. It's a great tool and i have been using it since several years in many projects and am really happy with it. 

i just found a significant flaw in the documentation in regards to configuration of oauth2_proxy with environment variables. The documentation states that settings that for settings that can appear more than once, the env variable should be pluralizsed, so that 
`--upstream` becomes `OAUTH2_PROXY_UPSTREAMS`. 

While I understand the behaviour, it's not quite obvious to the busy reader and there's a high chance this information is missed - leading to serious confusion and time loss when trying to setup oauth proxy and configuring the upstream via environment variables. (I just spent two hours trying to understand why `OAUTH2_PROXY_UPSTREAM` is not working) 

## Current Behavior

If you don't pay close attention to the docs (specifically the last paragraph in the environment variable section) you just miss the pluralization info. 

## Possible Solution

Would be great if the table with the config options would also contain the names of the environment variables that are used. That way you could avoid any confusion. 

## Context

setting up oauth2 proxy in kubernetes using environment variables for configuration

**Comment by JoelSpeed** [comment]
I had been thinking about how to solve this before, it's not easy to automate so we need to manually make a change to the docs and make sure we get it right.

Because of the way the markdown is written, I'm not sure what the best way to do this would be, perhaps we can use tabs within the page to add both the config file option and the environment variables, or would it be too clunky having to switch between the tabs?
