### ISSUE TITLE
whitelist-domain redirect to http. Navigation to http: URLs allowed in Login

### ISSUE THREAD

**Issue by matzegebbe** [oauth2-proxy/oauth2-proxy#1673]
whitelist-domain: redirect to http is possible.
There should be a flag or the possibility to allow only HTTPS redirects. Currently redirects also work on the http protocol.

https://auth.domain.com/oauth2/sign_in?rd=http://domain.com/page/

```
- --whitelist-domain=.domain.com
```

## Expected Behavior

Although of course a server port _domain.com:443_ is supported it would be nicer if we can basically exclude http redirects

## Current Behavior

Redirects to http is possible

## Possible Solution

```
--allow-http-redirects=false
```

The same logic for checking the redirect domain (whitelist) also checks the protocol could be implemented 

## Steps to Reproduce (for bugs)

call `/oauth2/sign_in?rd=http://domain.com/` with a http redirect

## Context

We did a penetration test on our login flow and application and this was a finding:

**Navigation to http: URLs allowed in Login (Info)**

## Your Environment

- Version used: 7.3.0 with OIDC

**Comment by JoelSpeed** [comment]
Interesting, hadn't really thought about this before as normally, it is up to the person configuring the application to set what the redirect is, so I would expect whoever is configuring, say nginx, to set up a redirect query string with https in there by default. Equally, assuming you've allowed the domain, you should have control over the http server for it, so could set up an HTTP -> HTTPS redirect (or even HSTS) as well.

Does setting :443 on the end force this to work? 

I'm wondering if we want to add a scheme section to the redirect validation, eg `https:<domain>:<port>`, this would match some other URL type schemes I've seen (Eg K8s service proxying) and would avoid the need for an extra flag, though would need some parsing magic on our side :thinking:

**Comment by matzegebbe** [comment]
hey! thanks for the quick response.

Here I share the content of our pentest report as promised:

*In the login processing, the URL specified in the "rd" parameter is used as the redirect
destination. Here, the URL employed for the redirect destination is restricted to URL
belonging to .domain.net or .domain.com domains.
However, it was discovered that the http: URL can be used as the destination. This gives
an attacker room to attempt Man-in-the-Middle attacks even if the login process is
started via https: URL. An adversary with the ability to eavesdrop on the network traffic
might use this weakness to read or even rewrite the response.
The issue can be reproduced via the following URL. After entering credentials, a 302
redirect response will be created for http: URL .

I also think the attack vector is very small and it is also only an infofinding. Nevertheless I think supporting this functionality makes sense. 

Adding port 443 then also requires the port in the redirect url - not so practical.

**Comment by AljoschaP** [comment]
> Interesting, hadn't really thought about this before as normally, it is up to the person configuring the application to set what the redirect is, so I would expect whoever is configuring, say nginx, to set up a redirect query string with https in there by default. Equally, assuming you've allowed the domain, you should have control over the http server for it, so could set up an HTTP -> HTTPS redirect (or even HSTS) as well.
> 
> Does setting :443 on the end force this to work?
> 
> I'm wondering if we want to add a scheme section to the redirect validation, eg `https:<domain>:<port>`, this would match some other URL type schemes I've seen (Eg K8s service proxying) and would avoid the need for an extra flag, though would need some parsing magic on our side thinking

From a user perspective, adding a scheme section sounds like a very intuitive and flexible approach. :+1: Is a simple comparison sufficient or do you think we need a more complex approach? @JoelSpeed 

https://github.com/oauth2-proxy/oauth2-proxy/blob/743c344fdc463461c3f4a3f8d975c177f8a3c07f/pkg/app/redirect/validator.go#L49

**Comment by JoelSpeed** [comment]
I think extending the redirect validation is the right place to be looking. We will need to somehow parse the scheme from the front of the string, perhaps in fact we want legitimate `https://` prefix support 🤔 

Anyone got time to work on a PR for this?

**Comment by AljoschaP** [comment]
Sorry for the delay. I'm a little bit busy right now. I have started working on it but I think we need to clarify what should be valid/invalid, because some combinations are very tricky. I created a short overview to show what I mean:

| Line | URL      | Description/Question | 
| ----------- | ----------- | ----------- |
| 1 | https://\*:\*      | HTTPS with any domain and any port. Normal use case.       |
| 2 | https://example.com:*   | HTTPS with specific domain and any port. Normal use case. |
| 3 | https://example.com:443   | HTTPS with specific domain and specific port. Normal use case.|
| 4 | example.com:443   | Does it mean any scheme or some sort of default scheme? |
| 5 | example.com:\*   | And now? |
| 6 | https://example.com  | HTTPS with specific domain and default port. What should we do with schemes where we can't guess the default port?|
| 7 | \*://\*:\*   | Any protocol with any domain and any port. Allow all.|
| 8 | \*://example.com:*   | Any protocol with specific domain and any port        |
| 9 | \*://example.com:443   | Any protocol with specific domain and specific port        |
| 10 | \*:\*:\*   | Any protocol with any domain and any port. It gets very tricky       |
| 11 | \*:\*   | Any protocol with any domain and default port \|\| Any domain with any port        |
| 12 | \*   | Any protocol with any domain and any port. Allow all        |

I'm afraid that especially the combinations with "*" and defaults/blanks will get very tricky. What do you think?

**Comment by JoelSpeed** [comment]
This makes me think that perhaps we shouldn't be overloading the string value and instead should look at moving this configuration over to the structured alpha configuration

The alternative is to say that you can't wildcard the scheme, so options 7 onwards wouldn't have a protocol section

**Comment by AljoschaP** [comment]
Honestly, my understanding of the oauth2-proxy is not deep enough to estimate the impact of choosing one over the other. Especially, because I suspect that it will be a breaking change in any case. Do you have any preferences @matzegebbe?

**Comment by matzegebbe** [comment]
--whitelist-domain | string \| list | allowed domains for redirection after authentication. Prefix domain with a . or a *. to allow subdomains (e.g. .example.com, *.example.com)
-- | -- | --

I would like to see

```
--whitelist-domain=https://*.domain.com
--whitelist-domain=*.domain.com (to be backward compatible)
--whitelist-domain=.domain.com (to be backward compatible)
```

basically I think `can't wildcard the scheme` is suitable with the possibility of a wildcard as prefix

2,5,10,11 I don't see as so useful currently

**Comment by matzegebbe** [comment]
I would like to invest some time here. I hope I can find the time in December.
