### ISSUE TITLE
oauth2-proxy does not respect --skip-auth-route 

### ISSUE THREAD

**Issue by AntonAleksandrov13** [oauth2-proxy/oauth2-proxy#1807]
## Expected Behavior

When adding `--skip-auth-route="GET=^\\/app\\/trigger\\/sns\\/.*"` routes like`/app/trigger/sns/foo/bar/something` should be allowed to bypass authentication.
## Current Behavior

The route is recognized by oauth2-proxy which is indicated by the following line in logs:
`[2022/10/03 08:17:06] [oauthproxy.go:408] Skipping auth - Method: GET | Path: ^\\/app\\/trigger\\/sns\\/.*`

However when I try to curl path `https://host/app/trigger/sns/foo/bar/something` I receive 401.

## Context

Based on [a similar issue](https://github.com/oauth2-proxy/oauth2-proxy/issues/1498#issuecomment-1008360459) I have tested my regexp in [Go Playground ](https://go.dev/play/p/FyYOn5UZ0Ro)

## Your Environment
EKS v1.21.14-eks-18ef993

- Version used: v7.3.1

**Comment by t-katsumura** [comment]
@AntonAleksandrov13 
Hi!
I checked this issue and that worked well for me.
oauth2-proxy v7.3.0 is used (I guess your v7.3.1 is a typo because v7.3.1 has not been released yet.)

I configured O2P like this in configuration file

```
skip_auth_routes = [
    "GET=^\\/app\\/trigger\\/sns\\/.*"
]
```

it showed the following log line 

`[2022/10/04 18:30:41] [oauthproxy.go:463] Skipping auth - Method: GET | Path: ^\/app\/trigger\/sns\/.*`

and `curl http://host:port/app/trigger/sns/foo/bar/something` worked well as follows (200 OK in logs)

`172.29.0.1:57334 - - [2022/10/04 18:58:29] oauth2proxy.localhost.com:4180 GET / "/app/trigger/sns/foo/bar/something" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" 200 839 0.006`

But, when I configured like this (using single quote)

```
skip_auth_routes = [
    'GET=^\\/app\\/trigger\\/sns\\/.*'
]
```

it showed the following log line 

`[2022/10/04 18:42:09] [oauthproxy.go:463] Skipping auth - Method: GET | Path: ^\\/app\\/trigger\\/sns\\/.*`

and `curl http://host:port/app/trigger/sns/foo/bar/something` did not work as follows (401 error in logs)  

`172.29.0.1:49882 - - [2022/10/04 18:43:12] oauth2proxy.localhost.com:4180 GET - "/app/trigger/sns/foo/bar/something" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" 401 2 0.000`

Your problem might be caused by the same problem.
It helps us if you can upload your configuration file or logs.

**Comment by AntonAleksandrov13** [comment]
Yeah, I have found a miss config in path later that day. Sorry for disturb you!
