### ISSUE TITLE
Provider client configuration for mTLS workloads

### ISSUE THREAD

**Issue by ethanchowell** [oauth2-proxy/oauth2-proxy#1837]
## Expected Behavior

I can provide a configuration for the provider client, similarly to the ca certs, pointing to PEM certificates and keys which are used for mTLS workloads.

## Current Behavior

I'm not able to provide a certificate and key to the provider client, leading to errors like `tls: client didn't provide a certificate`

## Possible Solution

Add config fields to the provider config pointing to certificates and keys.

## Context

I have a Keycloak instance running behind Istio, with ingress configured for mTLS. My oauth2-proxy instance is pointed at the VirtualService for Keycloak. With no client certificates provided, the TLS handshake fails.

- Version used: oauth2-proxy:v7.3.0

**Comment by braunsonm** [comment]
If you're using Istio why aren't you sidecaring oauth2-proxy so it communicates over mTLS for you?

**Comment by ethanchowell** [comment]
I have sidecars and mTLS set up for in-cluster communication, and since posting this have figured out how to set up istio egress to inject certs for outgoing requests. But, that's very specific to istio, and in some environments we push to I don't have istio but mTLS on ingress is the one constant so it felt cleaner to add here.

**Comment by braunsonm** [comment]
Still relevant

**Comment by ethanchowell** [comment]
Still relevant

**Comment by braunsonm** [comment]
Alive

**Comment by ethanchowell** [comment]
Still relevant

**Comment by ethanchowell** [comment]
Still relevant

**Comment by ethanchowell** [comment]
Still relevant

**Comment by rkachach** [comment]
Still relevant

**Comment by weristdominik** [comment]
Honestly, I am experiencing a similar problem (at least I think so). Basically, my oauth2-proxy is trying to connect to an IdP (Dex), but this Dex server sits behind an Nginx reverse proxy that requires mTLS authentication. In this case, oauth2-proxy would need to send a client certificate with its request.

I also tried setting up an Nginx proxy for "internal" traffic without mTLS authentication. However, this approach fails because oauth2-proxy calls the "internal-idp-url," and the Dex server responds with its "public-facing" URL — the same URL that uses mTLS to protect the login UI. Oauth2-proxy cannot handle this URL mismatch.

```
[main.go:59] ERROR: Failed to initialise OAuth2 Proxy: error initialising provider: could not create provider data: error building OIDC ProviderVerifier: could not get verifier builder: error while discovery OIDC configuration: oidc: issuer did not match the issuer returned by provider...
```

**Comment by weristdominik** [comment]
I found an working solution with `Apache2` and `mod_auth_openidc`. If anymone is interested you can find it here: https://medium.com/@mr.dodoro/mtls-and-oauth2-proxy-an-important-limitation-ddf1f43bffb5
