### ISSUE TITLE
How to Configure Prometheus as a Datasource to Grafana secured by Oauth2 Proxy

### ISSUE THREAD

**Issue by cloudpaldev** [oauth2-proxy/oauth2-proxy#1892]
How to Configure Prometheus as a Datasource to Grafana secured by Oauth2 Proxy. 

## Expected Behavior

Grafana should be able to authenticate with Prometheus which is secured by Oauth2 Proxy 

## Current Behavior

Error reading Prometheus: Post "https://promethus.test/api/v1/query": net/http: invalid header field name ""

## Context

I also tried selecting the basic auth param in Grafana Dashboards and then try adding the htpasswdFile to Oauth2 proxy. it did not work either

**Comment by JoelSpeed** [comment]
This isn't something we are familiar with as OAuth2 Proxy maintainers, but I would suggest either having a look through the logs of OAuth2 Proxy and Prometheus or posting them here so others can review them.

Without detail about the requests going through it's very hard to make suggestions on how to help, this issue is too light in detail at the moment IMO
