### ISSUE TITLE
Google `approval_prompt` vs `prompt`

### ISSUE THREAD

**Issue by mariusmarais** [oauth2-proxy/oauth2-proxy#191]
I'm trying to force the Google provider to present an account dialog instead of silently redirecting.

Setting `approval_prompt` to `force` (default) does not in fact force an approval prompt with the Google provider, at least not anymore.

Skimming the parameters in the [Google docs](https://developers.google.com/identity/protocols/OAuth2WebServer#redirecting) shows values `none`, `consent` & `select_account` for the `prompt` field.

Setting any of those values cause the Google side to fail with a 400 error.  Manually changing `&approval_prompt=select_account` to `&prompt=select_account` proceeds as expected.

It seems like Google changed their behaviour at some point to expect `prompt=` and not `approval_prompt=`.

It is possible to set  the `prompt=` value instead of / as well as the `approval_prompt=` value? Should the Google provider be updated to rather set the `prompt` value?

Alternatively, is it feasible to allow any additional parameters to be set for any provider?

**Comment by victornoel** [comment]
For the record, one can set both `consent` and `select_account` with the following: `prompt=select_account+consent`.

Using consent is useful to force the retrieval of a `refresh_token`, see https://github.com/pomerium/pomerium/pull/81 for a similar situation with pomerium.

Note also that enabling `select_account` would be required to avoid the current identity of an already logged in user to be used instead of proposing to login (for example with an identity managed on a domain specific for oauth2-proxy). See https://github.com/pomerium/pomerium/issues/231 for a discussion on the matter, again with pomerium.

**Comment by nzoueidi** [comment]
Having the same issue.

And just for the records @victornoel yes you can set `prompt` to `select_account` and `consent` together - But this would happen only manually by setting them in the headers and re-send them again. 

the `approval-prompt` can only set to `force`, so as mentioned by @mariusmarais is it possible to add and set the `prompt` value instead of / as well as the `approval_prompt` value? Or should the Google provider be updated to rather set the `prompt` value?

**Comment by cagiti** [comment]
I've found that setting `approval-prompt=` seems to do the trick... unless I've got the wrong end of the stick here

**Comment by mariusmarais** [comment]
Just tried with `--approval-prompt=`, but I see no change, I still cannot force a Select Account dialog.

**Comment by mariusmarais** [comment]
On that note, is anyone interested in fixing this?  Clearly the Google Provider is not working as intended.

**Comment by ploxiln** [comment]
I think this was fixed by https://github.com/oauth2-proxy/oauth2-proxy/pull/444 (allowing you to specify `--prompt=foobar`, and that *replaces* the `approval_prompt=force`)
