### ISSUE TITLE
Cookie not updated on refresh even though redis is updated

### ISSUE THREAD

**Issue by estroem** [oauth2-proxy/oauth2-proxy#1946]
Using oauth2-proxy with Azure OIDC and redis. Login works as expected, but refreshing does not. The redis cache is updated, but no Set-Cookie header is set on response from oauth2-proxy. This means the expire date is never updated on the cookie. No error is shown in the logs.

## Expected Behavior

On reauthentication, oauth2-proxy should respond with a Set-Cookie header.

## Current Behavior

On reauthentication, oauth2-proxy does not respond with a Set-Cookie header, even though redis is updated.

The only thing that appears in the logs is this:
`[2022/12/22 09:34:07] [stored_session.go:189] Refreshing session - User: ; SessionAge: 5m7.348710017s`
User is actually missing here, not redacted

## Steps to Reproduce (for bugs)

1. Sign in and wait 5 minutes
2. Refresh the page
3. Cookie expiration is still the same
4. Wait another 50 minutes
5. Cookie is now expired

## Context

This causes the users to lose their cookie and forces them to log in again, often in the middle of a session.

## Your Environment

Running in OpenShift on Azure, as an AuthorizationPolicy in the Istio ingress gateway. Istio installed as part of OpenShift Servicemesh

--provider=oidc
--client-id=***
--oidc-issuer-url=***
--scope=openid email profile offline_access
--cookie-name=***
--cookie-samesite=lax
--cookie-domain=***
--whitelist-domain=***
--cookie-refresh=5m
--cookie-expire=55m
--session-store-type=redis
--redis-connection-url=***
--set-authorization-header=true
--upstream=static://200
--email-domain=*
--http-address=0.0.0.0:4180
--skip-provider-button=true
--skip-jwt-bearer-tokens
--exclude-logging-path=/ping

- Version used:
oauth2-proxy: 7.3.0
istio: 1.12.9

**Comment by JoelSpeed** [comment]
Yeah that's a really good find, we need to make sure that the redis session is setting the `set-cookie` when you refresh the session. Have you had time to look into the code at all to work out where this is going wrong?

**Comment by miguelborges99** [comment]
The set-cookie is in the code, when the `s.store.Save(rw, req, session)` is called. Check `refreshSession `method:

https://github.com/oauth2-proxy/oauth2-proxy/blob/f753ec1ca5c42cd4c4e400afa1f76817638f3010/pkg/middleware/stored_session.go#L207

So, the flow did not reach the save method, then it means that two cases might have occurred, either the `refreshed` variable was equal to false, or an error had occurred. But, since @estroem did not report any log after

`[2022/12/22 09:34:07] [stored_session.go:189] Refreshing session - User: ; SessionAge: 5m7.348710017s`

this means that `refreshed` variable was equal to false.
He is using the oidc provider, then looking into `RefreshSession` in oidc.go

https://github.com/oauth2-proxy/oauth2-proxy/blob/f753ec1ca5c42cd4c4e400afa1f76817638f3010/providers/oidc.go#L111

The only situation when no error is reported, it is when session state is nil or session state has an empty refresh token.
The logs report that session exists, since it has a SessionAge. This leave us with the case that refresh token is an empty string

https://github.com/oauth2-proxy/oauth2-proxy/blob/f753ec1ca5c42cd4c4e400afa1f76817638f3010/providers/oidc.go#L112

Why session state has no user and no refresh token, it is something that @estroem may try to clarify us with more logs.
@estroem Are you receiving the refresh token from your OIDC provider?

**Comment by estroem** [comment]
I'm sorry, this is my mistake. The oauth2-proxy does in fact respond with a Set-Cookie header. Seems like the header is being eaten by Istio on its way back to the user.
