### ISSUE TITLE
[Question] What does sign_out endpoint do when cookie store is enabled?

### ISSUE THREAD

**Issue by nik123** [oauth2-proxy/oauth2-proxy#1958]
I'm configuring oauth2-proxy in pair with Keycloak. I currently use cookie storage. According to the [documentation](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/session_storage): 

> With the Cookie storage backend, all session information is stored in client side cookies and transferred with each and every request.

Since all the information us stored in the client side I'm wondering if calling sign_out endpoint have any effect. Does sign_out endpoint actually do anything in this case? From my understanding, to sign out from the system it is enough to clear the cookies in the client and directly call keycloak sign out url instead of passing it as rd parameter to sign_out aouth2-proxy endpoint. Is my understanding correct?

**Comment by myspaghetti** [comment]
I'm using the same setup. This is what happens:

If you use nginx `auth_request` with oauth2-proxy and Keycloak, the `auth_request` will return authorized as long as the cookie is valid. Clearing the cookie with `sign_out` makes oauth2-proxy re-request authorization from Keycloak. But since the Keycloak session is still valid, oauth2_proxy will issue a new cookie without asking again for verification.

If you want to properly end the session and make `auth_request` return unauthorized, you need to configure the Keycloak client logout settings so that the `Front-channel logout URL` is the oauth2-proxy `sign_out` address. This way when the user ends the session on Keycloak, for example from `realms/master/protocol/openid-connect/logout`, they immediately request `sign_out` afterwards which clears the cookie. Now when nginx checks `auth_request`, it receives "unauthorized" since there's no cookie, and when oauth2-proxy checks Keycloak, it prompts for login details since the session has ended.

In order to avoid situations when the Keycloak session has ended but `auth_request` still returns authorized since the cookie is still valid, I set the cookie refresh value to a few minutes.
