### ISSUE TITLE
alpha config status

### ISSUE THREAD

**Issue by kfox1111** [oauth2-proxy/oauth2-proxy#1964]
Whats the plan around graduating alpha config to something beyond alpha?

**Comment by JoelSpeed** [comment]
Sadly this is a long overdue project and I don't have a lot of time to drive it these days

The outstanding things left to do basically are:
* Complete the migration of all of the non-migrated options
* Work out how to handle environment variables and secret values (I think there's some WIP for this)
* Review the new configuration API as a whole and work out if we are happy with the design and believe it's extensible in the future
* Work on the final deprecation and replacement of the old configuration

The issue here is, we have a lot of change going on around the providers right now, so i think we need to work out what's going on there before we can cement that section of the configuration.

It does make me wonder if we should/could migrate some parts of the alpha configuration to GA and leave other parts of the configuration in their legacy state, a bit confusing for users maybe?
