### ISSUE TITLE
Documentation for backends

### ISSUE THREAD

**Issue by rhuanbarreto** [oauth2-proxy/oauth2-proxy#2065]
The container sidecar pattern is becoming more and more common those days. This is in my opinion the greatest benefit of having the oauth2-proxy. You can separate the auth concern out of the application development concern.

So far the docs exemplify a lot about hoe to integrate with frontend upstreams. But how to make it work in front of APIs, like FastAPI?

There are lots of informations in the docs but they are not presented in a meaningful way so I can know which configs should I use in order to accept a JWT token and validate it against OIDC endpoints.

My specific case is to put a FastAPI backend behind an Oauth2 Proxy that uses multi tenant Microsoft Azure AD. Also there's not much about multi-tenant Azure AD as well.

Could someone help?

**Comment by corybolar** [comment]
I've used oauth2-proxy for a similar use case of fronting rest apis.  Provider was OIDC but shouldn't make a difference with Azure AD.  The most useful settings are `--pass-user-headers`, `--pass-authorization-header`, `--skip-jwt-bearer-tokens`, and possible `--cookie-refresh`.  With user-headers you get the logged in user in the headers received by your backend,  The authorization header gives you the IDToken in the Authorization header that can be inspected for additional claims if present.  Skip-jwt-bearer-tokens allows you to send the IDToken in the Authorization header to oauth2-proxy and have it parsed and verified before allowing a cli user to have access.

Hope that helps a bit.  You can essentially test this all out fairly quickly using the docker-compose scripts in https://github.com/oauth2-proxy/oauth2-proxy/tree/master/contrib/local-environment by adding the variables I listed above to the oauth2-proxy-keycloak.cfg file.

**Comment by umershaekoor** [comment]
Hi,

How would the signout work when using the proxy to protect an api? Specifically, how does the cookie deletion work? Since my understanding is that the identification of a session is done via the cookie is a browser which is sent with the request when /oauth2/sign-out/ is hit. If there is no cookie, how is it identified which ID token is to be deleted?
At risk of answering my own question, is it done via the auth header containing the id token while hitting the /oauth2/sign-out/ endpoint?
