### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by nidhin077** [oauth2-proxy/oauth2-proxy#2075]
Hi,

We utilised GitLab as the provider and configured auth2proxy on our URL. Nevertheless, the domain is not validated for some of our GitLab users, who receive the error 502 bad gateway. After additional investigation, we discovered that the problem was caused by the fact that these individuals were linked to an excessive number of groups, and the domain is getting for a small number of group-associated members.

023/04/03 09:19:18] [session_store.go:163] WARNING: Multiple cookies are required for this session as it exceeds the 4kb cookie limit. Please use server side session storage (eg. Redis) instead.

When we switch the version to the old it's working fine. So please check the issue and resolve it as soon as possible. 

- Version used: 7.4.0

**Comment by JoelSpeed** [comment]
Out of interest, have you tried switching to a server side session storage and trying with one of the currently broken users? 

It's unlikely btw that any maintainer will have the time to investigate or try to reproduce this issue, we don't have access to gitlab. If you can work out where the issue is and can explain/reason it to us we can accept a PR though to fix the issue.
