### ISSUE TITLE
keycloak-oidc broken out of the box with Keycloak 21.x

### ISSUE THREAD

**Issue by brsolomon-deloitte** [oauth2-proxy/oauth2-proxy#2117]
Opening this issue as a result of numerous related issues such as https://github.com/oauth2-proxy/oauth2-proxy/issues/1913 and https://github.com/oauth2-proxy/oauth2-proxy/issues/1931 being prematurely closed.

Oauth2 Proxy as of version v7.4.0 is broken with `provider = "keycloak-oidc"` using the latest available stable Keycloak version 21.x. The authentication flow fails with:

```
[2023/05/16 17:41:06] [oauthproxy.go:830] Error creating session during OAuth2 callback: audience from claim aud with value [account] does not match with any of allowed audiences map[oauth2-proxy:{}]
```

Previous issues were responded to with responses to the extent of "this is Keycloak's fault" or "work with Keycloak to fix this."

On the contrary, this is very much not "Keycloak's fault". We have a platform with around 20 applications integrated with Keycloak/OIDC, and oauth2-proxy is the _only_ one that requires the additional step of adding proxy mapper in the Keycloak admin UI. It's clunky and shouldn't be necessary. At the very least it should be documented by oauth2-proxy. More appropriately, oauth2-proxy should update its API calls to Keycloak to get info that is already readily available.

![keycloak-oauth2-proxy-mapper](https://github.com/oauth2-proxy/oauth2-proxy/assets/81818815/fde46bcd-c629-412e-86f7-1fb85a6b3dba)

**Comment by coffeetrap** [comment]
Hi, any update on this ? I have the same issue and I do not use the `--allowed-group` flag ?

**Comment by tijder** [comment]
@coffeetrap  have you created the correct mappers?

> Create a mapper with Mapper Type 'Group Membership' and Token Claim Name 'groups'.
> Create a mapper with Mapper Type 'Audience' and Included Client Audience and Included Custom Audience set to your client name.

**Comment by SantiagoGaonaC** [comment]
I have the same problem with `provider="keycloak"`, when I create an Identity providers with `provider = "keycloak-oidc"` I get the log:

` [main.go:60] ERROR: Failed to initialise OAuth2 Proxy: error intiailising provider: could not create provider data: error building OIDC ProviderVerifier: could not get verifier builder: error while discovery OIDC configuration: failed to discover OIDC configuration: error performing request: Get "http://localhost:8080/realms/master/.well-known/openid-configuration": dial tcp 127.0.0.1:8080: connect: connection refused`

but this does not happen just by setting `"keycloak"`

**Comment by JoelSpeed** [comment]
> I have the same problem with `provider="keycloak"`, when I create an Identity providers with `provider = "keycloak-oidc"` I get the log:
> 
> ` [main.go:60] ERROR: Failed to initialise OAuth2 Proxy: error intiailising provider: could not create provider data: error building OIDC ProviderVerifier: could not get verifier builder: error while discovery OIDC configuration: failed to discover OIDC configuration: error performing request: Get "http://localhost:8080/realms/master/.well-known/openid-configuration": dial tcp 127.0.0.1:8080: connect: connection refused`
> 
> but this does not happen just by setting `"keycloak"`

Have you got the issuer URL set correctly? The keycloak-oidc provider needs the correct issuer URL to be able to complete the OIDC discovery process and it looks like, it's using the default value at the moment

**Comment by brsolomon-deloitte** [comment]
Please reopen

**Comment by olivierlambert** [comment]
It seems I posed the message in the wrong place the first time.

I had this temporary "fix" in Keycloak for a while (using Mappers), and now with Keycloak 25.1, I can't make it work anymore for any new client I add (or if I modify a previous client):

```
[oauthproxy.go:888] Error creating session during OAuth2 callback: audience from claim aud with value [xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx account] does not match with any of allowed audiences map[elastic:{}]
```

Note: the UUID (given with xxxx here) is the UUID of the client-id.

I checked 10 times, follow the doc in the exact same details and despite that, I can't make it work anymore. Note there's extra fields/boxes in Keycloak 25, that could made the configuration different:
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/1241401/e87e5542-660c-4b89-8a95-3cf2dbd34693)


Does anyone with a recent Keycloak made it work?

**Comment by bhayden53** [comment]
I've followed the oauth2-proxy docs for setting up a dedicated audience mapper, but I am still getting this exact error. Is there supposed to be a workaround?

**Comment by bhayden53** [comment]
@olivierlambert 24.0

**Comment by bhayden53** [comment]
I was able to get it working by retrieving the id_token instead of the access_token to pass as the bearer. This required the addition of the scope=openid param in the call to keycloak to get the token. I also had to add the client_id I was using as an extra audience in the oauth2-proxy config

**Comment by olivierlambert** [comment]
Can you detail a bit more exactly how you did this? I'd like to try on my side, thanks!

**Comment by bhayden53** [comment]
here is a crude python snippet showing how to retrieve the token and pass it to a GET request.
```
    payload = {
        'grant_type': 'client_credentials',
        'scope': 'openid'
    }
    url = f"{args.token_url}"
    print(url)
    resp = requests.post(url,
                         auth=(args.client_id, args.client_secret),
                         data=payload,
                         verify=False)
    token = resp.json()
    print(token)
    bearer = token["id_token"]

    headers = {"Authorization": f"Bearer {bearer}"}
    resp = requests.get("https://localhost/kafka/api/schema-registry/schemas/types/",
                        headers=headers,
                        verify=False)
    print(resp)
    print(resp.content)
```
The token_url arg is, i.e. http://example-domain.com/auth/realms/master/protocol/openid-connect/token
The client_id and client_secret args are for the client you had to create in keycloak.

In the docker compose for oauth2-proxy, I had to add the client to the following environment variable:
OAUTH2_PROXY_OIDC_EXTRA_AUDIENCES: 'same_client_id_from_above'

**Comment by githubbiswb** [comment]
Okay, I have a workaround, but you aren't going to like it

First of all, we are solving 2 problems which is always fun. 1 problem I know how to work around, the other disappeared and hopefully does for you too and I don't understand why.

***********************************************
Problem 1: Audience
You need to verify that your user has the correct audience name, because Keycloak seems to at first put in a weird ID string instead of the name you gave it. To verify yours is working do the following

Keycloak -> Realm -> <your oauth2 proxy client> -> Client scopes -> Evaluate -> Users

Pick a user from that list

On the right side click Generated access token

Verify under "aud":{} that your oauth2 proxy client name matches. If you see a UUID looking thing there, go back and delete your client mapper and set it up again. 

I don't know why this works, but now mine does. I would poke around with the options, onetime I named my mapper NOT my client name, and just put the client name in the alternative field. But at this point, I have mine set the way the docs say and it works with also adding the name into the Included Custom Audience field
Mapper Type: Audience
Name: <myoauth2proxyclient>
Included Client Audience: null
Included Custom Audience: <myoauth2proxyclient>
Add to ID token: On
Add to access token: On
Add to lightweight access token: On
Add to token introspection: On
**************************************************

Problem 2: Roles aren't seeming to matter, so that if you set --allowed-role=<correctrolname> you get 403 errors.

Here it seems oauth2proxy is doing a serach of the token, finds the very first word "role" pulls in those array values. And stops. It doesn't look anymore for roles. Even if you direct the --allowed-role to the correct array with the clientname_roles:role name format

Clearly this is a bug, and I lack the abilites to find it, but hopefully my post will inspire someone who does understand it better than me. 

But to work around your problem, you need to add a role for application access to your Realm Roles. 

The good news is any user you have already created will NOT automatically inherit this role. What I can't speak for as I can't test it, is what happens when NEW user is created. Do they just inherit that realm role, and I assume they would. 

But you can also take out realm roles from individual users to alleviate this problem. This is for sure not ideal, and if you are reading this post in the year 2025 or after, please verify you need to do this. Hopefully the issue is fixed and you won't need this work around. 

@olivierlambert I think you can fix your issue with the Problem 2 workaround, and I only shout you out because I love XCP-NG. Everyone should ;)

**Comment by olivierlambert** [comment]
Hey thanks! I will test it ASAP :+1: (well... in 2 weeks, when coming back from some deserved rest :D )

**Comment by dextercai** [comment]
with `oidc_extra_audiences = ["account"]` will make every user in realm can login.

**Comment by FingerlessGlov3s** [comment]
To fix my audience value, from being the guid to the client-id. I exported the client config from Keycloak,

In the `protocolMappers` section you will see your Audience mapper, you'll notice `included.client.audience` is set to the guid, I changed that to match the client id. I then deleted the client from Keycloak and imported my modified client, and it's working now.  I would assume this is a bug in keycloak itself?
```
    {
      "name": "Audience",
      "protocol": "openid-connect",
      "protocolMapper": "oidc-audience-mapper",
      "consentRequired": false,
      "config": {
        "included.client.audience": "7fa043da-ae34-466e-a58e-b2d823c63587",
        "introspection.token.claim": "true",
        "userinfo.token.claim": "true",
        "id.token.claim": "true",
        "lightweight.claim": "false",
        "access.token.claim": "true"
      }
    },
```

to
```
    {
      "name": "Audience",
      "protocol": "openid-connect",
      "protocolMapper": "oidc-audience-mapper",
      "consentRequired": false,
      "config": {
        "included.client.audience": "my-client",
        "introspection.token.claim": "true",
        "userinfo.token.claim": "true",
        "id.token.claim": "true",
        "lightweight.claim": "false",
        "access.token.claim": "true"
      }
    },
```
