### ISSUE TITLE
CSRF per requests can lead to 431 Header too large

### ISSUE THREAD

**Issue by pfragoso** [oauth2-proxy/oauth2-proxy#2163]
Currently having the --cookie-csrf-per-request=true sometimes can generate cookies that are larger than normal leading to being blocked.

This happens even with --cookie-csrf-expire is set to 1 minute

## Expected Behavior

I would assume that the cookie generate is on the limit of the RFC.

## Steps to Reproduce (for bugs)

This easily appears if you have multiple instances of auth2-proxy or if there are multiple tabs opened and one of the applications has some kind of reload/workers mechanism. 

I've attached an example of a normal session that for some reason have a lot of _csrf 
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/671634/ae8f1fba-58be-4c74-a944-2e02eb6ba515)

## Your Environment

- Version used: public.ecr.aws/bitnami/oauth2-proxy:7.4.0 in EKS 1.27

**Comment by tuunit** [comment]
Hi @pfragoso,

which IDP are you using? Do you see any warnings or errors in the logs?

**Comment by thefaftek-git** [comment]
@tuunit we're seeing the same issue with the AAD connector, I'm not seeing anything obvious in the logs, but happy to share if you let me know what log data you're looking for

**Comment by tuunit** [comment]
@thefaftek-git which IDP / provider are you using?

**Comment by thefaftek-git** [comment]
> @thefaftek-git which IDP / provider are you using?

Azure AD, we’re currently seeing this in an app that’s an SPA, I’m planning to use a few different basic apps to see if I can replicate what exact scenarios cause the behavior to occur.

**Comment by tuunit** [comment]
I was expecting that you use Azure. This is a known issue. For Azure you will have to use redis as the session store, because of the large number of groups put into the cookie.

**Comment by thefaftek-git** [comment]
> I was expecting that you use Azure. This is a known issue. For Azure you will have to use redis as the session store, because of the large number of groups put into the cookie.
> 
> https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/session_storage#redis-storage

Our issue is the CSRF cookies keep growing until we get issues, not the session cookie itself, most of our users don’t have many groups and we don’t use group claims in this app, so that shouldn’t be the cause of this behavior. I can try redis, but would that solve this CSRF cookie issue?

**Comment by tuunit** [comment]
So you think the issue is that because of the `--cookie-csrf-per-request` flag you create too many cookies as shown in your screenshot and therefore at some point get 431 header too large. Can you provide more logs / information which entity generates the error? Oauth2-proxy, your loadbalancer / ingress or your browser?

**Comment by miguelborges99** [comment]
@pfragoso It seems that your system is doing quite an amount of parallel authentication requests. Could it be some flaw in the design of your web application ?
Instead of using cookie storage, try to use [redis ](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/session_storage#redis-storage)storage.

And, remove the --cookie-csrf-per-request flag, since in redis may not be needed.
