### ISSUE TITLE
Pre-built image on quay return high violation warnings - updates needed

### ISSUE THREAD

**Issue by DelfiGhazaleh** [oauth2-proxy/oauth2-proxy#2243]
## Expected Behavior
The pre-built docker image should be in good health and free of 'high' or 'critical' violations

## Current Behavior
The oauth proxy pre-built docker image on quay has some 'high' urgency violations when deployed on openshift. It shows 'fixable severity at least important'
It reqiures updates for the following libraries:
<img width="1152" alt="image" src="https://github.com/oauth2-proxy/oauth2-proxy/assets/117922467/3332a866-52fd-4297-8351-4ac74b031c5f">

 

## Possible Solution
Update the vulnerable libraries and patch update to the image

## Context
This prevents us from using the proxy image for any productions

## Your Environment

- Version used: the issue was present for following versions: 7.5.0, 7.4.0, 7.2.1

**Comment by tuunit** [comment]
As of now the container images for this project are never updated after the initial build but we might need to consider this.

**Comment by charbonnierg** [comment]
I stumbled accross this issue this morning, and though it would be a good exercice to to come up with some kind of solutions to the problem in order to learn more about GitHub and GitHub actions. I created a repo which may (or may not) be useful to you, which shows how to schedule builds for historical releases. Here's the link: https://github.com/charbonnierg/demo-dynamic-matrix.

**Comment by tuunit** [comment]
Hi @charbonnierg,

thank you for your effort. The issue is not that we don't know how to do it but that we currently don't want to rebuild and re-tag existing versions of the application. Unfortunately, we don't have enough tests and especially no regression testing in place to guarantee that a re-tagged version still functions. In most every case they should still work but in special circumstances it could break previous versions and deployments. Therefore the current project policy is to regard the container images on quay.io as immutable.

**Comment by tuunit** [comment]
The only solution I currently see is to build docker images from scratch without any dependency on an underlying OS. Which would mitigate the issue by only having to rely on the go lang dependencies.

**Comment by charbonnierg** [comment]
I get what you mean, but IMHO, as a user of your project, I don't expect  images associated to short tags to be immutable. And if something breaks because I did not use a SHA but used a short tag, I would consider that this my fault, not yours. I'd even say that any Docker build / deployment which must be reproducible must also use SHA.

**Comment by tuunit** [comment]
Hi @charbonnierg,

unfortunately, this is the current project setup and has been like that for years. As it is quite tricky to get proper community feedback and project changes like this. We are currently hesitant to publish a change like that. I'm currently getting a PR reading regarding nightly builds of the master branch and I will most probably try to get a `build from scratch` version of the containers running as well.
