### ISSUE TITLE
NGINX auth_request example returns 200 when unauthorized

### ISSUE THREAD

**Issue by WhiteRabbit-Code** [oauth2-proxy/oauth2-proxy#2322]
The NGINX example with the auth_request directive in the docs returns 200 OK for the sign_in page on unauthenticated requests.

## Expected Behavior

oauth2-proxy responds to unauthenticated (without a session cookie) static files requests with HTTP-status 403 and the sign in page as body.
The same behavior is expected when running behind a NGINX reverse proxy.

## Current Behavior

When requesting a page at NGINX without a session cookie, the auth_request returns 401. This triggers NGINX to return the page defined in the error_page directive. This is /oauth2/sign_in, which itself is returned by oauth2-proxy with 200 OK.
This leads NGINX to deliver the sign in page with a 200 OK status code, instead of 403.

## Possible Solution

Update the error_page directive in the NGINX as in PR #2323.

## Steps to Reproduce (for bugs)

GET http://nginx/test -> returns 200
GET http://oauth2-proxy/test -> returns 403

## Your Environment

- Version used: v7.5.1

**Comment by WhiteRabbit-Code** [comment]
still relevant

**Comment by LeVraiRoiDHyrule** [comment]
Hi, did you succeed to make Oauth2-proxy work with nginx's auth_request ? I am trying to do the same thing with Caddy's equivalent, forward_auth. I think that the Oauth2-proxy configuration would even be the same. What happens when you try to go to a protected app with your setup ? I am having "Unauthorized" with the configuration described here : https://github.com/oauth2-proxy/oauth2-proxy/issues/2380. Could you please share your config ?
