### ISSUE TITLE
Allowing to pass header `Authorization: token` 

### ISSUE THREAD

**Issue by Ravio1i** [oauth2-proxy/oauth2-proxy#2339]
The Header `Authorization: Token` is not passed to the backend.

```bash
  - --pass-authorization-header=true
  - --pass-access-token=true
  - --skip-auth-route=^\/api\/.*
```

## Expected Behavior

A request, e.g with curl 

```bash
> curl -v -X GET https://myapp.domain.com/api/something -H 'Authorization: Token ***'
```

## Current Behavior

```bash
Authentication credentials were not provided
```

Since the header never arrives at the app

## Possible Solution

- Allow somehow the Authorization token 
- Allow custom rules for authorization headers

## Steps to Reproduce (for bugs)

Trying to pass `Authorization: Token ***`  and see if it arrives at backend

## Context

I have configured the oauth proxy with oidc to reach my app. The access with the UI with the OIDC authentication works as expected.

The app  shall use direct api access (`/api/`) with the Header `Authorization: Token ***`. However, I cannot find any way to pass through the oauth2-proxy this kind of header. The rquest itself reaches the backend, but not the header.

## Your Environment

ingress --> oauth2-proxy --> nginx --> app 

- Version used: v7.5.1

**Comment by JoelSpeed** [comment]
When you skip the authentication using skip auth route, we skip the authentication... So we don't look for an existing session and we don't therefore, inject the authorization header as the session has not been processed. I think this is working as expected.

Why have you configured your API to have the skip auth route option?

**Comment by JoelSpeed** [comment]
Oh wait, are you trying to use a token outside of OAuth2 Proxy rather than using a session that we create? We have some logic that strips headers that we would otherwise send to avoid users potentially exposing themselves to security issues.

Imagine if they expect a security header like this one to be populated by OAuth2 Proxy and we blindly passed through an invalid value that was set in the request, they lose their trust boundary there.

I think you can try `--skip-auth-strip-headers=false` to disable that behaviour

**Comment by Ravio1i** [comment]
Oh hey yes `--skip-auth-strip-headers=false` worked :) Thank you very much!

**Comment by markbaumgarten** [comment]
So --skip-auth-strip-headers=false is not the right way to access the auth token? I would like to see how one should use the oauth2-proxy session... In a fast api backend preferably.
