### ISSUE TITLE
[Feature]: Disable header flattening

### ISSUE THREAD

**Issue by aslafy-z** [oauth2-proxy/oauth2-proxy#2455]
### Motivation

I want to bind oauth2-proxy to kubernetes-dashboard impersonation.

kubernetes-dashboard requests headers in this form:

```
Impersonate-User: username
Impersonate-Group: group1
Impersonate-Group: group2
Impersonate-Group: group3
```

Currently, [this code](https://github.com/aslafy-z/oauth2_proxy/blob/b1fcb45b135317295b32d75b285b6afa718caac5/pkg/middleware/headers.go#L80) forces the computed headers to be flattened, joined with `,`.

I see that this behavior was implemented with https://github.com/oauth2-proxy/oauth2-proxy/issues/1017.
I'm think this behavior should be made configurable.

Note that this is unlikely to be solved anytime soon on Kubernetes level: https://github.com/kubernetes/kubernetes/issues/82468

### Provider

Any

**Comment by aslafy-z** [comment]
AFAIK, ingress-nginx does not support passing non-combined headers to backend...
https://github.com/kubernetes/ingress-nginx/blob/0c3d52bade1219c1d61d486e44a91ded48766aac/internal/ingress/controller/template/template.go#L602

**Comment by aslafy-z** [comment]
I'd would like to address this issue, however, I'm not sure how to access config within this block. Can someone give me some path?

**Comment by JoelSpeed** [comment]
It has been a long time since this was introduced, but, I believe at the time we deliberated over this for a while, and came to the conclusion that flattening the headers was appropriate and in accordance with the HTTP spec. IIRC as well, there are other projects, specifically I believe nginx which would, even if we sent individual headers, flatten them for us.

I think the issue you have here is a bug in Kube, rather than an issue with OAuth2 Proxy or otherwise/ I see though that there's resistance in making movements on the Kube side, not sure how best to approach this, but I'm currently -1 on fixing it in OAuth2 Proxy

**Comment by miquelcv** [comment]
This is still relevant with the current Alpha Config `injectRequestHeaders`.

We hit this while integrating oauth2-proxy with Tekton Dashboard using Kubernetes impersonation:

```yaml
injectRequestHeaders:
  - name: Impersonate-Group
    values:
      - claimSource:
          claim: groups
```

For a multi-valued `groups` claim, oauth2-proxy forwards:

```http
Impersonate-Group: group-a,group-b
```

while Kubernetes expects:

```http
Impersonate-Group: group-a
Impersonate-Group: group-b
```

and treats `group-a,group-b` as a single group.

We confirmed the difference directly:

```bash
kubectl auth can-i list namespaces \
  --as=user@example.com \
  --as-group=group-a \
  --as-group=group-b
# yes

kubectl auth can-i list namespaces \
  --as=user@example.com \
  --as-group='group-a,group-b'
# no
```

Regarding the HTTP semantics discussed above: RFC 9110, Section 5.3 allows combining repeated field lines only when doing so does not change the message semantics. In this case it does, because Kubernetes allows group names containing commas and defines `Impersonate-Group` as a repeatable header.

I understand the reasons for keeping flattening as the default. Would you consider an explicit opt-in in Alpha Config to preserve multiple values for selected injected headers?
