### ISSUE TITLE
[Bug]: Redirect deadlock on calling upstream path with query string

### ISSUE THREAD

**Issue by luklichtm** [oauth2-proxy/oauth2-proxy#2458]
### OAuth2-Proxy Version

7.5.1

### Provider

oidc

### Expected Behaviour

Query string gets appended after trailing slash of the path.
E.g. for /path?param=1:
Request: GET /path?param=1 ==> Response: 301 /path/?param=1

### Current Behaviour

Trailing slashes get appended until browser throws ERR_TOO_MANY_REDIRECTS.
E.g. for /path?param=1:
Request: GET /path?param=1 ==> Response: 301 /path?param=1/
Request: GET /path?param=1/ ==> Response: 301 /path?param=1//
[...]
Request: GET /path?param=1////////// ==> Response: 301 /path?param=1///////////
etc.

### Steps To Reproduce

1. Using local test environment https://github.com/oauth2-proxy/oauth2-proxy/tree/master/contrib/local-environment
2. Adjust upstream in config oauth2-proxy.cfg: upstreams="http://httpbin.localtest.me:8080/httpbin/"
3. In local-environment run docker compose up
4. In Browser: Open http://oauth2-proxy.localtest.me:4180/httpbin?param=1

**Comment by JoelSpeed** [comment]
Is this specifically because there is a trailing slash on the end of the upstreams? Does it change behaviour if you remove that trailing slash?

Did you manage to find at all logs/any indication of where in the code this might be happening? Did this start with a particular version, is it a regression?
