### ISSUE TITLE
[Feature]: Return a custom JSON response

### ISSUE THREAD

**Issue by marjus45** [oauth2-proxy/oauth2-proxy#2496]
### Motivation

I would like to be able to set a custom JSON response body in the error cases (40x) instead of the default JSON body `{}` which is currently hardcoded in the code. The motivation is two folded:
1. I would like to make a distinction in my client that this response is actually coming due to an Invalid Token 40x response than any other API response that may receive with the same status code.
2. I would like my client to handle a uniform JSON response for all 40x/50x requests which I am defining

### Possible solution

I propose that we configure a map from a status code (e.g., `401`) to a file containing the JSON response:
```toml
status_to_json_files = {401 = "/etc/oauth2_proxy/401.json", 403 = "/etc/oauth2_proxy/403.json"}
```
and when a request arrives which ends up in the `errorJSON` function (i.e., we want to return a JSON response) if there is defined such a map, and that map contains the HTTP code, then return the content in the file, otherwise return the default body (i.e., `{}`).

I have already been working on this, and I am will to make a PR, if you are open to this feature.

### Provider

None

**Comment by JoelSpeed** [comment]
The first question that pops to mind is, what is missing from the json responses that we return today, that means you need something custom?

Our responses should be uniform to each other, and where we are returning errors, there are conscious decisions typically made on which information is and isn't exposed, if we aren't telling the user why the error occurred, it's normally because we think that if the user had that information, it would tell them something we don't want them to know (eg see how GitHub handles a repository that you don't have access to, it 404s, not 403s)
