### ISSUE TITLE
[Bug]: Azure provider: problem with ProfileURL/ userInfoURL (duplicate of closed issue #2162 )

### ISSUE THREAD

**Issue by nbarlowATI** [oauth2-proxy/oauth2-proxy#2645]
### OAuth2-Proxy Version

v7.6.0

### Provider

azure

### Expected Behaviour

All users on our Azure tenancy should be able to authenticate via oauth2-proxy and use our application.   When "enriching the session" with user info, if they don't have the "email" field set in their Azure profile, the code suggests that "userPrincipalName" should be used instead.

### Current Behaviour

As reported on #2162  (apologies for the duplicate, but that Issue is closed, and I do have new information (see below)),
those users who don't have "email" set in their profile, get a 500 error "unable to find userPrincipalName: type assertion to string failed", even though they do have valid "userPrincipalName" in their profile (as obtained from https://graph.microsoft.com/v1.0/me ).

### Steps To Reproduce

User with no "email" set in their profile tries to login.

### Possible Solutions

The reason for this is that the "ProfileURL" queried in `azure.go`'s `getEmailFromProfileAPI` is `https://graph.microsoft.com/oidc/userinfo`, which is indeed the one returned by the discovery in `provider.go` via `https://login.microsoftonline.com/{tenant-id}/v2.0/.well-known/openid-configuration`.    However, this user info endpoint (described here https://learn.microsoft.com/en-us/entra/identity-platform/userinfo) doesn't have fields for "otherEmails" or "userPrincipalName".

Incidentally, the URL `https://graph.microsoft.com/v1.0/me`, which is set as `azureDefaultProfileURL` in `azure.go` DOES have these fields, but this is not the URL that ends up getting queried.

### Configuration details or additional information

(Apologies for opening a duplicate to #2162, wasn't sure how easy it is to reopen that, but happy to discuss on that thread if that is preferred).

**Comment by SlackingVeteran** [comment]
I ran into same issue for guest accounts in tenant.

I dug a lil into the issue and it seems like the new profile URL you are seeing https://graph.microsoft.com/oidc/userinfo" is coming from ProviderVerifier endpoints https://github.com/oauth2-proxy/oauth2-proxy/blob/10f26364c66c70d92fd5e988c9acfd2d1d5e8375/providers/providers.go#L107

It looks like we can skip the override of bunch of values through discovery by setting SkipDiscovery to true in OIDC config of the provider. Idk what the downside of that is going to be, I'd imagine this means we should setup LoginURL, RedeemURL manually if we want to use tenant specific login and redeem url instead of common one as well as v2 endpoint as the default ones seem to be v1 endpoints. But I am worried about JWKsURL and SupportedCodeChallengeMethods not being set if discovery is disabled.

I am gonna try out by disabling discovery and see if that resolved the issue for me.
I also think if a profileURL, LoginURL and RedeemURL is defined in the provider config than we should use those instead of them being overridden by discovery. Maybe another bool that allows to choose between discovery one or the user defined one?

@JoelSpeed whats your thought on this?

**Comment by SlackingVeteran** [comment]
So turns out for users in our tenant token authed token had email, groups and all the required info available. It was the guest accounts where email and groups were unavailable in the token so it tried to get the profile from profileURL. The MS discovery provides https://graph.microsoft.com/oidc/userinfo and it only provides the following:
```
{
    "email": "",
    "family_name": "",
    "given_name": "",
    "name": "",
    "picture": "https://graph.microsoft.com/v1.0/me/photo/$value",
    "sub": ""
}
```

Which is not the same json expected by getEmailFromJSON called by getEmailFromProfileAPI in azure.go

My solution was to turn of discovery with SkipDiscovery set to true and setting `JwksURL`, `profileURL`, `loginURL` and `redeemURL`.
For V2 Azure Auth endpoint i used following:
```
JwksURL: "https://login.microsoftonline.com/{tenant-id}/discovery/v2.0/keys"
profileURL: https://graph.microsoft.com/v1.0/me
loginURL: "https://login.microsoftonline.com/{tenant-id}/oauth2/v2.0/authorize"
redeemURL: "https://login.microsoftonline.com/{tenant-id}d/oauth2/v2.0/token"
```
All the default endpoints defined in azure.go are for v1 auth.
If you are using v1 than just defining `JwksURL` after enabling `SkipDiscovery` is enough

**Comment by nbarlowATI** [comment]
This workaround works perfectly for me - many thanks @SlackingVeteran !!!
