### ISSUE TITLE
[Bug]: provider-ca-file command line option is not working

### ISSUE THREAD

**Issue by jub77** [oauth2-proxy/oauth2-proxy#2802]
### OAuth2-Proxy Version

7.7.0

### Provider

oidc

### Expected Behaviour

The option `--provider-ca-file=/etc/ssl/custom/ca.cert` should allow to access to oidc with self signed ca certificate. The version 7.6.0 works just fine with the same setting.

### Current Behaviour

And error is thrown:

```
[2024/10/03 10:06:53] [provider.go:55] Performing OIDC Discovery...
[2024/10/03 10:06:53] [main.go:59] ERROR: Failed to initialise OAuth2 Proxy: error initialising provider: could not create provider data: error building OIDC ProviderVerifier: could not get verifier builder: error while discovery OIDC configuration: failed to discover OIDC configuration: error performing request: Get "https://test.local/auth/realms/test/.well-known/openid-configuration": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

### Steps To Reproduce

Configure proxy with settings `--provider-ca-file=` and try to connect to oidc.

Part of configuration:

```
--provider=oidc
--oidc-issuer-url=https://test.local/auth/realms/test
--client-id=client-id
--http-address=0.0.0.0:3000
--upstream=http://127.0.0.1:8080
--reverse-proxy=true
--ssl-insecure-skip-verify=false
```

**Comment by dashkan** [comment]
```shell
--ssl-insecure-skip-verify=true
```

Is also broken. I had to revert back to 7.6.0

**Comment by tuunit** [comment]
I'll try to find some time to reproduce the issues and release a bugfix.

**Comment by tuunit** [comment]
Updated the release page to reflect that this is a known issue now.

**Comment by jmazzitelli** [comment]
Interesting. I think this broke the Kiali CI tests as well: https://github.com/kiali/kiali/pull/7790

**Comment by tuunit** [comment]
For those interested. I was able to reproduce the issue and found the culprit of it:
https://github.com/oauth2-proxy/oauth2-proxy/commit/3045392c1700d66345426fcb8aaf4311bae03eff

https://github.com/oauth2-proxy/oauth2-proxy/pull/2570

Unfortunately, I don't have a fix yet but at least I can say with certainty that after reverting this commit the issue goes away so that helps to narrow it down a lot. Furthermore, I have written an e2e test that will help to mitigate breaking the ssl handling specific flags in future PRs and will be merged soon.

**Comment by tuunit** [comment]
Was able to validate a possible fix in #2803

**Comment by tuunit** [comment]
Fix is done. Waiting for review by @JoelSpeed

**Comment by tuunit** [comment]
Hi @jub77, @jmazzitelli,

patch release is out now: https://github.com/oauth2-proxy/oauth2-proxy/releases/tag/v7.7.1
