### ISSUE TITLE
Logout from  kibana is not removing cookies from local browser

### ISSUE THREAD

**Issue by deekshith-elear** [oauth2-proxy/oauth2-proxy#364]
Hi,
I'm using oauth2_proxy with kibana to use our oauth. I'm facing a problem while logout from kibana that oauth2 proxy not able to clear cookies from browser due to this kibana is re-logging. 
can anyone help me out to resolve this issue?

**Comment by morarucostel** [comment]
Hi @deekshith-elear ,
If my understanding is correct, the flow in your use-case is:
1. Login in kibana UI, which is using the oauth-proxy (since you are not authenticated) and then redirects the call to the IDP,
2. Successful login, oauth-proxy creates and stores a browser cookie (specific to oauth-proxy), which then your browser redirects you to the initial url, Kibana UI (which also has its own browser cookie),
3. When you logout from Kibana, presumably Kibana removes the specific Kibana cookie but you still remain authenticated from oauth-proxy perspective,
4. Any new invokation, which requires authenticated access goes back on step 1, but now you have the oauth-proxy cookie there, so no more IDP, just redirects you automatically as authenticated user. 

We had something similar and what we did was to use the `rd` capability of the sign_out from oauth-page. You can look at #314 .
The idea is to chain the two log out methods (the Kibana and the oauth-proxy) so that each one will remove it's own cookie. I did it invoking the oauth-proxy specific sign_out endpoint, passing the  `rd` parameter to the application specific sign_out action (in your case the Kibana sign_out page). I'm assuming you can chain them the other way arround if this is your case.
