### ISSUE TITLE
Do not propagate the _oauth2_proxy cookie to the upstream

### ISSUE THREAD

**Issue by holyjak** [oauth2-proxy/oauth2-proxy#388]
Currently the `_oauth2_proxy` (or whatever it is named via `-cookie-name` is included in the request sent to the upstream. This can be a problem if used with the `-session-store-type=cookie` because those cookies can be quite large and exceed the 8k limit that many web servers (e.g. Tomcat, Jetty) set on the max header size. And the cookie is of no interest to the upstream.

## Expected Behavior

The proxy should remove its own auth cookies from the request before sending it upstream.

## Current Behavior

See above.

## Context

Requests to my server were failing without any explanation with 400 Bad Request. Similarly, requests that by backend forwards on were failing for the same reason.

## Your Environment

- Version used: v5

**Comment by JoelSpeed** [comment]
The cookies are capped at 4kb deliberately to fit within the spec. If you are seeing cookies bigger than this then that is a bug, could you please verify this?

We are also strongly encouraging people to use the redis store where possible, especially if using a provider (eg Azure) that provides very large ID Tokens

**Comment by holyjak** [comment]
The size of individual cookies is OK but the total size of the cookies
(plus the Auth. header) exceeds the default limit on total header size.

**Comment by JoelSpeed** [comment]
@holyjak do you get the same problem if you use the redis storage mechanism for cookies?

**Comment by holyjak** [comment]
I assume not, haven't set it up yet though that is the plan.

**Comment by jbreiding** [comment]
If using K8s, you can "solve" this by stripping the cookie from the upstream ingress configurations, not the oauth2_proxy ingress.

> annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header cookie "";

We are experiencing an issue right now with an updated chrome blocking the cookie as its just passed the 4096. I believe the calculation for size is not matching up with what chrome is using.

Curiously is the data here, 
https://github.com/pusher/oauth2_proxy/blob/master/oauthproxy.go#L265

The same used in this calc?
https://github.com/pusher/oauth2_proxy/blob/master/pkg/sessions/cookie/session_store.go#L102

I asked this because the entire string from the set-cookie header coming back is about 4153 for our current sessions, and if we calc the cookiename=.*; length its just under 4096.

**Comment by JoelSpeed** [comment]
I have had another think about this and concouded this is probably a sensible improvement to make, not sure I really understood it the first time round 😅

**Comment by JoelSpeed** [comment]
Still needs attention
