### ISSUE TITLE
Provider proliferation needs to stop! 

### ISSUE THREAD

**Issue by JoelSpeed** [oauth2-proxy/oauth2-proxy#429]
Over the last year or so, many new providers have been added to the project. Each has had minor differences that mean they do not work well with existing providers.

Ultimately, all of the providers rely on the same protocols underneath, therefore we should be able to create a generic enough provider that has enough flexibility in its configuration to provide a working implementation for most if not all of the existing providers.

What I would like to see long term, is that each of the exiting providers just becomes a preset set of options to a new more flexible provider that underlies all of the existing providers. This may not be possible, but it's something I would like to explore. If there are really special cases, then an extension point should be added to the interface to allow custom providers to wrap the base implementation as necessary, but hopefully this will be minimal.

With this, hopefully we can deprecate a number of the new options that have been added (especially the provider specific ones) and make the provider implementation a lot more generic and less confusing to use.

I think the best course of action to go forward with this, would be to draft a proposal for a new implementation of the provider, to show what options it will have, how it will work, the interfaces required and how existing providers will be migrated to use this new provider.

In the mean time, I propose we block new provider implementations from being merged and urge users to run a fork in the mean time until we can get this generic provider implemented. That said, anyone wanting to add a provider should reach out via an issue so that we can make sure the new provider implementation will satisfy their needs

cc @syscll @steakunderscore

**Comment by holyjak** [comment]
I see some providers have quite specific calls to get information about the user's access etc, which I suspect will never be available via the standard OIDC. Perhaps it would make sense to make it possible to extend oauth2 proxy with e.g. Lua scripts, so that users of these providers could do whatever extra validation they wanted, without bloating the proxy itself? As long as the providers are compliant enough to support the standard login flow so that we end up with an auth and ID token, we could then delegate all validation (beyond #466) to the custom script (if provided).

**Comment by JoelSpeed** [comment]
I have been considering this myself, and you are correct, there is definitely some stuff that is quite provider specific (eg fetching groups for some providers) that we will likely never be able to make generic.

I like the idea of an extension point, though I think it should be more generic than enforcing a particular scripting language on users

Alternate ideas for extensions could be:
- Webhooks that extend a session or validate the session in some particular way (similar to how K8s does this)
- A binary interface so the proxy would os.Exec a binary with  the session json encoded and expect the session to be returned once modified, json encoded again
- Through Go plugins that match a particular interface for extending the session information

**Comment by arianvp** [comment]
My comment here seems related: https://github.com/oauth2-proxy/oauth2-proxy/issues/479#issuecomment-618020509

**Comment by rabbers** [comment]
I have recently run into this problem. I am using OIDC to authenticate with Azure B2C, but I can see that the default functin in OIDC is to mark some items as "Not Implemented". This is not on optional properties either.

For my scenario I can see that Microsoft documentation suggests that the content of their "id_token" generally offers MORE information than their UserInfo endpoint - I can also see that accessing their UserInfo endpoint is not compatible with oauth2_proxy's attempt to load the user profile.

In this case I would like to see configurable way to map id_token claims into the UserInfo response. Unfortunately I don't have the proper golang skills to work with JSON. I could imagine a flag such as e.g. --user-info preferredUsername=name and --user-info expiry=exp

I'd be interested in knowing how many other identity platforms could be addressed in this manner.

**Comment by JoelSpeed** [comment]
> In the continue link as part of the callback response_type and request_uri, I see skip_sso=true. Changing that to false fails as expected. Is my redirect with nginx correct or is there another redirect I can do?

I think I would like to see this kind of thing across all providers. One thought I had was by extending the sessionstate structure to include an additional claims `map[string]interface{}`, we could allow users to request their provider to try to extract extra claims and place them in this map. Then the userinfo endpoint could grab the extra claims from there

**Comment by rabbers** [comment]
I really needed this for OIDC, so have put a draft PR forward (#610). I've had to add a method to the Provider interface. I came to the same conclusion on map structure, but in mine the provider method returns that structure and OAuthProxy picks it up - this means that there is no change to the SessionState. It's there if you think you can use it.

I'm not sure what expanding the SessionState would add to this because I don't think that adding a provider method broke any providers, it's just that the default implementation is a "Not Implemented" stub.

**Comment by arianvp** [comment]
I'd say this is still relevant

**Comment by rabbers** [comment]
I don't think that there is anything wrong in particular with the provider model because it allows provider implementations to be quite sparse in that they only have to define a handful of functions to repurpose the base provider.

In general though I'd like to put forward another opinion on this, which may be at odds with Joel's initial concern and guidance, but it seems to me that the problem is not that there is a huge proliferation of providers, because that is in itself most compatible with open-source i.e. if you don't have a provider, and can't see what you need, write a provider!

The problem is that providers keep getting added into the core product, and that has a direct burden upon management and support of the project.

Some commentors have discussed using "lua", obviously there would be other script languages to consider, and this is a great idea - I see this as an option though, not a replacement to a derived class approach if that can be separated nicely in terms of development environment and build.

I'd be very interested in one of you golang guys discussing the proposition of dynamically loading a pre-compiled provider written in golang. I like the idea of spinning highly peculiar providers out to user's own projects and using the same language.

PS: A very quick afterthought: Architecturally, any external project needn't be given internal interfaces, indeed we could give them a new "ProviderEvents" interface including OnBefore, OnDone, OnSuccess, OnFail functions - not only could 3rd parties compile their own ProviderEvents libraries, this project could implement a LuaScriptProviderEvents class, or spin up a new repo for that. OnBefore could return true to indicate that the existing base implementation should run, false to completely override existing behavior (success/fail marker would have to be in a property or vice-versa). The "ProviderEvents" late-bound class would be the setting, so you'd use Base with "LuaScriptPrivoderEvents" or with "MySpecialAzureB2CProviderEvents". 

Does any of this sound like *the Answer*?

**Comment by gargath** [comment]
While I think @rabbers' suggestion is interesting, I'd advise caution when contemplating dynamically loading functionality at runtime.

This is a security product and allowing third-party code to be loaded at runtime in this way - regardless of whether it is precompiled libraries or scripts - opens up huge challenges.
Users will ultimately have to ensure that this code is not only safe from the source but also safely distributed to where it is used.
That is a burden that I don't think is worth incurring.

Maybe the answer is to simply only accept new providers if someone volunteers to be code owner for that provider code?
If a code owner leaves, that provider could be declared deprecated and ultimately removed unless it is adopted by someone else?

I don't think there are easy answers here, I'm afraid.

**Comment by rabbers** [comment]
In terms of the code being late-bound rather than compiled in, I don't really think that there is a difference (except that late-bound has to be usable without the caller having full knowledge of the content). Consider that a new user can't just change oauth-proxy, they have to fork it. Forking the project and compiling in one piece for static binding has a similar level of risk for the end user as forking a provider starter-kit project and making a custom build from stock oauth-proxy with their custom dynamic library. @gargath is correct to clearly identify that this is a risk, but I don't think the risk differs that much between the two implementation styles.

**Comment by gargath** [comment]
I think we have to be very clear about what we are proposing. I don't disagree with what you're saying. When the code gets compiled in makes little difference (although the use of Lua might tempt people to implement dynamic functionality like `haproxy`).
The real challenge I see is with the origin of that code.
If each provider is a separate library of some sort, maintained out-of-tree, then it is impossible to test for any negative interactions with other providers. This in turn I fear would open the door to unexpected security issues and just general flakiness.
Does that make sense?

**Comment by rabbers** [comment]
Well @gargath, I'd only considered the notion of a derived provider working atop the base implementation. Indeed my view is that there could be hundreds of differing providers, but the only interaction would be between the configured provider and the base implementation. So the question has to be, is there any potential for a single oauth2-proxy instance to be installed with multiple active providers at the same time?

**Comment by JoelSpeed** [comment]
So I think one of the main problems I have with the providers presently is the lack of testing they have. We have no idea if we are breaking the providers when we make changes. I think I would feel better about adding new providers if we had some sort of test suite for the providers that we could configure so that we can mock the providers.

I had considered suggesting a webhook integration for providers to allow people to build their own provider implementations and keep those outside of the main repository (though maybe within the org?), though again, as @gargath suggests, there are security concerns around this kind of integration.
