### ISSUE TITLE
How to use `-whitelist-domains` flag?

### ISSUE THREAD

**Issue by ghostsquad** [oauth2-proxy/oauth2-proxy#528]
This is a request for more documentation now how to use the `-whitelist-domains` flag in order to protect multiple domains. Specifically, the problem being that the value provided in `-redirect-url` must also be set in Okta, and if the subdomain is dynamic, you can't do wildcards or anything like that in Okta.

**Comment by ploxiln** [comment]
Just some bits that may help:

There are two different ideas of "redirect-url".
  * The oauth2-proxy setting "redirect-url" is the oauth callback url
  * the "whitelist-domains" applies to the redirect after that, to the upstream application url that was initially requested

You can have it so that the oauth-callback redirect-url is always to the same subdomain (a "primary" or "oauth" subdomain) and then the next-hop upstream-app-page redirect is allowed to be to any of your other subdomains (whitelisted).

**Comment by ghostsquad** [comment]
How do you configure the second redirect?

**Comment by ploxiln** [comment]
oauth2-proxy gets upstream-app-redirect value when you start the oauth process. It depends on whether you use direct-proxy mode, or nginx `auth_request` mode. In direct-proxy mode it's mostly automatic, in nginx-auth-request mode you can set the `X-Auth-Request-Redirect` header, see https://oauth2-proxy.github.io/oauth2-proxy/configuration#configuring-for-use-with-the-nginx-auth_request-directive

**Comment by ghostsquad** [comment]
Is there a known/vetted docker image of nginx that has the relevant LUA module?

**Comment by ploxiln** [comment]
You don't necessarily need lua to use nginx auth_request, I think lua is only needed if you get split cookies (due to huge provider auth tokens being included in cookies). That example has lots of possible stuff, your actual usage should be simpler.
