### ISSUE TITLE
ClientSecrets may be unintentionally interpreted as Base64

### ISSUE THREAD

**Issue by JoelSpeed** [oauth2-proxy/oauth2-proxy#547]
## Expected Behavior

A secret that is valid base64 but not 16, 24 or 32 characters in length should not be allowed by the proxy.

## Current Behavior

Some secrets are allowed because they appear to be base64 even though they aren't intended to be
So we end up with 13 character secrets instead of 16 for example because the base64 decoding is padding the value

## Possible Solution

Stop padding Base64 decoded values, they should only be decoded once

## Steps to Reproduce (for bugs)

1.  
2.  
3.  
4.  

## Your Environment

- Version used:

CC @NickMeves

**Comment by NickMeves** [comment]
Draft of this fix ontop of the sessions-utils PR here: https://github.com/grnhse/oauth2-proxy/pull/4

NOTE: Implementation slightly different than above, if a secret Base64s to 16,24,32 length []byte -- cool keep it.

Otherwise, return []byte(secret) that the user passed in. Don't want to confuse uses by telling them the 16 character secret string they put in a configuration isn't 16 characters (because unknown to them it base64 decoded opportunistically to 11 bytes).

**Comment by JoelSpeed** [comment]
Ack, that sounds right I think, thanks!

**Comment by JoelSpeed** [comment]
@NickMeves Would it be possible to get a PR for this based on current master or does it depend on the existing open PRs? We are trying to get release 6.0.0 out soon and this one is required for that, where the others aren't necessarily as far as I can tell

**Comment by NickMeves** [comment]
@JoelSpeed Its closely related to this minor organization refactor PR: https://github.com/oauth2-proxy/oauth2-proxy/pull/538

One of the main parts of #538 was eliminating the double identical implementation of `SecretBytes` -- were I to skip #538 - I think fixing that issue is still needed here, thoughts?

**Comment by JoelSpeed** [comment]
Ok, that makes sense, let's keep it as is and I'll add that to the project too
