### ISSUE TITLE
Different handling of UI paths and API paths on unauthorized requests

### ISSUE THREAD

**Issue by segfault16** [oauth2-proxy/oauth2-proxy#551]
I've seen https://github.com/oauth2-proxy/oauth2-proxy/issues/461 but I think this is worth discussing further.

If a SPA is open in the browser and the user manages to idle out or logs out of the auth provider (so access and/or refresh token are not valid anymore), a HTTP request to backend API of the application should result in a 403, so the SPA can handle (e.g. with a page refresh).

## Expected Behavior

- If Auth Cookie is deleted:
- API request returns 403

## Current Behavior

- If Auth Cookie is deleted:
- API request returns 302 with redirect to authorization endpoint of the auth provider

## Possible Solution

Like with the `skip_auth_regex` configuration a `skip_redirect_regex` (or some other possibly more meaningful `api_regex`) configuration can be added. If the request is not authorized and matches this regex, don't redirect to auth provider but return a 403 instead.

I'm happy to prepare a PR btw ;)

**Comment by JoelSpeed** [comment]
We already have some fix in for this kind of problem, are your requests to the backend AJAX?
https://github.com/oauth2-proxy/oauth2-proxy/blob/111d17efdecd4f716bc49b3ba8755ff2096d8c2c/oauthproxy.go#L851-L856

**Comment by segfault16** [comment]
Hi @JoelSpeed,
in my case backend requests are grpc.

**Comment by JoelSpeed** [comment]
I wonder if there is a better way that we can autodetect this rather than having explicit overrides as suggested. Eg, what if we detected XHR requests by the looking at the `X-Requested-With` header? Do you know if your SPA sets this when making the requests over GRPC?

**Comment by segfault16** [comment]
@JoelSpeed Thanks for your interest in the issue!

From what I can tell grpc-web adds the headers:

`X-Grpc-Web: 1`
`X-User-Agent: grpc-web-javascript/0.1`

but I didn't find a `X-Requested-With` header.

Maybe an option on oauth2-proxy to specify headers which identify API calls could be a flexible solution?

**Comment by JoelSpeed** [comment]
> Maybe an option on oauth2-proxy to specify headers which identify API calls could be a flexible solution?

That could be a good fix for now, though if there's a standard set that would allow us to identify requests, this could make it easier for users long term (otherwise everyone will have to configure that flag right?)

Out of interest, was there an `Accept` header? I wonder if there was a value in that that suggests it was a GRPC request 🤔

**Comment by segfault16** [comment]
In my case the request header says `Accept: application/grpc-web-text`

**Comment by JoelSpeed** [comment]
I'm leaning towards an option that allows users to identify the request headers, it may be quite difficult to enumerate a standard set

**Comment by segfault16** [comment]
Sounds good to me! The current implementation of the Accept header also isn't working in every case, e.g. if you do a simple `fetch("./something")` it's not `application/json` but `*` so you'd also get a redirect to Auth provider unless adding the encoding manually.

**Comment by segfault16** [comment]
@JoelSpeed Do you want to look into this or should I prepare a PR?

**Comment by JoelSpeed** [comment]
If you could prepare a PR that would be great!

**Comment by Bibob7** [comment]
What about always redirecting to auth provider but under certain conditions we set login flag `prompt=none` and skip provider button?
In this case the user will receive 403 only if he is not logged in anymore at the auth provider. So the expected behavior would be:

If Auth Cookie for App and Auth Provider is deleted:
API request returns 403

If Auth Cookie for App is deleted, but valid Auth Provider cooky exists.
API requests returns 200. (silent login)

I did something similar already in this PR: [#808](https://github.com/oauth2-proxy/oauth2-proxy/pull/808)
But I'm expecting to response application/json content. Maybe we can make this more dynamic.

**Comment by JoelSpeed** [comment]
> What about always redirecting to auth provider but under certain conditions we set login flag prompt=none and skip provider button?

What kind of conditions are you expecting here? At the moment this concerns me as it's making the proxy a little too clever, but not in a way that could be configured by users

**Comment by bard** [comment]
@JoelSpeed GraphQL clients are another bunch of offenders. They set `accept: */*` and requests and aren't caught by the check at: https://github.com/oauth2-proxy/oauth2-proxy/blob/111d17efdecd4f716bc49b3ba8755ff2096d8c2c/oauthproxy.go#L852

Would be great to be able to tell the proxy which routes to treat as API, a `--api-route="^(api/|graphql)"` would likely be enough for a lot of people.
