### ISSUE TITLE
Prometheus-metrics

### ISSUE THREAD

**Issue by jon88** [oauth2-proxy/oauth2-proxy#580]
If I am correct then currently no (prometheus) metrics are provided.

Was wondering what is the reason? Is there is any plan to implement them?

I know I would like to see some metrics about how many users are authenticated, how many redirected to 'login' page, for how many authentication fails etc

**Comment by JoelSpeed** [comment]
We currently don't have any metrics because no one has implemented them before, simple as that.

I'd happily have some metrics implemented and added to the proxy

Perhaps we could use this issue as a place to gather a list of metrics users would like to see?

One thing to make sure of, if we do implement this, is that we don't interfere with upstream servers by adding the metrics on a bad path, I assume Prometheus supports providing a path other than `/metrics` but I've never actually tried it

**Comment by kfox1111** [comment]
metrics around upstream connections (latency, failures, etc) and token handshaking failures would be most useful I think.

**Comment by gargath** [comment]
It might make sense to have a separate http server listen on a separate port just for metrics, like the `nginx-ingress-controller` does.
That would be the cleanest way to keep it out of the critical path for clients.

**Comment by jon88** [comment]
I agree with @gargath - haproxy has same logic with different stats port.

I thought that maybe it would be simplest to start with things that are already logged or even with a basic oauth_proxy_info metric. Eq add new configuration variables, starting/ stopping metrics httpListener and initially add the most basic metrics.

When this is completed then adding new metrics should be really straightforward and depends only on the complexity of the metric.

**Comment by JoelSpeed** [comment]
+1 To @gargath's suggestion, having it on a separate listener would definitely be cleanest.
One thing I would like to request however, is that we set it to be off by default. We shouldn't just be adding extra listeners to peoples applications so I think it's probably best if we have a `metrics-address` flag or something like that, that defaults to `0` which has a special casing of off, and otherwise would expect an address like `:8080` or `127.0.0.1:8080`, WDYT?

**Comment by metalmatze** [comment]
For an application, we run we already have ingress metrics and that's how we found that initially, our service was returning 5xx. However, it would be nice to get additional metrics from this proxy on its upstream health to be able to better troubleshoot.
A second internal webserver is what most projects these days do.

I'm happy to consult but also happy to add the metrics myself.

**Comment by JoelSpeed** [comment]
@metalmatze If you're happy to take a first stab at adding a metrics server as a secondary HTTP server on the proxy and some initial metrics, that would be greatly appreciated.

Do we get any metrics for free from the likes of the http package? I'm trying to think what would be useful for people? 

The upstream metrics that @kfox1111 has suggested sound good, I'm not sure how we would implement them though. Could maybe add a middleware between the upstream servemux and the reverse proxy that sets the metrics? Latency would be interesting, we would have to time how long the response takes to return (unless there's anything built in) 🤔

**Comment by metalmatze** [comment]
Yes, we can probably wrap the roundtripper [like this](https://github.com/openshift/telemeter/blob/master/pkg/http/client.go#L60:6) which makes it almost a transparent change to the user of that roundtripper.

**Comment by JoelSpeed** [comment]
That looks like it will be surprisingly easy! +1 for the transport wrapper

**Comment by jankatins** [comment]
I would still be really interested in this!

**Comment by JoelSpeed** [comment]
This is definitely something we should be including at some point.

To get started we could introduce a middleware that records some of the request/response details and makes those available.

**Comment by starkers** [comment]
I'm trying to free up some time to do this actually.. no promises but hopefully I can do something in aug

**Comment by neuralsandwich** [comment]
Is this the best issue to track progress on this? I'm looking into implementing metrics for this.

**Comment by JoelSpeed** [comment]
Yes I think this is the best one to track this. If you do take it up, thank you! This has been a long time coming but we've not found the time yet

**Comment by neuralsandwich** [comment]
Created a PR for some basic metrics #980

**Comment by NickMeves** [comment]
I think we should close this out and track new metrics use cases in new issues (so they can bubble to the top of our list).
