### ISSUE TITLE
Can not redirect when signout

### ISSUE THREAD

**Issue by K7cl** [oauth2-proxy/oauth2-proxy#595]
## Expected Behavior

 redirect the user to the authentication provider’s sign out page

## Current Behavior

just redirect to site home
<a href="/">Found</a>.

## Steps to Reproduce (for bugs)
in config file:
whitelist_domain = ".microsoftonline.com"

send request:
GET /oauth2/sign_out?rd=https%3A%2F%2Flogin%2Emicrosoftonline%2Ecom%2Fcommon%2Foauth2%2Flogout

## Context

It can clear the cookie but it do not redirect to the authentication provider’s sign out page.

## Your Environment

RHEL8.1 NGINX1.18.0

- Version used:
5.1.1

**Comment by JoelSpeed** [comment]
We don't currently support single sign out, so the `sign_out` is only meant to clear the cookie of our sessions.

You may be interested in the discussion in #506 

I think this is a feature we want to support, and I know there has been some discussion before about it, there was a workaround found at the time, but I'm not sure what it was right now, apologies.

**Comment by K7-Lenovo** [comment]
Thanks, the redirection does not work is a known issue?

**Comment by JoelSpeed** [comment]
It's known to the maintainers, let's keep this open as an issue to track it, hopefully we can come up with a solution or workaround at some point. I suspect it will end up being quite complex since sign out URLs aren't going to be consistent across providers

**Comment by K7cl** [comment]
OK, Thanks. Look forward to updates

**Comment by rkeshmir** [comment]
Is it possible to consider a configureable sign_out redirect url?
With current situation the micro-services and UI front-ends have to be aware of the sign_out URL of the authorisation provider which is not good.

**Comment by SeWieland** [comment]
I request to reopen this issue.
The [docs](https://oauth2-proxy.github.io/oauth2-proxy/docs/features/endpoints) state that the redirection works.

It does not - or am I missing something here?

**Comment by scaamanho** [comment]
Don't sure if this is correct but it works for me with a oidc provider, instead of call  `/oauth/sing_out?rd=...`  (this don't work for me) my workarround is, from my application call, to identity provider url to signout and use `/oauth/sing_out` as redirect uri.
eg: `https://keycloak.mydomain.com/auth/realms/oauth2proxy/protocol/openid-connect/logout?redirect_uri=https://app.mydomain.com/oauth2/sign_out`

In this way, first close the session in idp and then remove the cookie.

To be aware of multiple urls, allways a reverse proxy can be set in front of oauth2 proxy and keyckoak, and map path `/auth` to keyckoak server and `/` to your oauth2 server, even user oauth 2 proxy for it, but not sure how to do that, even if it was posible

**Comment by MNF** [comment]
@scaamanho , can you share some code snippet or ,if possible, repository fork that illustrates, how you implemented redirect?

**Comment by t7tran** [comment]
For future visitors, for redirect to work, the redirected URL domain has to be whitelisted. See `--whitelist-domain` option in the [docs](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview).
