### ISSUE TITLE
New Feature: Support Oauth2 token introspection as per rfc7662#section2.1

### ISSUE THREAD

**Issue by fllaca** [oauth2-proxy/oauth2-proxy#612]
## Expected Behavior

When calling the endpoint with directly an opaque (or not) access token, Oauth2Proxy should be able to validate the token. Using an `/introspect` endpoint it can fetch metadata from the context of the token and fill headers like X-Auth-Request-User. The mechanism is described at https://tools.ietf.org/html/rfc7662#section-2.1.

## Current Behavior
Only the cookie set by oauth2 proxy or JWT bearer tokens are accepted by Oauth2Proxy. Backend-to-backend communications that don't use JWT for access tokens (using the client-credentials flow) cannot be configured.

## Possible Solution

Add a `--token-instropection-url` and a `--skip-bearer-tokens` flags to be able to validate opaque access tokens. This would work in a similar way as `--skip-jwt-bearer-tokens`.

**Comment by JoelSpeed** [comment]
This makes sense to me, do you have any idea how it would be integrated yet?

**Comment by stefansedich** [comment]
This would be handy for us too, I am just thinking about how we can create a way to issue users with long lived "Access tokens" for APIs and this would make that task far easier.

**Comment by hakimsabery** [comment]
I am expecting the same behaviour

**Comment by ishchatul** [comment]
This is still extremely relevant please

**Comment by Bewalticus** [comment]
This feature is especially relevant for enterprise integration scenarios where a lot of communication is backend-to-backend and OIDC is used.
The introspection endpoint URL can be retrieved via ```.well-known/openid-configuration``` or ```.well-known/oauth-authorization-server``` metadata information.

**Comment by braunsonm** [comment]
Where does this fit in with the OIDC profile URL? Should both be called when using OIDC and discovered/provided by the user or should one be preferred? How would the claims be deconflicted?

Some questions regarding the implementation remain. As Joel said I think this would be an acceptable feature however there is nothing preventing the user from enriching their user by calling this introspection endpoint themselves as well (though ideally oauth2-proxy would do this for you). As marked help wanted for answering questions about how this should behave and for implementation.

**Comment by Bewalticus** [comment]
OAuth2-proxy supports the authorization code flow to allow end users to authenticate via browser. The client credential grant flow uses a bearer token for authentication. The use case is machine-2-machine communication, e.g. calling REST APIs. OAuth2-proxy can identify the Authorization header having a bearer token and then select the handling of the client credential grant flow instead of starting the authorization code flow as of now.
Oauth2-proxy then should call the token introspection endpoint to get information about the validity of the token and the logged in "user". The URI of the introspection endpoint can be retrieved from the OpenID configuration (property introspection_endpoint). As @fllaca said above there is RFC 7662 section 2.1 describing the usage of the endpoint.

There is no need to deconflict claims because there is no valid use case having both flows at the same time (in the same request) and AFAIK there is no specification describing the handling of such situation. Also there is no user session in the backend when using the client credential grant flow, however the authentication data can be cached to avoid excessive traffic on the introspection endpoint.

I would see Oauth2-proxy as a single point of authentication handling the OpenID authentication flows. It would not make much sense only to support one of the flows because often there is some mix of end users and backends especially if a REST API is exposed which is used by other machines and web clients at the same time. Otherwise the application need to handle it itself -- maybe by using some OpenID client library -- which would make usage of Oauth2-proxy obsolete.

PS: Our IAM setup requires 2 separate client IDs/client secrets for use of authorization code flow and for calling the introspection endpoint.

**Comment by braunsonm** [comment]
@gregrestivo you might be confused. OAuth Proxy does support tokens obtained through client credentials. This change involves introspecting the token in the event that the token is opaque (for claims) or prematurely revoked. (ie before expiry)

**Comment by gregrestivo** [comment]
@braunsonm Thanks for the clarification.  I didn't realize that the OAuth Proxy already supports bearer JWT tokens.  I found this article quite useful: https://medium.com/in-the-weeds/service-to-service-authentication-on-kubernetes-94dcb8216cdc

It looks like part of the request for this feature is to call the introspect endpoint to validate the bearer token.  How does it validate the JWT token today?  By checking it's expiry?

**Comment by JoelSpeed** [comment]
> How does it validate the JWT token today? By checking it's expiry?

Checking the signature and expiry as per standard JWT verification

**Comment by tuunit** [comment]
@rufreakde sorry for the long wait. We will try to get it into the next release.

**Comment by christophenoel** [comment]
Is it now supported through "flag: --validate-url : Access token validation endpoint" ?
Thanks

**Comment by jgongd** [comment]
@christophenoel I think setting `--validate-url` with the userinfo endpoint can validate a token.
