### ISSUE TITLE
type error while retrieving "email_verified" claim

### ISSUE THREAD

**Issue by iamfarsk** [oauth2-proxy/oauth2-proxy#629]
My OIDC provider returns "email_verified" claim as string due to which I am getting type error while retrieving "email_verified" claim during callback. OAuth2-Proxy has a strict type check for boolean value.

Can we allow string datatype for this claim and convert it to boolean?

- Version used: Latest

**Comment by JoelSpeed** [comment]
Hi @iamfarsk, could you confirm what your identity provider is? They are technically providing an out of spec token to you if the `email_verified` claim is a string rather than a boolean. I don't think there is really a workaround for this as if we change the field, the JSON marshaller would have problems unmarshalling  valid tokens which use the field as a boolean, as is in spec

**Comment by iamfarsk** [comment]
> Hi @iamfarsk, could you confirm what your identity provider is? They are technically providing an out of spec token to you if the `email_verified` claim is a string rather than a boolean. I don't think there is really a workaround for this as if we change the field, the JSON marshaller would have problems unmarshalling valid tokens which use the field as a boolean, as is in spec

**Comment by iamfarsk** [comment]
@JoelSpeed SecureAuth is my oidc provider. They are providing email_verified claim as string.

**Comment by JoelSpeed** [comment]
Perhaps you should approach them and see if they would be willing to change to make their implementation within spec? As described above, I don't think we would be able to support both implementations easily and I'd rather try to keep to supporting the specified implementation rather than a near spec implementation

**Comment by NickMeves** [comment]
Untested code incoming 😄 

If we switch the Verified field in the claims struct from a `*bool` to an `interface{}` -- would something like this potentially work?

```
if claims.Verified != nil  {
	var verified bool
	switch v := claims.Verified.(type) {
	case bool:
		verified = v
	case string:
		verified = v == "true"
	default:
		verified = false
	}
	if !verified {
		return nil, fmt.Errorf("email in id_token (%s) isn't verified", claims.Email)
	}
}
```

**Comment by JoelSpeed** [comment]
Maybe we should move the claim extraction over to the `simplejson` way of extraction, that way we could try both I guess, I'd rather we try and merge the claim extraction across providers first though, would be good to have 1 codepath for this extraction rather than 3/4/5...

**Comment by NickMeves** [comment]
Good thought -- maybe something in `apis/sessions/session_state.go` -- IE `NewSessionStateFromToken` to centralize all the logic in a meaningful place?

**Comment by JoelSpeed** [comment]
I was thinking something in pkg/authentication maybe? Something like `ExtractClaims` which would convert a token and maybe userinfo response (fallback?) Into the session

Might be worth having some discussion over design. I'm thinking maybe we try to get the claim from token, if that fails we fall back to requesting the userinfo and trying to extract it from there, but do so in a way that we cache the userinfo so we only fetch once per extraction and only fetch it if absolutely necessary, WDYT?
