### ISSUE TITLE
[FEATURE] support machine users by adding option to disable materialization of email address

### ISSUE THREAD

**Issue by PaulCharlton** [oauth2-proxy/oauth2-proxy#658]
The various identity providers available from Microsoft generally allow for several related categories of non-human users, none of which have an email address property. [Application Registrations, Service Principals, Delegated Applications, Managed Identities for Azure resources, etc]

The current Azure provider, and others, in the Oauth2-proxy attempt to render the email address from the various available tokens and endpoints.

The proposal here is to add a boolean config option which acts as a hard-stop to prevent any of the email related code paths from running, and/or prevent creation of http headers containing the email information.

PR forthcoming.

**Comment by PaulCharlton** [comment]
some upstream servers require an email address, in which case the oauth2-proxy could create a "dummy" email address for machine users based on various properties in the available tokens and id provider endpoints.

**Comment by JoelSpeed** [comment]
Are errors being thrown when trying to look up the emails? I'd rather we just try to look them up and not throw errors, just populate the email as an empty string. The header injectors should not be setting the header if the value in the session is empty.

I'm not a fan of the dummy email approach. We have plans to create a very flexible header injection method that would allow the customisation that would be need to construct the email headers but from other session claims, but I'm not sure when this will be implemented yet. We were discussing this in https://github.com/oauth2-proxy/oauth2-proxy/issues/631#issuecomment-649750682, do you think something like that may resolve that second issue?

**Comment by PaulCharlton** [comment]
Hey @JoelSpeed I like the header filter/injection in #631. 

1. The following code snippet from `azure.go` illustrates a performance issue I would rather have a config setting to control.   The code is always hitting the external ProfileURL endpoint (time sink) even when there's enough evidence in the AccessToken to avoid such inquiry.
2. if I know that my upstream servers do not need email headers, I would prefer not to spend the time in the auth server fetching it.

```
	if s.AccessToken == "" {
		return "", errors.New("missing access token")
	}
	req, err := http.NewRequestWithContext(ctx, "GET", p.ProfileURL.String(), nil)
	if err != nil {
		return "", err
	}
	req.Header = getAzureHeader(s.AccessToken)

	json, err := requests.Request(req)

	if err != nil {
		return "", err
	}
```

**Comment by PaulCharlton** [comment]
ps: I am available to create some code solutions, and I also see that there is already a lot of major refactoring in the works and I do not want to end up creating rework for those efforts.

**Comment by NickMeves** [comment]
I think I had a similar thought and played around with the potential of ditching forcing an email out of an IDToken when one wasn't present (currently logic makes `session.Email := claims.Subject` when `claims.Email` isn't present in bearer header auth). Which conflicts with the 1 universal authorization validator we have of `--email-domains`: https://github.com/oauth2-proxy/oauth2-proxy/pull/596

This commit: https://github.com/oauth2-proxy/oauth2-proxy/commit/1dd6ba559bb22f1f7fa35051772279f1cfc44a74

This discussion: https://github.com/oauth2-proxy/oauth2-proxy/pull/596#issuecomment-638346562

I use kubernetes projected service account tokens for service -> service authentication protected by oauth2-proxy using the `--skip-jwt-bearer-tokens` flag.  I just have to make sure I set `--email-domain=*` otherwise my kubernetes subjects forced into the email field in the session would never validate since they don't have an `@`.

**Comment by NickMeves** [comment]
In the end, I figured it wasn't a big deal to leave a duplicated subject in the `session.Email` field instead of forcing it to `""` -- both routes would've required `--email-domain=*`.

I think there's other areas that treat the session.Email as canonical too, upon a quick glance, some areas of the logger might be hardcoded to session.Email rather than using `GAP-Auth` which picks between User/Email appropriately.

**Comment by NickMeves** [comment]
Upon closer glance though -- this seems to be an Azure specific issue where potentially you can have machine users hitting most of the Azure provider flow? (rather than my situtation where I bypassed the Oauth flows with existing IDTokens and validated against OIDC well-known JWKS via bassing it via the bearer header)
