### ISSUE TITLE
unknown flag: --trusted-ip

### ISSUE THREAD

**Issue by ghostsquad** [oauth2-proxy/oauth2-proxy#704]
## Expected Behavior

documentation describes the flag `--trusted-ip` but that appears not to be a valid flag:
https://oauth2-proxy.github.io/oauth2-proxy/configuration

```
unknown flag: --trusted-ip
```

also

```
unknown flag: --trusted-ips
```

- Version used: v6.0.0

**Comment by JoelSpeed** [comment]
This is due to the fact that the hosted documentation reflects the state of the master branch. This feature was recently merged and will come in `v6.1.0` which I'm hoping to get out within the next week or so.

We have an issue open to track the fact the hosted docs are not for the current release already, see #550

**Comment by ghostsquad** [comment]
@JoelSpeed would it be possible to either keep the docs aligned with what _is_ released, or practice continuous delivery, such that master is released every time something is merged to it?
