### ISSUE TITLE
dot prepend to domain when cookieDomain is specified

### ISSUE THREAD

**Issue by mildis** [oauth2-proxy/oauth2-proxy#730]
> 

## Expected Behavior
When setting `cookie_domains = "myapp.example.com"`, cookie domain should be set to `myapp.example.com`

## Current Behavior
* With `cookie_domains` unset
** the following message is displayed in the log   
`[cookies.go:48] Warning: request host "myapp.example.com" did not match any of the specific cookie domains of
 ""`
** but the cookie domain as viewed from the browser is `myapp.example.com` (which is correct)  

* When setting `cookie_domains = "myapp.example.com"` and viewing cookie content in the browser, domain shows as `.myapp.example.com` (with a dot prepend)

Version used:
6.0.0

**Comment by JoelSpeed** [comment]
There's two issues at hand here, firstly that log line shouldn't really be doing that. I think we need to move this line down a couple of lines so that it only logs that message if `len(cookieDomains) >0`
https://github.com/oauth2-proxy/oauth2-proxy/blob/d7abd56981c72ab71baf5429e5eefc7406c9677f/pkg/cookies/cookies.go#L48

Secondly, the fact the dot is being prepended, I can't see where in the code that would happen at present, so we may need to do some debugging on this.

When you start the proxy, it should print out the domains that it thinks it's configured for, could you paste an example here that shows what it prints for your case?

**Comment by mildis** [comment]
@JoelSpeed Thanks for your feedback.  
My apologies, I'm confused : it looks like this is an intended behavior as per https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#Attributes

* If omitted, defaults to the host of the current document URL, not including subdomains.
* […] but if a domain is specified, then subdomains are always included.
