### ISSUE TITLE
go get github.com/oauth2-proxy/oauth2-proxy seem to install outdated version, maybe v3.2.0?

### ISSUE THREAD

**Issue by silcowitz** [oauth2-proxy/oauth2-proxy#740]
## Expected Behavior

the go get command should build the latest stable/secure release. (or at least I think so)

## Current Behavior

Running 

`GO111MODULE=on go get github.com/oauth2-proxy/oauth2-proxy`

builds an executable in /home/user/go/bin/oauth2-proxy that appears to be an outdated version. 

## Possible Solution

I'm not knowledgeable on the go build system, so I don't know.

## Steps to Reproduce (for bugs)

1. run GO111MODULE=on go get github.com/oauth2-proxy/oauth2-proxy 
2. Check if the output of /home/user/go/bin/oauth2-proxy --help  is as expected  (--version just says undefined)

## Context

I used the automated go get build process in a container, but the resulting executable doesn't behave like the docs describe. For instance, it doesn't have the --banner option as is described in the docs.  I also get the same behavior when running the go get command directly on my archlinux system.

## Your Environment
$ go version
go1.15 linux/amd64

$ uname -a
Linux archlinux 5.7.12-arch1-1 #1 SMP PREEMPT Fri, 31 Jul 2020 17:38:22 +0000 x86_64 GNU/Linux

$ lsb_release -a
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

**Comment by JoelSpeed** [comment]
So this seems to be related to https://github.com/golang/go/issues/35732

v3.2.0 is the latest version of our project that doesn't contain a go.mod file, so that is the last version that go.mod thinks is compatible with the import path `github.com/oauth2-proxy/oauth2-proxy`.

The solution to this is that we would have to rename the module every time we make a major release, so it would become `github.com/oauth2-proxy/oauth2-proxy/v6` for the current release.

There is no way for us to fix the current import path to be anything newer short of using some non go mod dependency management.

My suggestion would be that we remove the `go get` installation instructions and instead provide alternative/better instructions for people to build from source. I imagine this would look something like

```
git clone git@github.com:oauth2-proxy/oauth2-proxy
cd oauth2-proxy
git fetch --tags
git checkout v6.0.0
make build
mv oauth2-proxy $GOBIN
```

Does that help explain the problem at all?

Interested to know what other maintainers think of this issue (cc @oauth2-proxy/maintainers)

**Comment by silcowitz** [comment]
I'm not really sure what is the best solution here, but I can say that as somebody who just want to build/install oauth2-proxy and use it with the standard google account setup, I ended up trying to use the outdated version, while thinking I had the latest version.

So definitely, it's probably best to discourage the use of "go get" if it can't be ensured that it will build the latest release version.

**Comment by JoelSpeed** [comment]
Agreed. Let's keep this issue open as a reminder that we need to update the docs and discourage this
