### ISSUE TITLE
How to use oauth proxy to protect rest api with Bearer token

### ISSUE THREAD

**Issue by istvano** [oauth2-proxy/oauth2-proxy#755]
Hi,

I just found oauth-proxy and I would like to find out if it is the right tool for my problem.

I have an old legacy rest API that uses http headers to receive the authenticated user. Since we are moving away from CAS to Openid connect I am looking for a proxy that can help to implement the following.

1. The SPA will add a Bearer token to every request that is send to the API
2. I would like to add oauth2-proxy between the SPA -> API as a reverse proxy.
3. I would need Oauth proxy to extract the Access token that is sent by the SPA validate it against an openid connect provider
4. Extract the headers from the Bearer (Access) token and send them as http headers to the upstream.

Is this possible? I have tried this but oauth2-proxy wants me to authenticate every time except accepting the my access token.

What combinations of flag do I need to use for this use case?

Is this even possible?

Thanks!

## Your Environment

Kubernetes

- Version used:
6.1.1

**Comment by NickMeves** [comment]
https://oauth2-proxy.github.io/oauth2-proxy/configuration

You can use the `--skip-jwt-bearer-tokens` flag to consume bearer tokens to generate you session instead of needing a session from a cookie/redis (for humans).

By default it will use your provider details, but if you need extras, you can set `--extra-jwt-issuers` to set an arbitrary amount of additional providers.

I use those flags to setup architecture that need both human CLI tools to hit their rest APIs or server to server authentication with projected service account tokens from kubernetes.

**Comment by istvano** [comment]
Hi,

thanks for your answer! I was wondering how to switch it off the human version and force bearer token. Is that also possible?

**Comment by NickMeves** [comment]
In that case -- instead of using `--extra-jwt-issuers` you'd put your OIDC issuer + client for machine users directly into those OIDC provider main options (instead of a real human OIDC IdP).

For client secret & cookie secret - just put in dummy data since they won't be used (you won't have cookie session, everything will be via bearer headers)

**Comment by JoelSpeed** [comment]
There isn't a way to prevent our sign in mechanism being served, so if you can, I would recommend blocking access to the oauth2_proxy sign in path to prevent people even attempting this

**Comment by istvano** [comment]
Hi Guys,

Thanks for all the support! 

I am ok with people trying to access it on the other hand I would need to make sure of the following.

- user tries to call api.mydomain.com/search which is protected by oauth2-proxy to be forwarded to the iDP.
Instead of the redirect It needs to say 403 as the bearer token is missing. 

Do I also need to implement this on an other reverse proxy like an ingress ?

thanks again!

**Comment by NickMeves** [comment]
I don't think we have a way to prevent that nicely in the manner you mentioned.

SInce you only want to use bearer headers, the validation of IDTokens only uses the OIDC Issuer + Client ID. The Client Secret on the other hand is only used in the Oauth2 flow with the IdP.

So you could set that value to junk data that isn't valid with your IdP as a mitigation hack (I do this in my environments).

**Comment by istvano** [comment]
Hi,

thanks for that. I will try it out.

**Comment by NickMeves** [comment]
@JoelSpeed What are your thoughts -- I don't seem to be alone in using OAuth2-Proxy as a machine -> machine auth proxy via Bearer headers.  It seems to be a use case we get a lot of questions on.

Is it potentially worth tweaking the configs to make setting this up more standard at some point in the future?  At the moment it requires setting Dummy values for `cookie-secret` and `client-secret` when using `skip-jwt-bearer-tokens` with the OIDC provider.

**Comment by istvano** [comment]
Hi,

I think there is a common use-case which is the following.

- a client sends a request to an API with a bearer token. 

- oauth2 should validate the token using either the jwks_urls or introspect endpoint

- send the request to up-stream with the details from the bearer token details E.g. prefered username, roles etc.

This way legacy services can be protected by the proxy. This one with request signing can be secure enough in my opinion. 

I could not achieve this with oauth2 proxy as my legacy services do not understand JWTs they rely on old school http headers. (I am cas with openid connect)

There is no need for oauth2 to initiate a login as that is triggered by the SPA application and the SPA's responsibility is to send the bearer token and refresh it as well.

**Comment by JoelSpeed** [comment]
I could see supporting machine-to-machine only as a valid option for the proxy, how would you propose we implement this @NickMeves? Some way to disable auth by having no provider and associated options?

**Comment by miritsadon** [comment]
IF you look at the gatekeeper solution - it had an option to set bearer only - meaning without the redirection just the JWT validation .... is this possible? meaning if the request is received without the jwt or an invalid one it will fail the request and if the JWT is ok it will pass it as an authorization header to upstream?

**Comment by istvano** [comment]
Hi, 

Thanks for checking this. Can you put a link to that sample here so that others can find it if / when they need it?

**Comment by ftomassetti** [comment]
I also think this bearer only authentication mechanism (without attempting login) would be very useful
