### ISSUE TITLE
Suggestion: Include PKCE - Code Challenge in Proxy 

### ISSUE THREAD

**Issue by ImpThomasHein** [oauth2-proxy/oauth2-proxy#756]
## Expected Behavior

For security reasons It would be nice if the PKCE extension would be included in the proxy.
https://www.oauth.com/oauth2-servers/pkce/.

## Current Behavior

PKCE cannot be used for the authorization and callback request

## Possible Solution

It would be good if it could be enabled by a property.

**Comment by NickMeves** [comment]
Can you elaborate on the the architecture you are looking to get with PKSE included in OAuth2-Proxy so I can visualize the use case better?

For instance, I have client CLI tools that use OIDC + PKSE to get an IDToken.  Then I can consume that in the OAuth2-Proxy via the Bearer header with the `--skip-jwt-bearer-tokens` option set.

This sounds like your architecture is looking more for something server side directly?

**Comment by NickMeves** [comment]
> > client CLI tools that use OIDC + PKSE to get an IDToken
> 
> @NickMeves I have similar query. My use case is mobile (Android/iOS) and web SPA (static React app running at admin.domain.com) clients accessing a REST API (api.domain.com) with Keycloak as auth iDP provider (accounts.domain.com). Can I use oauth2-proxy to protect the REST API for such clients? I suppose I need to use the --skip-jwt-bearer-tokens flag. As OAuth 2.1 is recommending PKCE with code grant flow for mobile and SPA clients, I should then access the iDP directly with code grant flow + PKCE to obtain the access token, and then add the access token in header (Authorisation Bearer) to access the REST API endpoints exposed by oauth2-proxy?

This I'm not positive - maybe? If you can get the client side code to perform the PKSE flow, you can send the final IDToken (or Access Token, probably IdP specific) via the Bearer header with the options I mentioned.

For CLI tools, I have a client library my developers use that opens up a local webserver so it can get a callback on `http://localhost:<SOME_PORT>/callback` to finish the OIDC PKSE flow. Then they have an IDToken to ship off in the Bearer header.

> 
> In addition to the mobile and SPA clients, I also have a NodeJS/Express web frontend ([www.domain.com](http://www.domain.com)) running server side, which is accessing the same REST API. As this frontend is running server side, my guess there is less need for PKCE, and oauth2-proxy currently does not use PKCE to interact with iDP. Do I use a new instance of oauth2-proxy for the REST API for this frontend client? Or I can use the same instance of oauth2-proxy for the mobile/SPA clients?

Yeah, you can mix and match.  I have a use case coming up where a traditional POST OIDC flow is the main OIDC provider hooked into OAuth2-Proxy.

Then `extra-jwt-issuers` is set as well with a different OIDC PKCS provider to support the CLI tool access and another machine JWKS.json issuer for machine to machine access to the service as well.

**Comment by aberhallo** [comment]
@NickMeves
I'm struggling with the status/result of this suggestion since I use oauth2-proxy as a secure and simple solution to secure my apps (thanks for all the good work!).

But according to https://oauth.net/2.1/ "_PKCE is required for all OAuth clients using the authorization code flow_". That means also for confidential clients and not only for mobile and SPA clients as @etca2z stated before. So using PKCE is state of the art for me and I want to use PKCE. 

Enabling PKCE starts when sending the auth code request, which should look like this:

```
https://YOUR_DOMAIN/authorize?
    response_type=code&
    code_challenge=CODE_CHALLENGE&
    code_challenge_method=S256&
    client_id=YOUR_CLIENT_ID&
    redirect_uri=YOUR_CALLBACK_URL&
    scope=SCOPE&
    state=STATE
```
In contrast to the code flow without PKCE  a code_challenge has to be submitted. I think this is not done currently in the code, see https://github.com/oauth2-proxy/oauth2-proxy/blob/06808704a3762de73bed1cc92b077420eb93d735/providers/util.go#L38

To follow the 2.1 spec regarding PKCE I think oauth2-proxy should handle the PKCE flow.

PS:  since I can see different abbreviations here: I'm talking about PKCE - Proof Key for Code Exchange, see https://auth0.com/docs/flows/authorization-code-flow-with-proof-key-for-code-exchange-pkce. It's not related to PKCS or PKSE (?) in this context.

I would be very happy to hear from you (even if the suggestion is already closed) :-)

**Comment by aberhallo** [comment]
@NickMeves will I get an answer here or should I open a new suggestion :-) ?

**Comment by MNF** [comment]
@aberhallo, in general it’s better to create a new issue, than ask extra questions on closed thread.
