### ISSUE TITLE
Keycloak provider can not signout

### ISSUE THREAD

**Issue by wenerme** [oauth2-proxy/oauth2-proxy#765]
## Expected Behavior

/oauth2/sign_out should logout kc too

## Current Behavior

after /oauth2/sign_out will login immediately

## Possible Solution

logout like [louketo](https://github.com/louketo/louketo-proxy/blob/master/docs/user-guide.md#logout-endpoint)

## Steps to Reproduce (for bugs)

1.  use keycloak provider
2.  login and remember
3.  go to /oauth2/sign_out 

## Your Environment

- Version used: latest

**Comment by JoelSpeed** [comment]
We don't fully support single sign out in this way, though some users have managed to work around this in the past.

You need to set up your redirects so that you hit the log out endpoint of keycloak and have that redirect to the log out endpoint of OAuth2 Proxy (or vice versa) before redirecting back to your home page. 

This was added to the docs as part of #443 so please review the documentation for how to do this.
