### ISSUE TITLE
Rejecting invalid redirect "/some_route/?param=https://host.com/route": not an absolute or relative URL

### ISSUE THREAD

**Issue by RodrigoTHD** [oauth2-proxy/oauth2-proxy#786]
I need to use a `sub URL as a query value` to open the application, but after login, the `redirect URL is rejected`.

## Expected Behavior

After login, It should redirect using the initial state with `/route/?param=https://sub-host.com/sub-route|12345`.

## Current Behavior

After login, it will redirect using a empty URL `/`, without route and query parameters.

```cmd
[2020/09/18 21:08:37] [logger.go:490] Rejecting invalid redirect "/route/?param=https://sub-host.com/sub-route|12345": not an absolute or relative URL

172.24.0.11:44724 - some-email [2020/09/18 21:08:37] [AuthSuccess] Authenticated via OAuth2: Session{email:some-email user:some-user-information PreferredUsername: token:true id_token:true created:2020-09-18 21:08:37.631345859 +0000 UTC m=+25369.033558287 expires:2020-09-19 21:08:36.628715855 +0000 UTC m=+111768.030928183}

172.24.0.11:44724 - - [2020/09/18 21:08:37] domain GET - "/oauth2/callback?
```

But, it was authenticated, the cookie was created. Trying to open the app again, it will work.

## Possible Solution

Maybe this line can give you some clue about the problem: [oauthproxy.go#L802](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/oauthproxy.go#L802)

## Steps to Reproduce (for bugs)

1.  open the application using the URL: https://some-host.com/route/?param=https://sub-host.com/sub-route|12345
2.  Log in to the application;. I'm using: Core OS Dex.
3.  After login, it will redirect using a empty URL `/`, without route and query.
4.  I can see in the logs the message: `[2020/09/18 21:08:37] [logger.go:490] Rejecting invalid redirect "/route/?param=https://sub-host.com/sub-route|12345": not an absolute or relative URL`.

## Your Environment

 I'm using the provider [OpenID Connect Provider](https://oauth2-proxy.github.io/oauth2-proxy/auth-configuration#openid-connect-provider).

### Environment variables

 OAUTH2_PROXY_EMAIL_DOMAINS='*' \
 OAUTH2_PROXY_COOKIE_NAME='session_name' \
 OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:8080 \
 OAUTH2_PROXY_PROVIDER=oidc \
 OAUTH2_PROXY_SCOPE='openid email' \
 OAUTH2_PROXY_SKIP_PROVIDER_BUTTON='true' \
 OAUTH2_PROXY_UPSTREAMS='http://frontend.apps.internal:8080/' \
 OAUTH2_PROXY_WHITELIST_DOMAIN='.'

## Version used: 
- 6.1.1

**Comment by JoelSpeed** [comment]
Are you using the OAuth2 Proxy to directly proxy your application or are you using some external service like nginx and it's auth request module? 

I think that redirect should be valid though I'm a bit concerned about the `|` character that is in there, I wonder if that may be interpreted by browsers in a weird way that could lead to open redirects 🤔

**Comment by ScottGuymer** [comment]
Oauth2 is being used to directly proxy the application, nginx is only used as a basic upstream static file server.

I think that one of the issues here is that in #696 there was a change from using `req.URL.Path` which would have only grabbed the absolute path to `req.URL.RequestURI()` which will grab the path and query string (which is what we want) but will give back a fully qualified URL with protocol and domain included.

This seems to trigger the domain whitelist protection for redirects which means we needed to specify a `,` in the `OAUTH2_PROXY_WHITELIST_DOMAIN` to get it to redirect at all. But i think that it was still failing on seeing another domain in the URL.

If we encode the query string before staring the auth request. So that it is double encoded when pushed into state and still encoded when getting to the whitelist check it seems to redirect as expected.

It seems to be something to do with seeing 2 protocol schemes in the url (one at the start and one in the query string)

**Comment by RaymondPhilips** [comment]
I suspect it gets triggered at line [oauthproxy.go:552](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/oauthproxy.go#L552) by the `invalidRedirectRegex` which checks for `//` somewhere in the redirect string, which in this case will find the `//` in the query param rather than in the URL path.
Checking the URL path check for `//` is essentially already covered by the `strings.HasPrefix(redirect, "//")`.
I'm not 100% sure on what the regex is trying to protect against, but it feels like a 'start of string' indication is missing, and that the regex should be `^[/\\](?:[\s\v]*|\.{1,2})[/\\]`

**Comment by ScottGuymer** [comment]
Im looking at fixing this in a PR.

I can see the source of this in in https://github.com/oauth2-proxy/oauth2-proxy/blob/master/oauthproxy.go#L804 where it is checking the validity of the URL returned in the state from the IdP. The function `IsValidRedirect` needs to be able to handle this scheme of redirect. Im adding some test cases to the tests for that to see if this is the issue.

**Comment by RaymondPhilips** [comment]
A pull request with a possible fix is available for this issue. Is there anything blocking the completion of this issue?
We are being hampered by this defect.

**Comment by JoelSpeed** [comment]
A couple of [comments](https://github.com/oauth2-proxy/oauth2-proxy/pull/790#discussion_r531189040) were added to the issue yesterday. We are trying to make sure that this isn't going to re-introduce some previous security exploits, hence the delay.

**Comment by ScottGuymer** [comment]
#keepopen

**Comment by nikolayrk** [comment]
Could this be re-activated? I ran into this issue when using oauth2-proxy with Google as the Idp. Google formats its OAuth scopes in the form of a URL (e.g `https://www.googleapis.com/auth/gmail.readonly` is the scope for read-only Gmail access), which results in the error enclosed below.

```
[2023/05/08 13:51:34] [validator.go:63] Rejecting invalid redirect "/oauth2/callback?state=[redacted]&code=[redacted]&scope=https://www.googleapis.com/auth/gmail.readonly": not an absolute or relative URL
```

I tried to set the `--scope` parameter to the URL-encoded value of the scope, but that got rejected by Google as an unrecognized scope. Removing the `--scope` parameter altogether fixes the error, but I need access to that scope.

**Comment by evozniak** [comment]
@JoelSpeed There are a lot of security concerns on this redirect, but there are legit use cases for it.
What do you think of adding a new option `--allow-insecure-redirects`
We can set the invalidRegex based on that flag, and we can add a big disclaimer in the documentation just like all insecure options.

Grabbing one solution from https://github.com/oauth2-proxy/oauth2-proxy/pull/790

[Validator.go L16](https://github.com/oauth2-proxy/oauth2-proxy/blob/d9416c3630d4b888441425691b57f01dab64bda8/pkg/app/redirect/validator.go#L16C24-L16C24)
E.g.
```
if !allowInsecureRedirects {
  invalidRedirectRegex = regexp.MustCompile(`[/\\](?:[\s\v]*|\.{1,2})[/\\]`)
} else {
  invalidRedirectRegex = regexp.MustCompile(`^[/\\](?:[\s\v]*|\.{1,2})[/\\]`)
}
```
