### ISSUE TITLE
Refreshing old session cookie with every request to /oauth2/auth endpoint

### ISSUE THREAD

**Issue by phidlipus** [oauth2-proxy/oauth2-proxy#793]
## Expected Behavior

If cookie-expire is setted to long period (1 week) and cookie-refresh to 1 hour (because Google's JWT is valid 1 hour), oauth2-proxy should refresh session cookie earliest after first hour and if successfully recieve access token (JWT) oauth2-proxy should do next cookie refresh earliest after one hour (and so on, until the session cookie expire or OAuth provider refuse to renew user's authentication). Cookie-refresh should be the minimal time from one succesfull cookie refresh (JWT gain) to the next.

## Current Behavior

After the first cookie-refresh (after the first hour) oauth2-proxy is refreshing session cookie with every request to `/oauth2/auth` endpoint.
```
[2020/09/24 07:36:25] [logger.go:490] Refreshing 16h55m6.351034896s old session cookie for Session{email:my.name@domain.tld user:1234567890 PreferredUsername: token:true id_token:true created:2020-09-23 14:41:18.648965104 +0000 UTC expires:2020-09-24 08:36:05 +0000 UTC refresh_token:true} (refresh after 1h0m0s)
[2020/09/24 07:36:25] [logger.go:490] 200 GET https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=xyzxyzxyzxyzxyzxyzxyz... {
  "issued_to": "1234567890-abcdef.apps.googleusercontent.com",
  "audience": "1234567890-abcdef.apps.googleusercontent.com",
  "user_id": "1234567890",
  "scope": "https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email openid",
  "expires_in": 3580,
  "email": "my.name@domain.tld",
  "verified_email": true,
  "access_type": "offline"
}

192.168.1.5 - my.name@domain.tld [2020/09/24 07:36:25] oauth2-proxy.domain.tld GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Bla Bla Bla) AppleWebKit/123.45 (KHTML, like Turtle) Chrome/1.2.3.4.5 Safari/123.4" 202 0 0.030
```

## Possible Solution

Some kind of timer? Or timestamp of last successfull cookie refresh.

## Steps to Reproduce (for bugs)

1. run oauth2-proxy with these args (e.g. in Kubernetes in our case)
```
      - args:
        - --provider=google
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --whitelist-domain=.domain.tld
        - --cookie-domain=.domain.tld
        - --set-authorization-header=true
        - --redirect-url=https://oauth2-proxy.domain.tld/oauth2/callback
        - --cookie-refresh=1h
        - --cookie-expire=168h
        - --cookie-secure=true
        - --session-store-type=redis
        - --redis-connection-url=redis://127.0.0.1:6379
        - --silence-ping-logging
        - --reverse-proxy=true
```
2. use options for sign in and auth validation for application in ingress object
```
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: https://oauth2-proxy.domain.tld/oauth2/start?rd=https://$host$request_uri$is_args$args
    nginx.ingress.kubernetes.io/auth-url: https://oauth2-proxy.domain.tld/oauth2/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $token $upstream_http_authorization;
      proxy_set_header Authorization $token;
```
3.  check oauth2-proxy logs, and after first hour of session cookie validity oauth2-proxy starts to refresh session cookie with every request to `/oauth2/auth` endpoint (visit application or directly https://oauth2-proxy.domain.tld/oauth2/auth).

## Context

We are using oauth2-proxy for authentication in Kubernetes Dashboard.

## Your Environment

- Version used: 6.1.1
- OAuth provider: Google

**Comment by JoelSpeed** [comment]
So I know this works correctly for the OIDC provider which resets `createdAt` every time it refreshes the token successfully, I believe that all of the providers should be doing this, but at present, I can see that at least the Google provider isn't.

If someone has the time, could they sift through the providers and ensure that all the ones that support refreshing set the `createdAt` appropriately to `time.Now()` if the refresh is successful

**Comment by carabj** [comment]
Suggest to base this in the standard claim "expires_in" returned from the token endpoint when access token and refresh token is received.
That is according to OAuth2 standard and tells how long time the access token is valid.
And is logical to base any refresh using refresh token when this time is soon to be passed.

**Comment by mindw** [comment]
kicking bot.

**Comment by peppered** [comment]
Before I try to elaborate on this issue let my provide my setup highlights:

1. I use Istio 1.7.4, oauth2-proxy 6.1.1 and Azure Active Directory
2. oauth2-proxy is configured with:

```
--cookie-samesite=lax
--cookie-refresh=50m
--cookie-expire=168h
--cookie-name=_auth
--email-domain=*
--http-address=0.0.0.0:8081
--oidc-issuer-url=https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/v2.0
--provider=oidc
--scope="openid profile offline_access"
--user-id-claim=oid
--errors-to-info-log
--set-authorization-header
--upstream=static://200
```

From my understanding this behavior may be explained by two reasons (I faced both of them):

1. If you use oauth2-proxy ( `/oauth/auth` endpoint) as external authorization service (i.e. with Nginx `auth_request` or Envoy/Istio  `ext_authz`) then this problem might be due to the  `set-cookie` headers with refreshed tokens that are not propagated to initial client response. In my case all AJAX requests didn't receive this headers and was sending the old `cookie` header until the page is not refreshed (and the newest `set-cookie` received). If you use Istio too, then that may help: [https://github.com/envoyproxy/envoy/issues/7986#issuecomment-748673696](https://github.com/envoyproxy/envoy/issues/7986#issuecomment-748673696).
2. Another problem — tokens are not refreshed actually despite the log messages (@JoelSpeed is it a bug?). There is the following flow in `stored_session.go` : `loadSession()` —> `getValidatedSession()` —> `refreshSessionIfNeeded()`. The latter function checks if the session has to be refreshed [based on the session age and the refresh period](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/middleware/stored_session.go#L116) (`--cookie-refresh` argument). And it's time to refresh then it calls `refreshSessionWithProvider()` —> `refreshSessionWithProviderIfNeeded()`. The latter function is implemented by providers. In case of `oidc.go` provider there is a method `RefreshSessionIfNeeded()` which again checks if the session has to be refreshed, but it does it in different way — by [testing the session/token expiration time](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/providers/oidc.go#L77). So OIDC provider's refresh method ignores the actual refresh period. And if you try to refresh token that is not expired, then nothing will happen — OIDC provider's refresh method return `false` and you just get a log message `Refreshing <AGE> old session cookie...`  mentioned in the issue description.

For my purposes I just removed `(s.ExpiresOn != nil && s.ExpiresOn.After(time.Now()))` from OIDC provider's refresh method and everything became normal. I also checked that provider's `RefreshSessionIfNeeded()` is used only by `stored_session.go` (and tests). So I'm wondering doesn't it really make sense keeping `IfNeeded()` logic within the provider? Because in that case this logic is actually spread across two layers (stored session and provider). I think it would be nice to move all "decision making" logic into single layer (stored session).

**Comment by JoelSpeed** [comment]
> In my case all AJAX requests didn't receive this headers

What I've seen in the past is that a lot of ajax requests will fire off simultaneously and all try to refresh at once, the first will referesh and return a set-cookie header, but subsequent requests fail and end up clearing the cookie. We implemented a caching layer for the `/oauth2/auth` endpoint in NGINX so that requests were cached for a very short period and only one request would go through at a time, is this something you might be able to try? We did consider trying to move this refresh locking into the project but there's a lot of complexity around this so haven't done so yet

> Another problem — tokens are not refreshed actually despite the log messages (@JoelSpeed is it a bug?). 

There's a lot of issues in this area and yes, definitely some bugs! We did have some work in flight to rework the session refreshing but I can't find it right now, perhaps @NickMeves knows more as I think he was collaborating on this

**Comment by Zocker1999NET** [comment]
> @JoelSpeed We implemented a caching layer for the `/oauth2/auth` endpoint in NGINX
Can you publish a config example of the caching layer, at least for nginx? I'm currently facing the same issue (at least I think so) with Kibana behind oauth2-proxy and its breaking parts of the dashboards (as they trigger a lot of simultaneous requests). I'm not sure how to implement the cache in a secure way (e.g. that nginx does not apply the same cached request across multiple users).

Also, I think this should be put to the docs as it may stops users from using oauth2-proxy.

**Comment by JoelSpeed** [comment]
For the ingress version I think you can just `nginx.ingress.kubernetes.io/auth-cache-key: $remote_user$http_authorization` and it should work, else perhaps [this gist](https://gist.github.com/JoelSpeed/9f4dbf6f79f6498d12ccd6ff0bc096e2) can help
