### ISSUE TITLE
Service to service authentication - forward signing proxy

### ISSUE THREAD

**Issue by p53** [oauth2-proxy/oauth2-proxy#810]
## Expected Behavior

https://github.com/louketo/louketo-proxy/blob/master/docs/user-guide.md#forward-signing-proxy

## Current Behavior

doesn't provide this feature

## Steps to Reproduce (for bugs)

1.  
2.  
3.  
4.  

## Your Environment

- Version used:

**Comment by JoelSpeed** [comment]
This isn't something we had ever intended to support up to this point. Could you possibly estimate what this would look like for the proxy and how it would integrate?

**Comment by NickMeves** [comment]
I agree - this doesn't belong in `oauth2-proxy`, this is better served as its own lightweight project if it were to ever be developed.

Jotting down some thoughts of what I would expect since the amount of service-to-service architecture design questions we are getting recently is really ramping up. My perspective behind these ideas is it would be completely OIDC based.

- The forward proxy would be OIDC compliant and sign and inject in its own IDToken into the `Authorization: Bearer` header
- The public/private signing keys would be configuration options.  As well as the Issuer URL + Audience name.
- It would host the `.well-known` endpoint with `openid-configuration` and `jwks.json`.  `openid-configuration` would look like this that AWS EKS uses for IRSA: https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/SELF_HOSTED_SETUP.md#create-the-oidc-discovery-and-keys-documents
- `sub` claim could be global config option or based on basic auth that provides username/password protections.

**Comment by NickMeves** [comment]
I think service to service cases like this are better facilitated by the IaaS layer, like using Kubernetes in this manner for AWS EKS IRSA: https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/SELF_HOSTED_SETUP.md

But a tool like this always comes up to support external code where you don't have the ability to support custom service to service auth credentials like you do with your own code.

This comes to mind as I'm thinking of Kafka auth for instance with OAUTHBEARER -- but all the clients might not be ready to support that (I need to dig into if Debezium can support it). If a client can't support it, something like this fits in nicely in the middle to bridge the gap.

**Comment by p53** [comment]
1. but outbound requests are not automatically signed even when you use kubernetes token, you have to modify your app to send token
2. in case you have VM/Mesos/other orchestration kubernetes is not an option
3. there is project https://github.com/grepplabs/kafka-proxy and i wrote oidc plugin for exactly this use case
