### ISSUE TITLE
How to avoid getting "csrf failed"?

### ISSUE THREAD

**Issue by holyjak** [oauth2-proxy/oauth2-proxy#817]
Regularly, I cannot complete log in due to

> 403 Permission Denied
>
> csrf failed

I believe it happens after a new version of the service and thus also oauth proxy has been deployed. It normally helps to delete the CSRF cookie but that is inaccessible to normal, non-technical end-users.

## Expected Behavior

Users should not be exposed to the error unless they are trying to hack the system.

## Current Behavior

I get the csfr error for no good reason. I believe that it persists even when I sign in anew.

## Possible Solution

I guess we want to keep the CSRF cookie for security reasons. I see e.g. two options:

1. When this error happens, the server should automatically delete/overwrite the cookie so that a second sign in will succeed
2. Even better, the server would know when it was started and ignore the cookie if it was created before that

## Steps to Reproduce (for bugs)

I am not sure how to reproduce. I *believe* it is caused by restarts of oauth proxy (ie. deploys of new instances). Sometimes I do not get the CSRF cookie, sometimes I do, I do not know the logic behind that.

## Your Environment

- Version used: 6.0.0

**Comment by JoelSpeed** [comment]
It was my understanding that if this happens, the CSRF cookie should be cleared automatically and there should be a button on the page to re-start the login process, are you not seeing this?

**Comment by dippynark** [comment]
I am seeing something similar when using oauth2-proxy as an [external authorization](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter) endpoint for Envoy as described [here](https://www.blog.jetstack.io/blog/istio-oidc/) -- the button is returned but just the HTML (as it's being proxied through Envoy). Most of the time when the cookie expires the user is redirected as expected, so not too sure why occasionally this is happening.

I guess this use case isn't officially supported (it just happens to work), but an option to invalidate the cookie and trigger another login if the CSRF check fails seems like it'd fix this.

**Comment by dippynark** [comment]
Taking a quick look at the code, the initial CSRF cookie is set based on the config https://github.com/oauth2-proxy/oauth2-proxy/blob/c377466411f2aee180a732187edb638f2f7e57fb/oauthproxy.go#L460 but when the cookie is reset it's hardcoded to an hour https://github.com/oauth2-proxy/oauth2-proxy/blob/c377466411f2aee180a732187edb638f2f7e57fb/oauthproxy.go#L455 maybe changing this to always set the cookie to the duration from the config would make sure the CSRF cookie doesn't expire before the session cookie.

Maybe there's a good reason to do this as it also happens in other places https://github.com/oauth2-proxy/oauth2-proxy/blob/c377466411f2aee180a732187edb638f2f7e57fb/pkg/sessions/persistence/ticket.go#L168 https://github.com/oauth2-proxy/oauth2-proxy/blob/c377466411f2aee180a732187edb638f2f7e57fb/pkg/sessions/cookie/session_store.go#L78

**Comment by dippynark** [comment]
Having a quick look at the code, I think replacing the error page https://github.com/oauth2-proxy/oauth2-proxy/blob/c377466411f2aee180a732187edb638f2f7e57fb/oauthproxy.go#L904 with the signin https://github.com/oauth2-proxy/oauth2-proxy/blob/c377466411f2aee180a732187edb638f2f7e57fb/oauthproxy.go#L766
or having an option to do this, would fix this

**Comment by chlasch** [comment]
Experiencing this same issue too, only after a complete reset of my browser (chrome). Does not occur on Safari, oddly enough.

**Comment by JoelSpeed** [comment]
Normally when I've seen this issue, it's because people have multiple tabs open at once which all start the login process simultaneously. 

I have several concerns about automatically redirecting to the sign in page when there's a CSRF failure:
- If there's a genuine CSRF attack, would this mask it?
- If the problem is multiple tabs, do we not end up in a redirect loop with each tab constantly creating new CSRF tokens?
- I think this would certainly want to be opt-in if we were to accept the change

I think longer term, the solution might be to come up with a way that we can have unique CSRF protection per auth flow rather than having the single cookie that can cause issues when you have multiple logins at once

**Comment by chlasch** [comment]
> Normally when I've seen this issue, it's because people have multiple tabs open at once which all start the login process simultaneously.
> 
> I have several concerns about automatically redirecting to the sign in page when there's a CSRF failure:
> 
>     * If there's a genuine CSRF attack, would this mask it?
> 
>     * If the problem is multiple tabs, do we not end up in a redirect loop with each tab constantly creating new CSRF tokens?
> 
>     * I think this would certainly want to be opt-in if we were to accept the change
> 
> 
> I think longer term, the solution might be to come up with a way that we can have unique CSRF protection per auth flow rather than having the single cookie that can cause issues when you have multiple logins at once

I can reproduce this 100% of the time, by clearing all data in Chrome, and then attempting to login. It will result in a CSRF error page every single time, with the CSRF cookie being cleared, and the sign in option working, setting a new CSRF cookie that apparently is valid.

**Comment by JoelSpeed** [comment]
> I can reproduce this 100% of the time, by clearing all data in Chrome, and then attempting to login. It will result in a CSRF error page every single time, with the CSRF cookie being cleared, and the sign in option working, setting a new CSRF cookie that apparently is valid.

That is... strange. Have you tried using one of the local testing environments that we have and seeing if you can reproduce the error with that? From the repo root if you have docker, you can run `make local-env-up` to get a test environment, source is all in `contrib/local-environment`, instructions in the docker compose files.

I just tried what you said with the local env and was unable to reproduce this

**Comment by chlasch** [comment]
> > I can reproduce this 100% of the time, by clearing all data in Chrome, and then attempting to login. It will result in a CSRF error page every single time, with the CSRF cookie being cleared, and the sign in option working, setting a new CSRF cookie that apparently is valid.
> 
> That is... strange. Have you tried using one of the local testing environments that we have and seeing if you can reproduce the error with that? From the repo root if you have docker, you can run `make local-env-up` to get a test environment, source is all in `contrib/local-environment`, instructions in the docker compose files.
> 
> I just tried what you said with the local env and was unable to reproduce this

That's a really nice local env setup you folk have, very helpful. Turns out that due to poor design on my part, my app was doing an ajax call that was causing the CSRF cookie to be reset, and invalidating the state on the browser redirect to `/oauth2/start`.

Oauth2-proxy is working as intended from what I can tell. @holyjak, have you investigated your browser logs to make sure that there aren't any phantom requests invalidating the state?

**Comment by d-theus** [comment]
I'm struggling with this issue as well.
To reproduce:
- open a new incognito window
- open 2 or more tabs with proxied resource, get redirected to provider's login page (OIDC in my case)
- sign in on a auth provider login page
- get 403 from oauth-proxy complaining about invalid CSRF token on a first tab (100% of the time)

This behavior is ... expected I guess (csrf-cookie gets overwritten with each new tab).

In case you are wondering why would I open many tabs: open several tabs during workday, close laptop, return to work the next day. To make things worse, protected resource's web page makes a lot of ajax requests, which are also being intercepted by proxy. 

So, my question is: can I do something to mitigate this issue?

**Comment by JoelSpeed** [comment]
I'm not sure there's anything we can necessarily do as a workaround for this via configuration, but, a thought I had was about naming the CSRF tokens with some sort of nonce that we can transfer around via the state parameter. This would allow a 1:1 of CSRF cookie to request session. Not entirely sure if there are additional security concerns involved in this though so will try to sync up with @NickMeves on this.

Going to reopen as this is an ongoing issue

**Comment by d-theus** [comment]
Just checked what Rails does as it's okay with form submission with several tabs.
Turns out, this is due to the fact they don't reset session between tabs (for an obvious reason) and this (encrypted) session contains csrf-token counterpart.
https://stackoverflow.com/questions/47723379/why-does-the-csrf-token-in-rails-not-prevent-multiple-tabs-from-working-properly

**Comment by rishi1111** [comment]
![image](https://user-images.githubusercontent.com/17124299/128808979-5fd912a0-1525-4003-831d-40b375b7b62e.png)

I see one case where I get this issue intermittently is if there are multiple calls to fetch js, css files and all of them return a redirect 302 response. In this case the cookie gets overwritten resulting in 403 forbidden.

**Comment by Frizlab** [comment]
Same here, using an app I have no control over. Would love to see this fixed 🙂 For the time being I have whitelisted (too much) files based on path extension…

**Comment by PSanetra** [comment]
We experienced this error when we set `cookie_samesite` to `strict` as strict samesite cookies are not send on navigation from third party websites.

**Comment by Frizlab** [comment]
@PSanetra I have the issue even with `cookie_samesite` set to `lax`

**Comment by hanaws-1** [comment]
I'm also seeing the 403 issue and have tracked it down -as for e.g. @rishi1111 - to multiple concurrent requests to JS resources that get redirected to /auth, each overwriting the CSRF cookie of the previous one.

I'm asking myself why a request for a JS or CSS resource should be redirected to /auth at all. 

To my mind, it would make more sense to handle them like XHR requests, returning 40x instead of the 302 redirect.

Which brings me to the question: Would it make sense to make the "XHR"-recognition more flexible that just "anything that accepts `application/json`"?

Apart from this, @JoelSpeed 's suggestion in https://github.com/oauth2-proxy/oauth2-proxy/issues/817#issuecomment-864535566 would certainly solve this problem.

**Comment by blankburian** [comment]
When there is a large number of background script requests, the header size may grow too large, when too many cookies with different nonce are set. This would result in http error 431, also see here, where the problem is solved similarly: https://github.com/thomseddon/traefik-forward-auth/issues/238

**Comment by JoelSpeed** [comment]
> Which brings me to the question: Would it make sense to make the "XHR"-recognition more flexible than just "anything that accepts application/json"?

We have discussed this idea in the past, but it never really got anywhere. If you have time to do some investigation and work out a good way to make this detection work, I think we can add this as a feature for sure

> When there is a large number of background script requests, the header size may grow too large, when too many cookies with different nonce are set.

This is a really good point that suggests to me that we don't want a per request CSRF. If we wen't down this route we would have to seriously limit the number of incoming requests from the same client at once. Not impossible but would be challenging for either us or our users

**Comment by ace130-github** [comment]
Thanks for your quick reply.

As for the more flexible XHR recognition: My idea would be to let the user specify a path pattern of requests that are to be treated just like the 'application/json' requests (ie are answered with a 40x instead of a redirect to the login page). 

The user would configure this in a way that the static resources their front-end framework requests at runtime (js, xml, and so on) would be handled just like the application/json resources. It would be the frontend application's responsibility to recognize the 40x responses and make the application navigate to the login screen. This should already be in place today for those requests that are already recognized as XHR.

Provided that the intervening requests (and responses) that cause the CSRF problem refer to such resources, no redirects to the login page would occur, and the problem would be solved.

Today, I handle this situation by bypassing auth for those resources altogether (`--skip-auth-routes`), which is OK for my current application. But I have also seen apps where those static resources needed to be protected by auth. 

If there was such an option (say `--treat-routes-as-xhr`), if a non-authenticated request matches the regex at `--skip-auth-routes`, it would be passed on, if it matches `--treat-routes-as-xhr`, it would be a 40x, and in all other cases the 302 to login.

There are other options such as recognizing certain headers (`x-requested-with` comes to mind), but the above would be my preferred solution.

As for the per-request CSRF, I agree that it would probably a serious task to make this work reliably.

**Comment by Frizlab** [comment]
This ain't fixed AFAIK.

**Comment by Frizlab** [comment]
I think this issue is still relevant.

**Comment by SeWieland** [comment]
For me it helped A LOT to just add "/favicon.ico" to the extraPaths of oauth2-proxy (like robots.txt) ;)
The Chrome browser starts the oauth flow once when requesting the icon (IF NOT CACHED => only on the first login) and a second time during the actual login.

This resolved the CSRF Token problems with any fresh instance of chrome for me.

However, I _still_ receive the error occasionally on the first login to our website a day :(
I'm still not quite sure, why this happens sometimes.

**Comment by Frizlab** [comment]
It will depend on how your website works, but if JS is cached locally, it can pre-fetch a bunch of resources which makes the CSRF token check fail (exactly like the browser pre-fetches the favicon.ico).

**Comment by coronabytes** [comment]
Also fixed the issue by commenting out
#cookie_samesite="strict"

**Comment by ericmeadows** [comment]
I don't like turning off the `cookie_samesite` - isn't it less secure??

**Comment by mazenaissa** [comment]
Hello,
Is there any solution to this issue? We are having the same problem in our production when the user is having 2 tabs that will interact with oauth2 for authentication.

**Comment by toddke** [comment]
I'm seeing this every time I use oauth2-proxy. I don't have multiple tabs open. It also happens across multiple devices [Android, Windows, and Linux], but always using the chrome browser. Haven't tried a different browser.

**Comment by vince-franco** [comment]
I am also seeing this issue with a react/redux app upon login after the cookie expires or is cleared from the browser.

If you don't need any of the information in the callback URL you can redirect the callback url endpoint to the home page with whatever web server you are using, in my case the nginx rewrite looks like this:

`rewrite ^/supercool/callback(.*)$ / redirect;`

I haven't confirmed this 100% solves the problem for every case but we are no longer getting this error via login.

**Comment by toddke** [comment]
Not seeing this all the time, but still observing this periodically. Only way to recover is to clear cookies within chrome.

**Comment by toddke** [comment]
For me, it doesn't matter if `cookie_samesite `is `"lax"` or `"none"`. It will authenticate once, then after some time [I haven't narrowed it down, or whether it's related to docker restart, etc...] I get CSRF failures. The only way forward is to remove my site cookies.

**Comment by SeWieland** [comment]
@toddke have you already checked for possible fetches of other resources during login?
These will lead to CSRF failures as describe in https://github.com/oauth2-proxy/oauth2-proxy/issues/817#issuecomment-895723345 and https://github.com/oauth2-proxy/oauth2-proxy/issues/817#issuecomment-1032818354
Whitelisting the paths of such static resources resolved 99% of our issues.

**Comment by miguelborges99** [comment]
If you do multiple authentication requests at the same time, you may get "csrf failed", because one request will delete/change the CSRF cookie created by the other request. With PR #1708 , you can enable CSRF cookies per request (--cookie-csrf-per-request=true) and you may define a time-to-live for CSRF cookies (--cookie-csrf-expire=5m), to avoid leaving too many CSRF cookies in a session for long time. I think this solves the issue.

**Comment by al-hy** [comment]
Hi,

I am new to using oauth2-proxy, and I am using oauth2-proxy in an Istio service mesh to facilitate user authentication.

I am also noticing a csrf invalid issue with my environment. Wanted to see if anyone has insight on what could be happening. 

I deployed the bookinfo application into my service mesh, and exposed the productpage through an ingress with host name productpage.bookinfo.dev.example.io. 

My oauth2-proxy pod has a CA that is mounted to trust hostnames in *.dev.example.io. 
I have the same CA installed on my laptop, and figured I can use hostname *.bookinfo.dev.example.io based on the wildcard certificate. However, I notice that my browser doesn't trust endpoints at *.bookinfo.dev.example.io endpoints, and only trust endpoints at *.dev.example.io. (i.e. foobar.dev.example.io is trusted as opposed to foobar.bookinfo.dev.example.io)

When I am on my browser, I connect to **productpage.bookinfo.dev.example.io**, oauth2-proxy redirects me to my OIDC provider to authenticate myself. When I get redirected back to the backend service, I get the CSRF Invalid error. This is the error I also see when I inspect the oauth2-proxy log: 
`[AuthFailure] Invalid authentication via OAuth2: unable to obtain CSRF cookie"`

I decided to change my ingress hostname to **productpage.dev.example.io**. After changing the hostname to a use a hostname domain I know my browser trusts, I suddenly stopped experiencing the CSRF invalid error (not sure if this was the solution?) 

Does anyone know what's happening behind the scenes in oauth2-proxy that prompting the CSRF invalid on productpage.bookinfo.dev.example.io as opposed to productpage.dev.example.io? Do untrusted domains trigger a CSRF invalid error?

I'm confused, and trying to understand what's happening.

Thanks!

**Comment by anand188** [comment]
Same error for me [AuthFailure] Invalid authentication via OAuth2: unable to obtain CSRF cookie
any resolution or options to by pass this

**Comment by phllpmcphrsn** [comment]
@al-hy you may want to show your oauth2-proxy config, and Istio resources deployed for it. I'm having a similar issue btw

**Comment by smulikHakipod** [comment]
I do have this issue as well. From looking at the access logs it seems my case is where for some reason, in some cases and not all time, users are accessing `/oauth2/callback` URL directly (with all the GET paramaters). My guess is the user browsers caches those URLs in history, and once users types in the application URL, it suggests going through the `/oauth2/callback` URL for some reason. 

If that is the case, it would be much more meaningful to redirect the user to the login page rather than showing them error and basically blocking their work. Is there a workaround I can implement to make this kind of logic?

Thanks

**Comment by ethanbayliss** [comment]
We had the same issue with multiple simultaneous tabs being open caused CSRF errors. It seemed to be reproduceable by leaving a tab idle for longer than the `cookie-expire`. 

`100.65.199.181:57990 - e3ae1ed3ef798bf85e7fdc87907868dd - aaa@bbb.com [2026/05/06 01:48:24] [AuthFailure] Invalid authentication via OAuth2: CSRF token mismatch, potential attack`

To fix we amended our CSRF options in OAuth2Proxy. Adding `--cookie-csrf-per-request=true` seemed to fix and we no longer see the error.
