### ISSUE TITLE
oauth2-proxy does not check all github emails against allowlist

### ISSUE THREAD

**Issue by drewwells** [oauth2-proxy/oauth2-proxy#821]
## Expected Behavior
oauth2-proxy fetches all emails from github (this works today)
oauth2-proxy compares each email against allow list
oauth2-proxy uses email that matches to authenticate

## Current Behavior

oauth2-proxy fetchs all emails from github
oauth2-proxy uses primary email to authenticate
oauth2-proxy denies on primary email only

## Steps to Reproduce (for bugs)

Set a github account and have your authenticating email be the non-primary. For a user,
Primary email: user@deny.com
Secondary email: user@allow.com

Setup oauth2-proxy with allow-domain allow.com
Attempt to login, it will fail

## Context

Corporate employees don't always have their company email as the primary email on github. As a result, we are unable to enforce @company.domain allowlist filters.

## Your Environment

- Version used:
quay.io/pusher/oauth2_proxy:v4.0.0

**Comment by NickMeves** [comment]
Thanks for the report!  I'm taking a look at refactoring how we do authorization and I'm starting the refactor here with Github included: https://github.com/oauth2-proxy/oauth2-proxy/pull/796

I'll keep this in mind as we look at refactoring the authorization logic in all the providers.

**Comment by drewwells** [comment]
Did this get resolved in the above PR?

**Comment by NickMeves** [comment]
I don't think so.

We need a contributor that uses the GitHub provider to help out. I got it aligned superficially to the new authZ patterns in backwards compatible, stable ways.

But anything that changes core behavior I need help from someone who uses the provider and can do integration testing in realistic scenarios.

Help on the GitHub provider would be greatly appreciated. It has some older logic and I've made note of some logic that is blocking other PRs due to security issues: https://github.com/oauth2-proxy/oauth2-proxy/pull/770#issuecomment-734450030

**Comment by drewwells** [comment]
Please reopen

**Comment by marsavela** [comment]
I believe this is still relevant. Why would OAuth authorize only the primary email?

It should check all the emails and authorize the user if it has a verified email that matched the OAuth email domain.

Is there a solution for this?

**Comment by marsavela** [comment]
Please reopen

I believe this is still relevant. Why would OAuth authorize only the primary email?

It should check all the emails and authorize the user if it has a verified email that matched the OAuth email domain.

Is there a solution for this
