### ISSUE TITLE
Group/Role Access Restriction support in `/oauth2/auth` endpoint

### ISSUE THREAD

**Issue by NickMeves** [oauth2-proxy/oauth2-proxy#831]
In nginx subrequest & Kubernetes ingress auth annotations, a request is checked against the `/oauth2/auth` endpoint and given back a 204 or 401 for an access decision.

Now that we support Groups/Roles in our session, we should be able to specify groups/roles that are allowed to authenticate.

This will allow OAuth2-Proxy to be deployed as a single central access proxy & apps can configure groups/role restrictions themselves in the `nginx-ingress` auth annotations (or similar).

## Expected Behavior

Add support for a querystring to the `/oauth2/auth` endpoint where we can specify groups/roles that are allowed access (as an additional constraint beyond simple access).

This would mirror the new `allowed-groups` flags that use groups/roles to restrict access when OAuth2-Proxy is deployed inline to upstream applications instead of via nginx subrequests.

## Current Behavior

No group/role auth access restriction for nginx subrequests using `/oauth2/auth`.

## Possible Solution

Querystring parameter with a comme delimited list of groups/roles to restrict access to.

## Context

Would simplify the deployment of a central Access Proxy for Kubernetes ingresses -- instead of having to support multiple with different OIDC apps that have different RBAC controls managed at that layer.

## Your Environment

Kubernetes with a central access proxy. Apps that want to add authentication add these nginx ingress annotations:
- `nginx.ingress.kubernetes.io/auth-signin`
- `nginx.ingress.kubernetes.io/auth-url`

- Version used:
v6.1.1

**Comment by NickMeves** [comment]
Assuming this is done via querystring -- best route to support multiple allowed groups?

`?group=foo&group=bar&group=baz`

AND/OR

`?groups=foo,bar,baz` with a delimiter?

**Comment by NickMeves** [comment]
Once we settle on a design -- I think this PR will end up being very simple.

**Comment by toboshii** [comment]
I just want to say that A) You're my hero if this gets merged, I've looked for so long for something that could provide this ability. B) If it's of any value, I prefer the second delimited format as it looks cleaner in what (for myself anyway) would ultimately be an annotation.

**Comment by JoelSpeed** [comment]
Several questions that spring to mind:
- What's the benefit of this being in OAuth2 Proxy over embedded in the app (eg just using OAuth2 Proxy for AuthN)
- How would this interact with `--allowed-groups`, if an admin has configured this flag, does the query string override it? Does it narrow the scope?
- Will this be always on or an opt in feature for administrators to enable?
- Have we considered having multiple "auth only" endpoints with different AuthZ policies associated with them? To that point, could it also have different AuthN?

**Comment by NickMeves** [comment]
So this comes up when OAuth2-Proxy is positioned as a global Access Proxy with no upstreams configured.  In Kubernetes for instance, applications hook into it with these ingress annotations. (I have on my TODO list to make a blog post about this and add more to our docs to advertise the possibilities of this architecture with Kubernetes users).

This saves me from needing to stand up multiple OAuth2-Proxies with various flavors OIDC apps with varying groups access (company wide, engineering only, infrastructure SREs, etc).

(1) Gives the "app" the much easier ability to control group access to a global access proxy via updating an ingress annotation (rather than needing to update backend app code -- a near impossibility with something like limiting prometheus/grafana to infra SREs only for instance).

(2) Good point on `--allowed-groups` - the ingress annotation should only be able to further restrict access beyond what Access Proxy already allows (not add additional groups to allow).  I think by putting this restriction after `getAuthenticatedSession` we'd have that protection: https://github.com/oauth2-proxy/oauth2-proxy/blob/f705d2b5d33ef7b18edc0716823454fcb548a55a/oauthproxy.go#L874

(3) I think always on -- if you can only further restrict access by adding a supplemental querystring to the `/oauth2/auth` endpoint, I see no security risk.

(4) Would this require more configuration on the OAuth2-Proxy side from the central Access Proxy admin? I was trying to think of an architecture to put more power in the app admins hands when hooking into a central OAuth2-Proxy and allowing them to somehow make their RBAC configurations self-service.  Any better ideas than a querystring? Since the annotation was the only area I could see where the app admin had input, I thought configuration data would need to come from that.

**Comment by NickMeves** [comment]
I leaned toward querystring to mirror the `rd` parameter users of this architecture already need to use for the `sign-in` annotation:

```
nginx.ingress.kubernetes.io/auth-signin: https://access-proxy.example.internal/oauth2/start?rd=https%3A%2F%2F$host$escaped_request_uri
nginx.ingress.kubernetes.io/auth-url: https://access-proxy.example.svc.cluster.local/oauth2/auth
```

**Comment by radhus** [comment]
I started working on something similar: supporting multiple `authenticated-emails-file` which can be specified by a query string to `/auth`. I found this issue now afterwards, so I'll await creating a PR until this has settled. [Diff if interested](https://github.com/oauth2-proxy/oauth2-proxy/compare/47710d00945e9d9d3451b401107b8eb7fc7fccd9...radhus:support-multiple-email-files), running it internally and works for me but far from complete and nice :)

**Comment by predakanga** [comment]
I was going to request this feature myself, were it not here.

For my usecase, I also use OAuth2-Proxy as a global auth proxy, and want to restrict specific subdomains to specific groups.

I've tried to achieve the same effect using the `set_xauthrequest` option and logic in the nginx configs, but this has proven quite fragile. To my eyes, OAuth2-Proxy is the perfect place to implement this.

**Comment by shinebayar-g** [comment]
Similar request: https://github.com/oauth2-proxy/oauth2-proxy/issues/775

**Comment by Felk** [comment]
Hey @NickMeves, I saw this contribution and wondered how I would be able to apply this to roles. I see that I can configure multiple ingresses, each with a different `allowed_groups` parameter in its `auth-url`. But, in the case of using the `keycloak-oidc` provider, there does not seem to be an `allowed_roles` parameter similar to how there are both [`--allowed-group`](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/#keycloak-auth-provider) and [`--allowed-role`](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/#keycloak-oidc-auth-provider).

**Comment by alexander-bauer** [comment]
@Felk I've run into the same issue here, and I just discovered a workaround.

## Background

When it comes time for a user to authorize, the tool consuming OAuth2-Proxy's `/auth` endpoint (such as an NGINX ingress controller) issues a request like `GET http://oauth2-proxy.auth.svc/oauth2/auth?allowed_groups=my-allowed-group`, forwarding along with it a token provided by the user. (This is either the ID or the Access token -- I'm not totally clear on which.) OAuth2-Proxy inspects that token for a "claim" (which is to say, what is essentially a dictionary field) called `groups`, which is expected to contain a list of strings. If that list contains `my-allowed-group`, then authorization is granted (assuming other requirements provided as flags to OAuth2-Proxy are met).

So, in order to "hack" this process to check user roles rather than group membership, we simply need to fill the `groups` claim with a list of roles, and adjust our query parameters to `/auth` to match. Fortunately, Keycloak grants us an intimidating degree of control over what is put in to the tokens it generates by way of a subsystem it calls "protocol mappers." Existing installations of OAuth2-Proxy using Keycloak probably make use of a `User Group Membership Protocol Mapper`, which inserts the list of groups (identified by paths) to which a user belongs into a configurably-named claim. If instead, we use a `User Client Role Protocol Mapper`, Keycloak will insert a list of roles (in the format `role:<client>:<role_name>` for client-scoped roles or `role:<role_name>` for realm-scoped roles) into a claim of our choice. If this choice is `groups`, and the "groups" we ask OAuth2-Proxy to look for are in this `role:<client>:<role_name>` format, then it'll be none-the-wiser.

## Implementation

My infrastructure is provisioned with Terraform, and I use the [`mrparkers/keycloak` provider](https://registry.terraform.io/providers/mrparkers/keycloak/4.3.1) for managing Keycloak. Just for context, the consumer of this is an NGINX ingress controller configured by way of the `nginx.ingress.kubernetes.io/auth-url` annotation (and its friend `/auth-signin`); these annotations are added on a per-ingress basis, meaning that I can differentiate authorization on a per-ingress level using query parameters.

### Previous, using Groups

I used a protocol mapper defined roughly like this, which makes the group names available in the `groups` claim.

```hcl
resource "keycloak_openid_group_membership_protocol_mapper" "group_membership_mapper" {
  realm_id  = keycloak_realm.realm.id
  client_id = keycloak_openid_client.openid_client.id
  name      = "group-membership-mapper"

  claim_name = "groups"
}

Combined with this, I used the `auth` endpoint with a URL query like this:

```hcl
locals {
  auth_endpoint = "${local.auth_proxy_base_url}/oauth2/auth?allowed_groups=${urlencode(keycloak_group.group.path)}
}
```
(**Note for anyone trying to sort this out in the future:** please note that `allowed_groups` for Keycloak uses the **path** as opposed to just the name -- even for top level groups this begins with `/`.)

### New, using Roles

Now, I've replaced the original group membership mapper with this client role mapper, **which I've associated to a claim called `groups`**, rather than a more typical `roles`. This is the magic trick.

```hcl
resource "keycloak_openid_user_client_role_protocol_mapper" "user_client_role_mapper" {
  realm_id   = keycloak_realm.realm.id
  client_id  = keycloak_openid_client.openid_client.id
  name       = "user-client-role-mapper"

  claim_name = "groups" # <--- this is the critical piece which "tricks" OAuth2-Proxy into thinking these roles are groups
}
```

```hcl
locals {
  client_name = "oauth2-proxy"
  role_name = "my-example-role"

  # client-scoped roles are "role:<client_name>:<role_name>", and realm-scoped are just "role:<role_name>"
  full_role_string = "role:${local.client_name}:${local.role_name}"

  auth_endpoint = "${local.auth_proxy_base_url}/oauth2/auth?allowed_groups=${urlencode(local.full_role_string)}
}
```

And now, with this configuration, I'm able to differentiate authorization based on user *roles* in a single-backend OAuth2-Proxy. Do beware that I haven't tested realm-scoped roles, so I can't claim to know for sure they behave as expected, but I believe they do.
