### ISSUE TITLE
Dedicated `Bearer` Auth Provider chain with structured configs

### ISSUE THREAD

**Issue by NickMeves** [oauth2-proxy/oauth2-proxy#835]
We seem to get a TON of questions relating to how to do service to service authentication correctly via bearer headers.

SITUATION:
At the moment, this is a little buried in documentation and hacky using the `--skip-jwt-bearer-tokens` & `--extra-jwt-issuers` configuration options. Plus, users not using the OIDC provider get confused and run into issues since these option implicitly rely on pulling public keys from an OIDC `.well-known` location based on the provided issuer URL.

PROPOSED SOLUTION:
In a structured configuration world, I say we separate the human cookie session provider from the bearer session provider -- and allow a chain of bearer providers for the bearer/machine case (like we do now with chained `--extra-jwt-issuers`)

We would use the `CreateSessionStateFromBearerToken` provider method for this auth route -- allowing any interface that implements it to use the pattern.

Any existing users of `--extra-jwt-issuers` can just migrate to a chain of OIDC providers for bearer auth where they setup the issuer & client-id.

CC: @JoelSpeed

**Comment by NickMeves** [comment]
This is still the goal in v8.

**Comment by holyjak** [comment]
Any ideas about what would the configuration of the chain of providers look like? I can think of a number of cases we want to cover:

* tokens from a particular OIDC client id under the same issuer as the one used by oauth
* tokens from any client under the same issuer as oauth's client
* tokens from a particular client under a particular, different issuer (which `--extra-jwt-issuers` used to cover)
* tokens from any client under a particular issuer

And of course we want to support a number of providers so that a number of different tokens may be accepted.

**Comment by NickMeves** [comment]
With structured configs, each provider will have their block of allowed configurations. I foresee the bearer token provider config being distinct from the main interactive config of the provider.

I think just an array or provider config objects (with the chain processed for bearer tokens in the order they are configured)
