### ISSUE TITLE
acr_values request param not sent according to RFC 

### ISSUE THREAD

**Issue by carabj** [oauth2-proxy/oauth2-proxy#836]
The "acr_values" request param according to RFC https://openid.net/specs/openid-connect-eap-acr-values-1_0.html#acrValues should not be sent as "acr".

## Expected Behavior

If configuring a "acr_values", the request param sent to the oidc provider should be "acr_values".

## Current Behavior

Current behaviour is to send the "acr_values" as "acr".

## Possible Solution

Change the request param to "acr_values", as per rfc: https://openid.net/specs/openid-connect-eap-acr-values-1_0.html#acrValues.
If some oidc providers supports the current behaviour with a "acr" request param, make it configurable to select which request param (i.e. "acr" or "acr_values").

## Steps to Reproduce (for bugs)

1.  Configure the "acr_values" in the cfg file
2.  Check the network tab for the sent request to the provider

## Context

Cannot use oauth2-proxy with a standard OIDC provider and select an ACR via the acr_values request param, thus making it impossible to select which ACR to authenticate the user.

## Your Environment

- Version used: 6.1.1

**Comment by NickMeves** [comment]
This is the current code for `6.1.1`: 

https://github.com/oauth2-proxy/oauth2-proxy/blob/e4e5580852dcc8a45cc5c552243416f7a6ae0368/providers/provider_default.go#L81

(This was refactored a bit in a recent PR on master to here https://github.com/oauth2-proxy/oauth2-proxy/blob/f705d2b5d33ef7b18edc0716823454fcb548a55a/providers/util.go#L38)

These look right to me? What configuration did you use to get `acr` instead of `acr_values`?

**Comment by carabj** [comment]
@NickMeves  Yes, you are right, my bad. I got stuck at my OIDC provider stating a bad request, with an "acr" request param in the url. But now when I inspect it, I see that oauth2-proxy sends the "acr_values" as expected, but my OIDC provider does a redirect and changes the request param to "acr".
