### ISSUE TITLE
Groups are not mapped from access token

### ISSUE THREAD

**Issue by blsho** [oauth2-proxy/oauth2-proxy#874]
I'm sending an access token in Authorization header as Bearer to oauth2-proxy with `groups` claim. I expect the JWT Claim is mapped to `X-Forwarded-Groups` for upstream.

## Expected Behavior

`X-Forwarded-Groups` is mapped from `access_token.payload.groups` for upstream.

## Current Behavior

Header `X-Forwarded-Groups` is not send to upstream.

## Steps to Reproduce (for bugs)

1. Obtain an access token from IDP with `groups` claim
2. Send the access token via proxy in `Authorization: Bearer <access_token>`
3. Check request headers received in upstream.

## Context

I'm opening my API for other IDP clients. I'm trying to limit access based on group membership. My configuration:
```
...
--skip-jwt-bearer-tokens="true" \
--extra-jwt-issuers="https://<idp_host>/auth/realms/<realm>=account" \
--allowed-group="TestGroup" \
...
```
When I access the API with browser (via oauth2-proxy redirect; using IDP client from `--client-id`) everything works as it should. When I generate access token with different client and send the token in `Authorization: Bearer <access_token>` than this request fails. When I remove tag `--allowed-group="TestGroup"` and send request with the same access token then request is successfully forwarded to upstream but header `X-Forwarded-Groups` is missing.

## Your Environment

- Version used: latest master commit 8abc4e6d876b2e4a5c348e05927b2c472fdfef9b

**Comment by JoelSpeed** [comment]
Doesn't look to me like group extraction was implemented for `--extra-jwt-issuers` based on https://github.com/oauth2-proxy/oauth2-proxy/blob/8abc4e6d876b2e4a5c348e05927b2c472fdfef9b/pkg/middleware/jwt_session.go#L158-L166

@NickMeves are you aware that this seems to have been missed?

**Comment by NickMeves** [comment]
I wasn't aware - Thanks for bringing this to our attention! I have thoughts:

This gets into that hairy area of conflating the OIDC provider with the (maybe) OIDC-ish issuers that might be pulled with this middleware (because technically this works with a direct `jwks.json` even if a `openid-configuration` isn't present).

Since people can specify these as subsequent chain-able auth routes when using a main provider that isn't OIDC, we've had a lot of bugs in the past when PRs introduced dependencies here on the OIDC provider (which I recall resulted in @JoelSpeed  & I needing to make bugfix PRs to decouple the relationship).

So if an OIDC provider is used, its configuration and options for groups will apply to the first verifier in the chain (from the provider) where the subsequent will use this generic one.

I see the merit in adding a generic `groups` claim extractor to this method to put into the `session.Groups` -- but I would be very cautious about full configurability like the OIDC provider `oidc-groups-claim` allowing other claims to act as the group. ...But maybe it's fine? 😨 

Long term -- this problem would go away with chainable `Bearer` providers that are explicitly configured in a structured config. Then we'd scrap this generic logic.
