### ISSUE TITLE
Undefined behaviour using structured config for upstream servers

### ISSUE THREAD

**Issue by JoelSpeed** [oauth2-proxy/oauth2-proxy#909]
## Expected Behavior

Not sure 🤔 

I thought if I had an upstream of
```
- id: httpbin
  path: /foo
  uri: http://httpbin/bar
```

that the request that hit the upstream would be `http://httpbin/bar/foo`

## Current Behavior

Currently with the above the request that is made to the upstream is `http://httpbin/foo`, the `/bar` is completely lost

## Possible Solution

I think we need to make some changes to the proxy director.

https://github.com/oauth2-proxy/oauth2-proxy/blob/6254ed24ea319302b8cbdd8aaa16f6495c0b4c11/pkg/upstream/http.go#L144

In the basic implementation (in the core http library) there is a part that joins the strings as I was expecting, but we overwrite this with the raw string to ensure that it keeps encoded characters.

If we copied the core implementation out and didn't use the core director at all, we may be able to preserve the behaviour of joining the paths while also keep the encoding that we are doing right now with the raw URI

## Steps to Reproduce (for bugs)

Using my WIP PR #907 

1. Edit the upstream config in `contrib/local-environment/oauth2-proxy-alpha-config.yaml` to include a path on the URI
2.  From the repo root `make local-env-alpha-up`
3.  Request a path on the test server
4. Observe that the path to the upstream doesn't include the path from the URI

## Context

Reverse proxies are hard! We need to do whatever is the most commonly expected behaviour here, I feel like what we do presently is a bit weird, we can't proxy to a subpath of server without that being included in the `path` element <- perhaps this isn't actually a bad thing 🤔

**Comment by iinuwa** [comment]
First off, thanks for your your work on this!

I'm bumping into this issue. I have an application proxied on a sub-path `/app/a` or `http://proxy/app/a`, but the upstream is listening for requests at the root (`/` or `http://upstream/`).
If I run without oauth2-proxy, I can tell my proxy server (NGINX) to trim the sub-path for the upstream, so if I send `http://proxy/app/a/page1.html`, the upstream just sees `/page1.html`. The problem with introducing oauth2-proxy is that I can either:

1. trim the path between NGINX -> oauth2-proxy, which makes oauth2-proxy redirect to the proxy URL root (`http://proxy/page1.html`) rather than the upstream's root (`http://proxy/app/a/page1.html`, which would be `/page1.html` on the upstream) after authentication, which is incorrect, or
2. not trim the path between NGINX -> oauth2-proxy and run oauth2-proxy with a proxy prefix of `/app/a/oauth2`, but then the upstream sees `/app/a/page1.html`, which is also incorrect.

NGINX allows you to configure the path trimming behavior: if you specify an upstream without a path, then entire proxied path is sent to the upstream. If you send it with a path, the proxied path is trimmed.

```
location /app/a {
  proxy_pass http://upstream; # upstream sees /app/a/...
}

# Note trailing slashes
location /app/b/ {
  proxy_pass http://upstream/; # upstream just sees trimmed path, /
}
```

I only modify NGINX configs like once a month, and I always forget exactly how it works, so maybe the same semantics aren't so great to copy and there's a better way to signal how to do this. Or maybe we do want to just copy NGINX so that people don't have to learn yet another syntax... Regardless, I think we should be able to configure this, since different applications have different needs.

**Comment by JoelSpeed** [comment]
> trim the path between NGINX -> oauth2-proxy, which makes oauth2-proxy redirect to the proxy URL root (http://proxy/page1.html) rather than the upstream's root (http://proxy/app/a/page1.html, which would be /page1.html on the upstream) after authentication, which is incorrect, or

Are you using auth request in NGINX or just proxying straight through? If you were to use auth request mode I think you could avoid this issue completely. You can set the redirect via an `rd` query parameter when starting the auth flow, and then handle the proxying to the upstream via NGINX rather than OAuth2 Proxy

> NGINX allows you to configure the path trimming behavior: if you specify an upstream without a path, then entire proxied path is sent to the upstream. If you send it with a path, the proxied path is trimmed.

This behaviour is useful, but also very very confusing and I forget every single time I touch NGINX config which way round it is 😂 I think providing the option to do something like this seems reasonable, but I think an explicit `stripPrefix` option on the upstream may be a better way to provide this support, WDYT?
