### ISSUE TITLE
when protected resource other than Graph api is specified in azure provider the access token will be invalid to query Graph

### ISSUE THREAD

**Issue by weinong** [oauth2-proxy/oauth2-proxy#913]
## Expected Behavior
it should not use the access token destined to the protected resource to query Graph api

## Current Behavior
In azure provider, when protected resource `--resource` is specified to any resource other than Graph api, the access token will not be valid to query graph api for user's email. It results in 401 error: `{"odata.error":{"code":"Authentication_MissingOrMalformed","message":{"lang":"en","value":"Access Token missing or malformed."}}}` in [GetEmailAddress](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/providers/azure.go#L247)

## Possible Solution
There is actually no need to query Graph api for user email. Either the id_token or access_token can be configured to emit such claim. As such, we should check the token's claim first. I believe oidc provider is already doing that.

## Steps to Reproduce (for bugs)

repro script: https://github.com/weinong/brownbag-oauth-oidc/blob/master/01_authorization-code.sh
just change the resource in L21 to a different one.

## Context
This impacts any use of protected resource in Azure AD such as
https://github.com/kubeapps/kubeapps/issues/2118

## Your Environment
Azure AD

- Version used:
5.0.0, but it is the same logic in any other versions.

**Comment by weinong** [comment]
Hi @codablock , saw your PR #753 to add proper support of `--resource`. did you not have this issue where access token issued for `--resource` is used to call graph api?

**Comment by weinong** [comment]
i can repro this on the master branch with options
```
      --provider=azure
      --client-id=<omitted>
      --client-secret=<omitted>
      --cookie-secret=<omitted>
      --upstream=http://localhost:8080/
      --http-address=0.0.0.0:3000
      --email-domain=*
      --pass-basic-auth=false
      --pass-access-token=true
      --pass-authorization-header=true
      --skip-auth-regex=^\/config\.json$
      --skip-auth-regex=^\/favicon.*\.png$
      --skip-auth-regex=^\/static\/
      --skip-auth-regex=^\/$
      --ssl-insecure-skip-verify
      --cookie-secure=false
      --resource=<omitted>
      --azure-tenant=<omitted>
      --scope=<omitted> offline_access openid
```
with error
```
[2020/11/11 21:32:08] [logger.go:508] Error creating session during OAuth2 callback: unexpected status "401": {
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Access token validation failure. Invalid audience.",
    "innerError": {
      "date": "2020-11-11T21:32:08",
      "request-id": "5e172d16-42c5-4a57-af6f-5b908d27b4ce",
      "client-request-id": "5e172d16-42c5-4a57-af6f-5b908d27b4ce"
    }
  }
}
```

**Comment by lindhe** [comment]
Are we still waiting for that refactoring?

**Comment by codablock** [comment]
@weinong I finally found time to work on this again. I'm now in the middle of migrating from our forked oauth2-proxy back to the upstream one with my PRs merged. I stumbled across the exact same issue now.

I also figured out now why I did not have this issue initially. It was because the failure of getting the profile and the EMail from it were silently ignored in the old codebase, as can be seen here: https://github.com/oauth2-proxy/oauth2-proxy/blob/v6.1.1/oauthproxy.go#L308.

The interesting thing is that nothing in the code relied on the EMail afterwards and everything working as expected. That's maybe because I'm not using oauth2-proxy as a reverse-proxy but as an external auth provider for nginx (kubernetes ingress-nginx to be specific).
