### ISSUE TITLE
option prefer_email_to_user don't fallback to user 

### ISSUE THREAD

**Issue by jlore-talend** [oauth2-proxy/oauth2-proxy#933]
## Expected Behavior
In version 6.1.1 when you use prefer_email_to_user oauth2-proxy set email instead of user only if email exist
so when you use htpasswd you don't have email and oauth2-proxy set the user.

In future 7.0.0 this option does not work at all because you don't check if email exist.
When you use htpasswd you don't have the email and oauth2-proxy don't set the http header "X-Forwarded-User"

Expected Behavior is to fallback to the user when the email is empty or not defined.

## Current Behavior

When using the option prefer_email_to_user and email doesn't exist the http header "X-Forwarded-User" is not set.  

## Possible Solution

I look the source code but i can't figure out how to test if a field email exist in the session 

## Steps to Reproduce (for bugs)

1.  Start oauth2-proxy with htpasswd file, the option "prefer_email_to_user" and debug upstream 
2.  make a http request basic auth 
3.  look at the upstream request header 
4.  check missing header "X-Forwarded-User".

**Comment by JoelSpeed** [comment]
This change was a conscious change as part of the work to rework our header injection configuration. Having this fallback within the code means that the output of the proxy is non-deterministic and can very from user to user. This doesn't give guarantees to the services that consume the headers we are injecting and leads to confusing circumstances.

Could you explain a little more about your use case for the prefer email option and perhaps we can discuss potential solutions or ways we can help you

**Comment by rbailly-talend** [comment]
Hi @JoelSpeed, I'm working with @jlore-talend on this issue. 

Our use case is to have 2 authentication method (Basic & OAuth) in front of our upstream. Then we can read the `X-Forwared-User` and `X-Forwarded-Role` headers to find out if the user has been logged and what permissions to give him.

When using Basic Auth the username is correct. But when using OAuth the username is a UID (considered a sensitive data), which is why we would like to have the email instead.

So from the documentation we saw the `--prefer-email-to-user` and decided to give it a shot. Now the Basic Auth does not set the `X-Forwared-User` header, causing a 401 on the upstream side.

I understand you point about deterministic behavior. Maybe we can update the [documentation](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview) about the `--prefer-email-to-user` flag, because it is a bit misleading. Especially the part ` Will only use Username if Email is unavailable`.

**Comment by jlore-talend** [comment]
I use oauth2-proxy in reverse proxy mode with 2 auth
first is oidc auth, this authentication pass 3 headers to upstream : 
X-Forwarded-User ==> uid oidc
X-Forwarded-Email ==> email
X-Forwarded-Preferred-Username ==> email
seconde is basic auth, this authentication pass 1 headers to upstream : 
X-Forwarded-User ==> user htpasswd

My backend read the header X-Forwarded-User to show the user(not a uid) or email of the user

In 6.1.1 when you use prefer_email_to_user it's work because oidc provider change the header X-Forwarded-User from user to email and htpasswd don't change the value so I have user email for oidc and user for basic auth

In 7.0.0 when you use prefer_email_to_user, the oidc provider change X-Forwarded-User from user to email but htpasswd don't have email in claim so the header "X-Forwarded-User" is not set.

if i remove prefer email_to_user, the oidc provider set user uid from pid in "X-Forwarded-User" and htpasswd set the user in the header "X-Forwarded-User"

**Comment by JoelSpeed** [comment]
> I understand your point about deterministic behavior. Maybe we can update the documentation about the --prefer-email-to-user flag, because it is a bit misleading. Especially the part Will only use Username if Email is unavailable.

The documentation should be updated you are correct.

> Also if it's the expected behavior to remove this feature in 7.x, maybe we can mention this in the Changelog as a Breaking Change.

Yes, this will need updating in the changelog, apologies, I completely forgot to add that note.

> When using Basic Auth the username is correct. But when using OAuth the username is a UID (considered a sensitive data), which is why we would like to have the email instead.

So in this case, I have a few questions:

1. Can you upstream utilise two separate headers for the auth? IE could you have one for basic auth users and one for oauth users?
2. What would happen if you upstream received two Authorization headers? We have some WIP to add alpha configuration which would allow you to configure so that both email and user basic auth would be sent to the upstream, obviously only if they are non empty. So in this case you would get one value for basic auth users, as happens now, but for oauth2 users you would get 2 values for the header, this may or may not be accepted by your upstream server.
3. One idea I had been toying with was to allow users using the basic auth functionality to extend the configuration and add a description of the values for the user. Eg they could set the user and email, groups etc that should be sent to upstreams if a particular basic auth user is used

**Comment by rbailly-talend** [comment]
> 1. Can you upstream utilise two separate headers for the auth? IE could you have one for basic auth users and one for oauth users?

Well, the upstream is an open source project and it doesn't support having to look at different headers for Authorization.

> 2. What would happen if you upstream received two Authorization headers? We have some WIP to add alpha configuration which would allow you to configure so that both email and user basic auth would be sent to the upstream, obviously only if they are non empty. So in this case you would get one value for basic auth users, as happens now, but for oauth2 users you would get 2 values for the header, this may or may not be accepted by your upstream server.

Working with `Authorization` headers has been painful, this why we switched to using the `X-Forwared-User` and `X-Forwarded-Role` headers instead, relying completely on the proxy for the Authentication part.

> 3. One idea I had been toying with was to allow users using the basic auth functionality to extend the configuration and add a description of the values for the user. Eg they could set the user and email, groups etc that should be sent to upstreams if a particular basic auth user is used

I think that would indeed be helpful, this would mean that in the configuration we can map a username from the `htpasswd` file to an email+roles ?

**Comment by JoelSpeed** [comment]
> Working with Authorization headers has been painful, this why we switched to using the X-Forwared-User and X-Forwarded-Role headers instead, relying completely on the proxy for the Authentication part.

Sorry I meant the `X-Forwarded-*`, if for example you had in the request `X-Forwarded-User: <email>, <name>` or `X-Forwarded-User: <email>; X-Forwarded-User: <name>`, do you know what the upstream project would do? These are valid in the HTTP spec and it _should_ be able to handle this and use the first value if it needs a value. I think this could be achieved using our new alpha config with something like

```
injectRequestHeaders:
- name: X-Forwarded-User
  values:
  - claim: email # Add the email if it's not empty
  - claim: user # Add the user if it's not empty
```

> I think that would indeed be helpful, this would mean that in the configuration we can map a username from the htpasswd file to an email+roles ?

@NickMeves WDYT to this, allowing users to basically describe the session they would like to see as part of the htpasswd file 🤔  It would mean we have to solidify the sessionstate and ensure it's as we want it before we make this public, or use a substructure of it somehow

**Comment by rbailly-talend** [comment]
So we checked the behavior of the upstream when it receive multiple `X-Forwarded-For` headers, and what we see is that it takes the last value. So basically it works, but we would need to have the user in the first header, and the email in the second (so order matters).

**Comment by JoelSpeed** [comment]
Ordering would be preserved based on the order in the configuration file, so we have a workaround for those who will be losing this internal fallback by the looks of things

**Comment by NickMeves** [comment]
> @NickMeves WDYT to this, allowing users to basically describe the session they would like to see as part of the htpasswd file 🤔 It would mean we have to solidify the sessionstate and ensure it's as we want it before we make this public, or use a substructure of it somehow

I think we had on our minds implementing a dynamic part of the session (substructure route?) for arbitrary user specified data in the future to support the concept of dynamic claim -> header mapping. The feature a lot of the former Louketo users have been missing from that project.

The place I eventually want to throw `PreferredUsername` and make `User`, `Email` & `Groups` or 3 canonical top level fields.

Does that future concept give us flexibility for handling this?

**Comment by JoelSpeed** [comment]
I believe it does yes, I imagine the current htpasswd file would end up with a modified structure so that you end up with a `map[string]SessionState`, then when the user authenticates using a key, their session is loaded from the SessionState value at the given key. We may want to consider omitting some fields though, I imagine something like `CreatedAt` not to be useful in this case.

If we are only using a subset, it would mean we don't need to wait for the transition to happen, we could just crack on with this feature and make the change

**Comment by NickMeves** [comment]
It sounds like we want it less tied to all `SessionState` fields (so skip time & tokens). And want to extend the htpasswd file (or adjacent file) to associate the users with attributes that populate the session? Emails & Groups probably being enough?

Making sure I'm following the idea correctly: We want to provide more identity elements to htpasswd based auth so we behave more like an IdP? E.g. a unix like representation of users?

**Comment by JoelSpeed** [comment]
Yeah I think that's what I'm leaning towards at this point too. Perhaps allowing them to override the username too? And maybe eventually allow an additional claims map?

**Comment by NickMeves** [comment]
If we just allow in a flat claim object now that matches IDToken payload structure, we will be covered with the way we process claims in other providers. And potentially be future proofed for extra claim processing we might want to bolt on?

**Comment by NickMeves** [comment]
```
{
 email: me@me
 groups: [ blah blah ]
 extra: foo
 more_extra: bar
}
```

**Comment by JoelSpeed** [comment]
> If we just allow in a flat claim object now that matches IDToken payload structure, we will be covered with the way we process claims in other providers. And potentially be future proofed for extra claim processing we might want to bolt on?

That makes sense, but we then have to convert this into a `SessionState` before we can use it? So why not just have some go object that we know the structure of for this rather than claim processing.  I'm thinking changing to something like below:

```
type SessionClaims struct {
  User string
  Email string
  Groups []string
  Extra map[string]interface{}
}

type SessionState struct {
  SessionClaims
  CreatedAt *time.Time
  ExpiresAt *time.Time
  ...
}
```
