### ISSUE TITLE
oauth2_proxy is not passing basic auth back to the server

### ISSUE THREAD

**Issue by raz3r** [oauth2-proxy/oauth2-proxy#935]
Hi,

I am using an old version of [oauth2-proxy](https://github.com/bitly/oauth2_proxy) but I believe it applies to this version as well, help would be really appreciated. Also if you know that this issue is solved with the current version of oauth2_proxy I may be willing to update. Basically I have oauth2_proxy on top of a server which requires basic auth on its own for some paths. The unprotected paths work like a charm, the protected paths ask me for username and password but then it seems like those are not being passed back to the server, like oauth2_proxy is rewriting them or stripping them. To prove this, if I remove oauth2_proxy and just use nginx it works.

## Expected Behavior

Basic auth should be passed to the server behind oauth2_proxy.

## Current Behavior

Basic auth is not being passed to the server behind oauth2_proxy.

## Your Environment

nginx: 1.16.1
oauth2_proxy: 2.2.0
I am using Google as provider.

One thing I've noticed from the logs. The actual basic auth user is displayed in the nginx server logs but in the oauth2_proxy server logs it is being replaced by the Google user instead.

**Comment by JoelSpeed** [comment]
If your backend server already supports basic auth, do you need OAuth2 Proxy in front of it? 

The intention of the basic auth features for OAuth2 Proxy are either to allow users to login to servers that do not currently support auth, by using basic auth credentials.

Or to allow users to share a common basic auth password which will be proxied to the upstream server when they authenticate with some service such as google. Eg you can have it so that an basic auth header is injected with the username as the email from the identity provider, and the password as some shared static password

I'm not sure what benefit or feature of OAuth2 Proxy you are trying to use here

**Comment by raz3r** [comment]
I know it's weird but unfortunately it's a behavior of our ERP that I can't change. It works like that for some path. Before I spend hours installing and configuring the new version would you be so kind as to confirm whereas it will work or not? This information would be greatly appreciated.

**Comment by raz3r** [comment]
Update, now I have a brand new installation with latest version of OAuth2 Proxy but I have the same exact issue.

**Comment by raz3r** [comment]
Another question, is there a way to set cookie-domains to multiple domains? If so, how?

**Comment by JoelSpeed** [comment]
If you provider cookie-domains multiple times as a flag (`--cookie-domain .foo.bar --cookie-domain .bar.foo`), the logic will look at the host header and pick the best match (longest match) for the request when creating new cookies
