### ISSUE TITLE
Add User Groups and Roles to Response Headers

### ISSUE THREAD

**Issue by Bibob7** [oauth2-proxy/oauth2-proxy#940]
## Expected Behavior

In the future, we will have a huge list of groups and roles for users. We don't want to add this list to the access_token, because it will increase the size of the token a lot and with with this also the size of the request the user has to send.

Instead, I would like to enable oauth2-proxy to fetch a list of all groups and roles from the idp with the help of the access_token and the user info endpoint of the idp. This list of groups and roles, I would like to add to a response header to make it available for the upstream service.

## Current Behavior

It could be, that this is already possible somehow, but I'm not sure how. Maybe you can explain shorty, how this can be done.

## Possible Solution

If it is currently not possible, I would like to implement it.

**Comment by JoelSpeed** [comment]
I believe this should be possible in our next release. @NickMeves is working on supporting groups so that you can load them from either the ID Token or from the userinfo/profile URL on the IDP. This list of groups will then be stored in the session (which can be cookie based or redis based presently) then will be added to headers as either `X-Forwarded-Groups` or `X-Auth-Request-Groups` based on your configuration

**Comment by NickMeves** [comment]
https://github.com/oauth2-proxy/oauth2-proxy/pull/936

Currently implemented to try to pull groups/role from a userinfo endpoint if they aren't already set via an IDToken claim for the OIDC Provider.

**Comment by NickMeves** [comment]
@Bibob7 #936 Just merged which should cover all this.  Give it a whirl and let us know how it works!
