### ISSUE TITLE
Cookie Secret Rotation

### ISSUE THREAD

**Issue by Bibob7** [oauth2-proxy/oauth2-proxy#963]
## Expected Behavior

If I want to change the cookie secret, it should be possible to use two cookie secrets in parallel. For encryption oauth2-proxy will use the new cookie secret and for decryption, it will try to decrypt with the two existing secrets. With this behavior it would be possible to exchange the cookie secret over time.

## Current Behavior

It is only possible to use one cookie secret. If we would change it, all existing cookies are invalid, because they can not be decrypted anymore.

## Possible Solution

Optionally it should be possible to configure two cookie secrets with a clear order. For encryption, oauth2-proxy will always use the first secret. For decryption, it will first try to use the first secret and as a fallback it will try t decrypt with the second secret.

## Context

If we would change the cookie secret, all existing cookies are invalid, because they can not be decrypted anymore.

## Your Environment

- Version used: 6.1.1

**Comment by JoelSpeed** [comment]
This seems like a reasonable feature to add!

We need to make sure that it's still possible to invalidate old sessions by changing the cookie-secret, but otherwise I'm not too concerned. If we can add this in a backwards compatible way perfect, but let's create some discussion about how this could be implemented

**Comment by NickMeves** [comment]
I've been thinking about this recently too 😄 

I think we implement it in the same way similar products in the encryption space do key rotations:

We allow multiple entries, where the first represents the newest `cookie-secret` to perform encryption & cookie signing. 

When receiving an existing session that is encrypted and signed with an old secret, we work our way through the allowed secrets (ideally this is just 2 at most and you clean up quickly after the rotation).

The first (new) one will fail signature validation, but a later one will pass and then we can move onto session decryption using that secret. The cookie HMAC validation is key because cookie sessions use AES-CFB which is an unauthenticated cipher (due to IV collision concerns in AES-GCM).

Should be completely backwards compatible if implemented as a list that we just loop through and perform signature validations.

**Comment by JoelSpeed** [comment]
Taking this approach, we would want to rename the `cookie_secret` and `OAUTH2_PROXY_COOKIE_SECRET` config and env var names to be plurals appropriately, so this would be a breaking change

**Comment by NickMeves** [comment]
Ack, the dreaded plural breaking change, I always forget 😅 

A second flag then that is array based that contains any rotated cookies? `rotated_cookie_secrets`?

**Comment by NickMeves** [comment]
Hmmm, this might be tough to use an array if any underlying secrets weren't Base64 encoded and included `,` as one of their values. Might just need to support a single historical secret during a rotation window and not multiple?

**Comment by JoelSpeed** [comment]
I would suggest maybe `previous_cookie_secrets` but yeah, a second option could be better and would be more explicit about the behavior. Encoding logic like top one of the list is likely to break or confuse people so actually, this will likely be better as a separate option, great idea!

> single historical secret during a rotation window and not multiple?

I would imagine 1 would be enough, how often are people rotating their cookie secrets? In structured config world, this would be a list of `SecretSources` so would be fine 🤔

**Comment by JoelSpeed** [comment]
Also, we need to work out how this works with the `client-secret-file` option, which would presumably want to support this too?

**Comment by NickMeves** [comment]
That's related to the OAuth provider `client_secret` right? Should be unrelated to our `cookie_secret` used in AES & SHA256 HMAC I think.

**Comment by JoelSpeed** [comment]
Doh, yep, good point! Ignore that previous comment 🤦‍♂️

**Comment by Bibob7** [comment]
Up
