### ISSUE TITLE
Option to always return 401

### ISSUE THREAD

**Issue by gboor** [oauth2-proxy/oauth2-proxy#971]
## Expected Behavior

I would like to have a configurable option that will always return a 401 instead of a redirect to the auth provider.

## Current Behavior

As far as I can see, this is not currently possible. If you open a URL protected by oauth2-proxy in a browser, it will always redirect. It does return 401 if you do an AJAX request on the URL.

## Possible Solution

Some boolean config parameter that handles this. The logic must already be there for ajax/non-ajax.

## Steps to Reproduce (for bugs)

1. Set up oauth2-proxy
2. Go to the URL and get redirected

## Context

I have several Kubernetes deployments that use oauth2-proxy. Frontends and backends are generally separated into 2 deployments with their own docker images etc.. I serve the backend on the same domain as the frontend, but under a different URL. I.e.; if the frontend is on www.my.tool, then the backend is on www.my.tool/api/v1. Having oauth2-proxy with the same config on both frontend and backend works fine here, since the cookie is shared (same domain).

If I go to the frontend, I get redirected to the auth provider - good. If I remove the cookie and try to do a request to the backend, I get a 401 - also good. If I open the URL of the backend directly in my browser, it redirects me to the login - this is the one case  that is not good. I would prefer it just show a 401 page and do nothing.

## Your Environment

- Version used: 6.1.1.

**Comment by JoelSpeed** [comment]
This has been asked for a few times and I thought we had a PR in flight to fix it, but can't seem to find it.

My 2 cents given the current state of play, is that we are currently underway with a massive overhaul of the provider logic. Part of this will enable multiple providers at once.

I would envisage some option such as `disableLogin` for each of the providers that means it won't be available on the login screen, but could be used to decode existing cookies or Auth headers.

If all providers have `disableLogin: true`, then we should return a 401 instead of redirecting to the sign in page. This I think would be appropriate for your use case.

The question is whether implementing this option before we migrate to the multiple providers will cause a headache for those implementing it, or whether we should wait until that work is done.

**Comment by gboor** [comment]
That option works for me and currently it's more of an annoyance than a problem, so I would definitely wait until the new source base is stable.

**Comment by vanyakosmos** [comment]
This is still a problem for us because we have to configure special behaviour on o2p level for backend and frontend in order to return 401 and 302 respectively. It would be really convenient to configure simple auth check w/o mandatory login redirect and this case seems logical for RESTful APIs.
