### ISSUE TITLE
allowed groups ignored when in JWT passthrough mode

### ISSUE THREAD

**Issue by rickardp** [oauth2-proxy/oauth2-proxy#993]
When using `--skip-jwt-bearer-tokens=true`, the X-Auth-Request-Groups header is not populated, and the allowed groups check is not done.

## Expected Behavior

When authenticating against an OIDC provider the logic works and the access token returned is a JWT token that has its groups property set in the claim configured (in my case this is called "roles"). I expect that this list is checked for the existence of the allowed groups, as well as that the matched group is exported to the X-Auth-Request-Groups header.

## Current Behavior

List of groups is empty when sending "Authorization: Bearer ..." headers.

## Possible Solution

Allow the specification of which attribute of the JWT token contains the groups, just like for e.g. email.

- Version used: master/a0d37518e0192e00bb20213c3d507760dcefcfb2

**Comment by NickMeves** [comment]
None of the groups or authorization logic that is in master is in a release yet. They will all be released in V7 which is wrapping up (https://github.com/oauth2-proxy/oauth2-proxy/projects/3).

We JUST recently fixed our docs problem where they weren't version stamped and new docs additions in master were in our documentation but not in a stamped release.

If you are using v6.1.1, it could very well be our v6.1.1 doc stamping happened after a few of the v7 PRs if you are seeing this functionality in the documentation.

**Comment by NickMeves** [comment]
Here's the implementation on master if you want to peek and see if you can identify your bug case: https://github.com/oauth2-proxy/oauth2-proxy/blob/8e02fac2cc0ae61552d3244b313eb8e0dcd2d545/providers/oidc.go#L181

Bearer tokens use that `CreateSessionFromToken` implemented in your provider.  When OIDC makes a `SessionState` from an ID Token in either the interactive or bearer flow, it calls the same underlying `buildSessionFromClaim`

https://github.com/oauth2-proxy/oauth2-proxy/blob/8e02fac2cc0ae61552d3244b313eb8e0dcd2d545/providers/provider_data.go#L142

**Comment by rickardp** [comment]
@NickMeves Yes, I found that out the hard way and forgot to put that the issue. I tried building myself from master but I got the same issue. Group validation works when the token is received from OIDC but not when the token is validated offline. Possibly it is something I need to configure but I cannot find out how to configure the checking of group claims for JWT tokens. I think possibly the problem here might be that the name of the claim in the JWT token is not necessarily the same as the OIDC claim.

**Comment by NickMeves** [comment]
I think the new flag you might want to try is `--oidc-group-claim`.

The `groups` claim in OIDC isn't official in the specification like other claims. While most OIDC Identity Providers have used it, its name (and underlying format) is not consistent and we've had a few PRs to help handle the corner cases around it.

It sounds like you need to set it to `roles` based on your issue?

The other area that might explain the difference: interactive logins will try to extract the group first by pulling the group claim from the ID Token claims -- and if that doesn't work, it will pull it from your IdP's `userinfo` endpoint by sending your Access Token.

Bearer auth only extracts claims (so it doesn't result in s subrequest to your IdP every request causing a ton of latency). You might want to compare your token claims manually against a manually call to your IdP's userinfo endpoint.

Here's the userinfo / profileURL enrichment code interactive sessions get: https://github.com/oauth2-proxy/oauth2-proxy/blob/8e02fac2cc0ae61552d3244b313eb8e0dcd2d545/providers/oidc.go#L79

**Comment by NickMeves** [comment]
And you aren't using `--extra-jwt-issuers` with extra OIDC provider tokens that are different than your primary OIDC provider you've configured right?

Those get a barebones OIDC processor and don't inherit the primary OIDC provider settings (since technically they aren't your configured provider).

https://github.com/oauth2-proxy/oauth2-proxy/blob/8e02fac2cc0ae61552d3244b313eb8e0dcd2d545/pkg/apis/middleware/session.go#L20

**Comment by rickardp** [comment]
Yes, I am using `--extra-jwt-issers` because that is how the issued JWT token looks (not sure if it follows spec or not, but it's Okta in this case, which is a fairly popular service)

**Comment by NickMeves** [comment]
So you have two different providers connected that have distinct issuers & clientIDs/audiences?

By default with Bearer auth, it will use you configured provider's OIDC details first for ID Token verification (and gain the full configurability of that provider), then it will use any subsequent ones provided in the extra-jwt-issuers with the barebones OIDC token validator I linked.

We've had PRs in the past that have tried to make OIDC main provider options bleed over to the basic OIDC settings -- but this broke a lot of installations where people had a non-OIDC provider as the main IdP (Google, Kaycloak, Gitlab, Azure came up frequently). So I am very hesitant to cross that bridge again moving forward, especially since we plan to overhaul this in the next major version.

Long term, we are working to support multiple providers. In the V8 structured configuration overhaul we are working, my goal is for the configuration to specify a chain of bearer auth providers (instead of `extra-jwt-issuers` which only allows issuer=audience). Those will allow any provider that implements `CreateSessionFromToken` to be added to the chain with whatever rich configuration tweaks they need (e.g. `roles` claim in your case).

**Comment by NickMeves** [comment]
We could make custom `extra-jwt-*` flags that mirror `oidc-groups-claim` and `oidc-email-claim` to allow configuration of just the provider agnostic OIDC logic for extra JWTs -- 🤔

**Comment by JoelSpeed** [comment]
> We could make custom extra-jwt-* flags that mirror oidc-groups-claim and oidc-email-claim to allow configuration of just the provider agnostic OIDC logic for extra JWTs -- 🤔

While we could do this, we are working on multiple provider support at the moment, which would mean we get this for free (since we plan to make the extra jwt issuers just extra providers), perhaps we could spend our time on that effort instead? 🤔

**Comment by NickMeves** [comment]
I'm inclined to agree -- in thinking about it more, I just realized the `authorize` part of the flow is tied to the main Provider at the moment.

Even if we did support group extraction from adhoc extra ID Tokens, it feels weird to shoehorn them into the main provider's authorize implementation.

That'll be something we need to keep in mind with multiple providers (especially the chainable bearer token providers idea).
