### ISSUE TITLE
Error loading cookied session: http: named cookie not present, removing session

### ISSUE THREAD

**Issue by Christoph-Raab** [oauth2-proxy/oauth2-proxy#998]
## Expected Behavior

Login succeed

## Current Behavior

From time to time I get an exception in the logs stating

```
[logger.go:508] Error loading cookied session: http: named cookie not present, removing session
```

In some cases this led to expired token for a logged in user, which is passed to the application and checks for expiration as well, so user is logged out.

Furthermore it appears after a restart of oauth2-proxy (but no restart of redis storage), if a once logged in user revisits the website. Not sure if this is the correct behavior.

This happens with named cookie (azuread) or with default cookie name. So it's different from https://github.com/oauth2-proxy/oauth2-proxy/issues/978.

## Context

I am running v6.1.1 in a kubernetes cluster with istio and redis for session storage with AzureAD.

**Comment by NickMeves** [comment]
So that `http: named cookie not present` is the text of a `http.ErrNoCookie` error. If you are using Redis, I'm pretty sure this is the exact area you are getting the error:

https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/sessions/persistence/ticket.go#L92

That's calling the Golang `http.Request` `Cookie` method on the configured cookie name. No special logic - so seems like the cookie wasn't in the request.

And this isn't from users who's sessions have expired with the `--cookie-expire` setting (default 168h0m0s) so their browsers didn't send the session cookie anymore? That would trigger these logs you are seeing and would be my guess and what's happening.

**Comment by Christoph-Raab** [comment]
So I checked and monitored for some time. Seams you are right, but I find it a bit misleading to be honest. I have all logs disabled and get multiple errors every day, although it's the expected behavior.
